### ISSUE TITLE
报告一个bug

### ISSUE THREAD

**Issue by candebbs** [AriaLyy/Aria#100]
下载一个文件，如果用户手动删除这个文件，如果再调用
` Aria.upload(MyHadDownloadActivity.this).load(path).removeRecord();`

因为文件不存在了，删除会造成崩溃，删除不了记录。

**Comment by AriaLyy** [comment]
我这测试是正常的呢
能否提供一下logcat的日志？

**Comment by candebbs** [comment]
```
java.lang.IllegalArgumentException: 上传文件不存在
at com.arialyy.aria.util.CheckUtil.checkUploadPath(CheckUtil.java:113)
at com.arialyy.aria.core.upload.UploadReceiver.load(UploadReceiver.java:47)
```
删除代码：
                ```
String path = ((DownloadEntity) mData.get(position)).getDownloadPath();
                String name = ((DownloadEntity) mData.get(position)).getFileName();
                LogUtil.e("pdfDownload", "had path " + path);

                if(id == R.id.pdf_open_bt) {

                    Bundle bundle = new Bundle();
                    bundle.putString("ebook_pdf", path);
                    CommonUtil.startActivity(mContext, OpenPDFActivity.class, bundle);

                } else { // 删除pdf

                    mData.remove(position);
                    adapter.notifyDataSetChanged();

                    if(!TextUtils.isEmpty(path)) {
                        if(FileUtils.fileIsExists(path)) {
                            Aria.upload(MyHadDownloadActivity.this).load(path).removeRecord();
                            FileUtils.delFile(path);
                        } else {
                            T.ss("数据出错，不能删除这条记录");
                        }
                    }

                }
```

**Comment by AriaLyy** [comment]
明白了，这是上传的一个逻辑问题，上传需要验证文件路径，才能进一步操作，就和判断下载地址是否为null一样，下个版本我专门增加一个不需要验证文件路径的api吧。
现在你可以通过ORM模型直接删除：
```java
UploadEntity entity = DbEntity.findFirst(UploadEntity.class, "filePath=?", filePath);
entity.deleteData();
```

**Comment by candebbs** [comment]
好的
