### ISSUE TITLE
Aria.download(this).removeAllTask(false) 删除任务时报错

### ISSUE THREAD

**Issue by lyxc** [AriaLyy/Aria#139]
如题，在调用Aria.download(this).removeAllTask(false)方法时，报如下错误：
--->CockroachException:Thread[main,5,main]<---
                                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.arialyy.aria.core.download.DownloadGroupEntity.getDirPath()' on a null object reference
                                                                      at com.arialyy.aria.util.CommonUtil.delDownloadGroupTaskConfig(CommonUtil.java:240)
                                                                      at com.arialyy.aria.core.command.normal.CancelAllCmd.handleDownloadGroupRemove(CancelAllCmd.java:63)
                                                                      at com.arialyy.aria.core.command.normal.CancelAllCmd.executeCmd(CancelAllCmd.java:50)
                                                                      at com.arialyy.aria.core.AriaManager.exe(AriaManager.java:166)
                                                                      at com.arialyy.aria.core.download.DownloadReceiver.removeAllTask(DownloadReceiver.java:290)
                                                                      at com.sdjsl.congress.module.DirectorMaterialActivity.DownGroupFile(DirectorMaterialActivity.java:263)

**Comment by AriaLyy** [comment]
这是哪一个版本的代码？

**Comment by lyxc** [comment]
使用版本:3.3.2
使用场景：同一个文件使用组文件连续下载时，第一次下载完成后，再点击下载，下载进度始终为0，我猜测是第一次下载完成后，第二次再下载该url下文件，有该文件的下载任务了，所以不能正常下载。于是我使用了removeAllTask这个方法，将下载的任务清除，然后再次下载。这种操作偶尔就会报上面的问题。

**Comment by AriaLyy** [comment]
你用3.3.5版本试试呢，我这测试是可以删除任务组的

**Comment by lyxc** [comment]
这个错误是偶尔出现，没有完全复现出来。另外，我再第一次下载完某个URL下面的文件后，如果不使用removeAllTask方法删除任务，有没有其他方法来执行重新下载？

**Comment by AriaLyy** [comment]
有一个reStart()的api

**Comment by AriaLyy** [comment]
3.3.6已经处理了这个null判断
