### ISSUE TITLE
空指针

### ISSUE THREAD

**Issue by Pluckypan** [AriaLyy/Aria#148]
10-24 11:04:22.874 23981-23981/engineer.echo.androidshare D/BaseCachePool: 任务添加成功
10-24 11:04:22.875 23981-23981/engineer.echo.androidshare W/BaseExecutePool: 任务添加成功
10-24 11:04:22.893 23981-23981/engineer.echo.androidshare D/GifActivity: onPre key=http://static.gaoshouyou.com/d/22/94/822260b849944492caadd2983f9bb624.apk
10-24 11:04:22.909 23981-23994/engineer.echo.androidshare D/OpenGLRenderer: DecorView @cc6b72 is drawn by HWUI
10-24 11:04:22.909 23981-23994/engineer.echo.androidshare D/OpenGLRenderer: DecorView @265f2dc is drawn by HWUI
10-24 11:04:22.928 23981-25663/engineer.echo.androidshare W/System.err: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
10-24 11:04:22.928 23981-25663/engineer.echo.androidshare W/System.err:     at android.os.Handler.<init>(Handler.java:209)
10-24 11:04:22.928 23981-25663/engineer.echo.androidshare W/System.err:     at android.os.Handler.<init>(Handler.java:137)
10-24 11:04:22.928 23981-25663/engineer.echo.androidshare W/System.err:     at com.arialyy.aria.core.download.DownloadTask$Builder.setOutHandler(DownloadTask.java:167)
10-24 11:04:22.928 23981-25663/engineer.echo.androidshare W/System.err:     at com.arialyy.aria.core.queue.TaskFactory.createDownloadTask(TaskFactory.java:108)
10-24 11:04:22.928 23981-25663/engineer.echo.androidshare W/System.err:     at com.arialyy.aria.core.queue.TaskFactory.createTask(TaskFactory.java:66)
10-24 11:04:22.928 23981-25663/engineer.echo.androidshare W/System.err:     at com.arialyy.aria.core.queue.DownloadTaskQueue.createTask(DownloadTaskQueue.java:125)
10-24 11:04:22.928 23981-25663/engineer.echo.androidshare W/System.err:     at com.arialyy.aria.core.queue.DownloadTaskQueue.createTask(DownloadTaskQueue.java:37)
10-24 11:04:22.928 23981-25663/engineer.echo.androidshare W/System.err:     at com.arialyy.aria.core.command.normal.AbsNormalCmd.createTask(AbsNormalCmd.java:165)
10-24 11:04:22.928 23981-25663/engineer.echo.androidshare W/System.err:     at com.arialyy.aria.core.command.normal.StartCmd$WaitTaskThread.handleTask(StartCmd.java:149)
10-24 11:04:22.928 23981-25663/engineer.echo.androidshare W/System.err:     at com.arialyy.aria.core.command.normal.StartCmd$WaitTaskThread.run(StartCmd.java:105)
10-24 11:04:22.928 23981-25663/engineer.echo.androidshare W/System.err:     at java.lang.Thread.run(Thread.java:818)
10-24 11:04:22.930 23981-25663/engineer.echo.androidshare E/AndroidRuntime: FATAL EXCEPTION: Thread-701
                                                                            Process: engineer.echo.androidshare, PID: 23981
                                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'long com.arialyy.aria.core.inf.AbsEntity.getCurrentProgress()' on a null object reference
                                                                                at com.arialyy.aria.core.download.BaseDListener.<init>(BaseDListener.java:52)
                                                                                at com.arialyy.aria.core.download.DownloadListener.<init>(DownloadListener.java:28)
                                                                                at com.arialyy.aria.core.download.DownloadTask.<init>(DownloadTask.java:44)
                                                                                at com.arialyy.aria.core.download.DownloadTask.<init>(DownloadTask.java:33)
                                                                                at com.arialyy.aria.core.download.DownloadTask$Builder.build(DownloadTask.java:176)
                                                                                at com.arialyy.aria.core.queue.TaskFactory.createDownloadTask(TaskFactory.java:109)
                                                                                at com.arialyy.aria.core.queue.TaskFactory.createTask(TaskFactory.java:66)
                                                                                at com.arialyy.aria.core.queue.DownloadTaskQueue.createTask(DownloadTaskQueue.java:125)
                                                                                at com.arialyy.aria.core.queue.DownloadTaskQueue.createTask(DownloadTaskQueue.java:37)
                                                                                at com.arialyy.aria.core.command.normal.AbsNormalCmd.createTask(AbsNormalCmd.java:165)
                                                                                at com.arialyy.aria.core.command.normal.StartCmd$WaitTaskThread.handleTask(StartCmd.java:149)
                                                                                at com.arialyy.aria.core.command.normal.StartCmd$WaitTaskThread.run(StartCmd.java:105)
                                                                                at java.lang.Thread.run(Thread.java:818)
10-24 11:04:22.952 23981-25663/engineer.echo.androidshare I/Process: Sending signal. PID: 23981 SIG: 9

**Comment by Pluckypan** [comment]
老铁看到请回复下，出现了空指针

**Comment by AriaLyy** [comment]
已经看到了，我先排查下是什么原因导致的，将会在下个版本处理这个问题

**Comment by AriaLyy** [comment]
你用3.3.6测试下看看还会不会出这个null
