### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by wlxfxy** [AriaLyy/Aria#151]
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
at android.os.Handler.<init>(Handler.java:200)
at android.os.Handler.<init>(Handler.java:128)
at com.arialyy.aria.core.download.DownloadTask$Builder.setOutHandler(DownloadTask.java:167)
at com.arialyy.aria.core.queue.TaskFactory.createDownloadTask(TaskFactory.java:108)
 at com.arialyy.aria.core.queue.TaskFactory.createTask(TaskFactory.java:66)
at com.arialyy.aria.core.queue.DownloadTaskQueue.createTask(DownloadTaskQueue.java:125)
at com.arialyy.aria.core.queue.DownloadTaskQueue.createTask(DownloadTaskQueue.java:37)
at com.arialyy.aria.core.command.normal.AbsNormalCmd.createTask(AbsNormalCmd.java:165)
at com.arialyy.aria.core.command.normal.StartCmd$WaitTaskThread.handleTask(StartCmd.java:149)
at com.arialyy.aria.core.command.normal.StartCmd$WaitTaskThread.run(StartCmd.java:105)
at java.lang.Thread.run(Thread.java:841)

**Comment by AriaLyy** [comment]
这个应该是警告的内容吧，我在这个警告里面已经做了try-cath处理了

**Comment by lxpeng** [comment]
我也出现此情况， @Download.onTaskRunning以及.start(); 并不是在activity类中会使用，虽然不会崩溃，但无法进入回调方法；
