### ISSUE TITLE
部分设备初始化失败,数据库

### ISSUE THREAD

**Issue by gaoxuefeng** [AriaLyy/Aria#173]
android.database.sqlite.SQLiteException:duplicate  column name: d (code 1): , while compiling: create table UploadEntity(d  varchar,e bigint,f varchar,g interger,h bigint,i bigint,k boolean,a  varchar,b varchar,c boolean,d boolean,e varchar,a varchar,FOREIGN KEY  (a) REFERENCES f(key));
--
6 android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
7 android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
8 android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
9 android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
10 android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
11 android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
12 android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1674)
13 android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
14 com.arialyy.aria.b.k.a(Unknown Source)
15 com.arialyy.aria.b.k.a(Unknown Source)
16 com.arialyy.aria.b.c.<init>(Unknown Source)
17 com.arialyy.aria.b.c.init(Unknown Source)
18 com.arialyy.aria.core.b.<init>(Unknown Source)
19 com.arialyy.aria.core.b.getInstance(Unknown Source)
20 com.arialyy.aria.core.a.get(Unknown Source)
21 com.arialyy.aria.core.a.download(Unknown Source)

**Comment by AriaLyy** [comment]
3.3.9已经修复了这个问题

**Comment by painld6** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{PlayerActivity}: android.database.sqlite.SQLiteException: vtable constructor failed: UploadEntity (code 1)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2722)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2783)
                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6259)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:803)
                                                  Caused by: android.database.sqlite.SQLiteException: vtable constructor failed: UploadEntity (code 1)
                                                     at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
                                                     at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
                                                     at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
                                                     at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
                                                     at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1679)
                                                     at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1608)
                                                     at com.arialyy.aria.orm.d.a(SqlHelper.java:539)
                                                     at com.arialyy.aria.orm.d.a(SqlHelper.java:65)
                                                     at com.arialyy.aria.orm.c.<init>(DbUtil.java:46)
                                                     at com.arialyy.aria.orm.c.a(DbUtil.java:53)
                                                     at com.arialyy.aria.core.b.<init>(AriaManager.java:82)
                                                     at com.arialyy.aria.core.b.a(AriaManager.java:91)
                                                     at com.arialyy.aria.core.a.c(Aria.java:91)
                                                     at com.arialyy.aria.core.a.a(Aria.java:72)
更新到3.3.9，初始化 Aria.download(this).register() 报出上面的错误
