### ISSUE TITLE
单任务文件下载

### ISSUE THREAD

**Issue by ADroidCoder** [AriaLyy/Aria#177]
我单任务文件下载，为什么下载完成了之后再次下载就会报数组越界，在load()这一块

**Comment by AriaLyy** [comment]
能否提供一下错误日志？

**Comment by ADroidCoder** [comment]
at com.arialyy.aria.orm.SqlUtil.str2Map(SqlUtil.java:116)
	at com.arialyy.aria.orm.SqlHelper.newInstanceEntity(SqlHelper.java:586)
	at com.arialyy.aria.orm.SqlHelper.findData(SqlHelper.java:208)
	at com.arialyy.aria.orm.DbUtil.findData(DbUtil.java:127)
	at com.arialyy.aria.orm.DbEntity.findFirst(DbEntity.java:104)
	at com.arialyy.aria.core.manager.DTEntityFactory.create(DTEntityFactory.java:50)
	at com.arialyy.aria.core.manager.DTEntityFactory.create(DTEntityFactory.java:67)
	at com.arialyy.aria.core.manager.DTEntityFactory.create(DTEntityFactory.java:29)
	at com.arialyy.aria.core.manager.TEManager.createTEntity(TEManager.java:71)
	at com.arialyy.aria.core.download.DownloadTarget.<init>(DownloadTarget.java:60)
	at com.arialyy.aria.core.download.DownloadReceiver.load(DownloadReceiver.java:92)
	at com.arialyy.aria.core.download.DownloadReceiver.load(DownloadReceiver.java:81)

**Comment by ADroidCoder** [comment]
我断点跟了下，是因为加了header，然后第二次重复下载的时候，调用了SqlUtil.str2Map 去转head里面的数据所以就 抛异常了

**Comment by AriaLyy** [comment]
能否发下错误信息，这个只是告诉我那个地方可能有问题，但是到底是啥问题麻烦贴出来下，如果方便的话能否贴下header的数据

**Comment by ADroidCoder** [comment]
Mozilla/5.0 (Linux; Android 4.4.4; Nexus 5 Build/KTU84P; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.132 Mobile MQQBrowser/6.2 TBS/043722 Safari/537.36



BAIDUID=DFC7EF42C60AD1ACF0BA94389AA67F13:FG=1; H_WISE_SIDS=121192_104493_114745_121434_119046_100098_120212_121140_118882_118858_118850_118820_118792_121254_121534_121214_117588_117242_117431_119974_120597_121043_121422_120943_121175_121272_117552_120482_121013_119962_119145_120851_120841_120034_121325_116407_121109_120654_110085_120708; PSINO=7; BDORZ=AE84CDB3A529C0F8A2B9DCDD1D18B695

**Comment by ADroidCoder** [comment]
那上面是两个 header数据，我隔开了

**Comment by AriaLyy** [comment]
你看我理解有没有错误：
第一个header:
BAIDUID=DFC7EF42C60AD1ACF0BA94389AA67F13:FG=1; 

第二个：
H_WISE_SIDS=121192_104493_114745_121434_119046_100098_120212_121140_118882_118858_118850_118820_118792_121254_121534_121214_117588_117242_117431_119974_120597_121043_121422_120943_121175_121272_117552_120482_121013_119962_119145_120851_120841_120034_121325_116407_121109_120654_110085_120708; PSINO=7; BDORZ=AE84CDB3A529C0F8A2B9DCDD1D18B695

对吧

**Comment by ADroidCoder** [comment]
第一个 header
Mozilla/5.0 (Linux; Android 4.4.4; Nexus 5 Build/KTU84P; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.132 Mobile MQQBrowser/6.2 TBS/043722 Safari/537.36

第二个
BAIDUID=DFC7EF42C60AD1ACF0BA94389AA67F13:FG=1; H_WISE_SIDS=121192_104493_114745_121434_119046_100098_120212_121140_118882_118858_118850_118820_118792_121254_121534_121214_117588_117242_117431_119974_120597_121043_121422_120943_121175_121272_117552_120482_121013_119962_119145_120851_120841_120034_121325_116407_121109_120654_110085_120708; PSINO=7; BDORZ=AE84CDB3A529C0F8A2B9DCDD1D18B695

**Comment by ADroidCoder** [comment]
第一个是UA第二个是cookie

**Comment by AriaLyy** [comment]
第一个和第二个的key分别是啥？

**Comment by ADroidCoder** [comment]
第一个 User-Agent 第二个 Cookie

**Comment by AriaLyy** [comment]
用3.3.9试试呢，这个时数据库字段不够长导致的问题

**Comment by ADroidCoder** [comment]
ok
