### ISSUE TITLE
android.database.sqlite.SQLiteException: vtable constructor failed: UploadEntity (code 1)

### ISSUE THREAD

**Issue by painld6** [AriaLyy/Aria#185]
3.3.7报出了这个问题#173 
后升级到3.3.9，在使用后，报出下面的问题。。。
Process: com.mimikoukou.mkapp, PID: 1501
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{PlayerActivity}: android.database.sqlite.SQLiteException: vtable constructor failed: UploadEntity (code 1)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2722)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2783)
                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6259)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:803)
                                                  Caused by: android.database.sqlite.SQLiteException: vtable constructor failed: UploadEntity (code 1)
                                                     at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
                                                     at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
                                                     at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
                                                     at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
                                                     at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1679)
                                                     at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1608)
                                                     at com.arialyy.aria.orm.d.a(SqlHelper.java:539)
                                                     at com.arialyy.aria.orm.d.a(SqlHelper.java:65)
                                                     at com.arialyy.aria.orm.c.<init>(DbUtil.java:46)
                                                     at com.arialyy.aria.orm.c.a(DbUtil.java:53)
                                                     at com.arialyy.aria.core.b.<init>(AriaManager.java:82)
                                                     at com.arialyy.aria.core.b.a(AriaManager.java:91)
                                                     at com.arialyy.aria.core.a.c(Aria.java:91)
                                                     at com.arialyy.aria.core.a.a(Aria.java:72)

**Comment by AriaLyy** [comment]
这是某些机型sqlite 版本太低了，不支持虚拟表导致的问题，我下个版本处理下这个问题

**Comment by painld6** [comment]
谢谢，处理完了希望即使通知下我

**Comment by AriaLyy** [comment]
ok

**Comment by AriaLyy** [comment]
```
compile 'com.arialyy.aria:aria-core:3.3.10'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.3.10'
```
3.3.10已经去掉了虚表的支持了
