### ISSUE TITLE
空指针

### ISSUE THREAD

**Issue by Zvirtuey** [AriaLyy/Aria#191]
http上传直接报空指针（还有问题就是上传能有进度条么）：

D/BaseCachePool: 任务添加成功
D/BaseExecutePool: 任务添加成功
E/AndroidRuntime: FATAL EXCEPTION: Thread-996
                                                                   Process: com.virtue.backup, PID: 11395
                                                                   java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.arialyy.aria.core.FtpUrlEntity.hostName' on a null object reference
                                                                       at com.arialyy.aria.core.common.AbsFtpInfoThread.createFtpClient(AbsFtpInfoThread.java:161)
                                                                       at com.arialyy.aria.core.common.AbsFtpInfoThread.run(AbsFtpInfoThread.java:72)
                                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by AriaLyy** [comment]
这是正则表达式匹配不到主机名导致的。能否把上传地址贴出来一下，我需要你的上传地址来验证正则表达式（不要求能连接）

**Comment by AriaLyy** [comment]
进度是@Upload.onTaskRunning这个就是进度了

**Comment by Zvirtuey** [comment]
服务器是局域网的抱歉；这种问题是不是代码可以规避掉。

**Comment by AriaLyy** [comment]
对，这是正则表达式匹配出的问题，我只需要地址用来进行正则表达式的验证，不需要进行上传。方便的话，麻烦提供下上传地址哈（不需要能上传，只需要字符串）

**Comment by Zvirtuey** [comment]
这个是上传路径url：http://192.168.2.223/SendFileExAction.php

**Comment by AriaLyy** [comment]
`3.3.11`已经修复了这个问题
