### ISSUE TITLE
FTP 上传

### ISSUE THREAD

**Issue by hncc** [AriaLyy/Aria#196]
FATAL EXCEPTION: Thread-2288
                                                                         Process: com.xxx.androiddowxx, PID: 16790
                                                                         java.lang.NullPointerException
                                                                             at java.util.regex.Matcher.reset(Matcher.java:177)
                                                                             at java.util.regex.Matcher.<init>(Matcher.java:90)
                                                                             at java.util.regex.Pattern.matcher(Pattern.java:297)
                                                                             at com.arialyy.aria.core.common.AbsFtpInfoThread.createFtpClient(AbsFtpInfoThread.java:161)
                                                                             at com.arialyy.aria.core.common.AbsFtpInfoThread.run(AbsFtpInfoThread.java:72)
                                                                             at java.lang.Thread.run(Thread.java:841)

**Comment by AriaLyy** [comment]
ftp地址需要添加端口号
