### ISSUE TITLE
上传的一点问题

### ISSUE THREAD

**Issue by supercwn** [AriaLyy/Aria#20]
上传能支持断点续传吗？

**Comment by AriaLyy** [comment]
上传断点续传服务器这块情况比较复杂，目前暂时没有一个很好的方案，该功能还在规划中，如果将来的版本支持了，我会在这里回复你的^_^

**Comment by Simonhy** [comment]
上传会出现问题
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.arialyy.aria.core.inf.ITask com.arialyy.aria.core.queue.pool.ExecutePool.getTask(java.lang.String)' on a null object reference
  at com.arialyy.aria.core.queue.AbsTaskQueue.getTask(AbsTaskQueue.java:69)
 at com.arialyy.aria.core.queue.UploadTaskQueue.getTask(UploadTaskQueue.java:64)
  at com.arialyy.aria.core.queue.UploadTaskQueue.getTask(UploadTaskQueue.java:31)
 at com.arialyy.aria.core.command.AddCmd.executeCmd(AddCmd.java:35)
  at com.arialyy.aria.core.AriaManager.exe(AriaManager.java:149)
    at com.arialyy.aria.core.inf.AbsTarget.start(AbsTarget.java:174)
      at com.arialyy.simple.upload.UploadActivity.upload(UploadActivity.java:90)
 at com.arialyy.simple.upload.UploadActivity$$ViewBinder$1.doClick(UploadActivity$$ViewBinder.java:19)

**Comment by Simonhy** [comment]
还有上传,希望后面能更新分片断点上传和socket断点上传

**Comment by AriaLyy** [comment]
@Simonhy 非常感谢您的反馈，compile 'com.arialyy.aria:Aria:3.1.3' 版本已修复这个问题，两个断点上传的功能后期版本会支持^_^

**Comment by mlick** [comment]
加油，master~
