### ISSUE TITLE
OutOfMemoryError 出现次数好像有点多 又是姿势不对么

### ISSUE THREAD

**Issue by junchenChow** [AriaLyy/Aria#209]
java.lang.OutOfMemoryError: Failed to allocate a 98841610 byte allocation with 4194304 free bytes and 36MB until OOM
                                                                       at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:83)
                                                                       at java.lang.StringBuilder.<init>(StringBuilder.java:67)
                                                                       at java.lang.String.replace(String.java:991)
                                                                       at com.arialyy.aria.util.CommonUtil.renameConfig(CommonUtil.java:843)
                                                                       at com.arialyy.aria.util.CommonUtil.renameDownloadConfig(CommonUtil.java:812)
                                                                       at com.arialyy.aria.core.download.DownloadTarget.setDownloadPath(DownloadTarget.java:126)
                                                                       at com.xxx.xxxx.page.download.service.AppDownloaderService.lambda$startDownload$0(AppDownloaderService.java:175)
                                                                       at com.xxx.xxxx.page.download.service.AppDownloaderService.access$lambda$0(AppDownloaderService.java)
                                                                       at com.xxx.xxxx.page.download.service.AppDownloaderService$$Lambda$4.apply(Unknown Source)
                                                                       at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:64)
                                                                       at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
                                                                       at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.onNext(FlowableFilter.java:52)
                                                                       at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
                                                                       at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:69)
                                                                       at io.reactivex.internal.operators.flowable.FlowableFilter$FilterSubscriber.tryOnNext(FlowableFilter.java:74)
                                                                       at io.reactivex.internal.operators.flowable.FlowableMap$MapConditionalSubscriber.tryOnNext(FlowableMap.java:129)
                                                                       at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnConditionalSubscriber.runAsync(FlowableObserveOn.java:637)
                                                                       at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by junchenChow** [comment]
> private void startDownload() {
        DownloadDao downloadDao = AppDatabase.get(DonguoApplication.getInstance()).downloadDao();
        downloadDao.queryCheckedDownloads()
                .subscribeOn(Schedulers.io())
                .filter(CollectionsUtil::notEmpty)
                .map(downloads -> {
                    for (int i = 0, len = downloads.size(); i < len; i++) {
                        Downloads item = downloads.get(i);
                        String fileSuffix = item.getType() == CourseDetailActivity.COURSE_TYPE_AUDIO ? ".mp3" : ".mp4";
                        DownloadEntity downloadEntity = downloadReceiver.getDownloadEntity(item.getMediaSrc());
                        if (downloadEntity == null) {
                            DownloadTarget downloadTarget = downloadReceiver.load(item.getMediaSrc()).setDownloadPath(FileUtil.getRootPath() + File.separator + "videos/" + item.getTitle() + fileSuffix);
                            downloadTarget.add();
                            positions.put(downloadTarget.getDownloadEntity().getKey(), i);
                        } else {
                            positions.put(downloadReceiver.getDownloadEntity(item.getMediaSrc()).getKey(), i);
                        }
                    }
                    downloadingList.addAll(downloads);
                    return downloads;
                })
                .map(this::continueQueDownload)
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(downloads -> EventBus.getDefault().post(new DownloadEvent(DownloadEvent.DownloadAction.DOWNLOAD_ITEMS, downloads)), Throwable::printStackTrace);
    }

**Comment by AriaLyy** [comment]
装饰3.3.16_dev的一个bug，现在3.0分支已经修复

**Comment by junchenChow** [comment]
还有下载的时候有时候停止都停止不了 调用移除文件了都不行。

**Comment by junchenChow** [comment]
还有个问题。。。https://static.donguo.me//video/ip/course/pfys_1.mp4 类似这种url 你那边转url的方法有问题 把双斜杆去掉之后 我这个链接直接not found了。

**Comment by AriaLyy** [comment]
。。。。 将两个反斜杠转换为单斜杠时因为以前有人用两个反斜杠，地址错误......

**Comment by AriaLyy** [comment]
你用3.3.16_dev2试下
