### ISSUE TITLE
不支持断点下载的链接 导致程序奔溃异常。我想问下怎么拦截这个异常，而不是异常导致程序崩掉

### ISSUE THREAD

**Issue by Sammiu** [AriaLyy/Aria#210]
异常信息

- 、03-16 17:51:49.547 9167-9272/com.onepiecenew W/DownloadUtil: 该下载链接不支持断点下载
03-16 17:51:50.883 1754-2022/? E/HwSystemManager: LeisureTrafficSetting:result is empty
03-16 17:51:50.946 1754-2022/? E/HwSystemManager: CommonMethodUtil:No package name to uid:-4
03-16 17:51:50.946 1754-2022/? E/HwSystemManager: CommonMethodUtil:No package name to uid:0
03-16 17:51:50.957 1754-2022/? E/HwSystemManager: CommonMethodUtil:No package name to uid:1021
03-16 17:51:50.964 1754-2022/? E/HwSystemManager: NotificationUtil:Month Warning Notification not create
03-16 17:51:51.291 496-496/? E/Thermal-daemon: [ap] temp_new :34  temp_old :35
03-16 17:51:51.292 1895-1910/? I/ThermalService: Receive temperature change, type: 0, temp: 34 from thermald
03-16 17:51:51.293 1895-2355/? I/LowBatteryManager: Only handle msg event!
03-16 17:51:51.293 496-496/? E/Thermal-daemon: Report temperature: [ap] temp :34  report_threshold:1
03-16 17:51:51.654 9167-9167/com.onepiecenew I/Choreographer: Skipped 126 frames!  The application may be doing too much work on its main thread.
03-16 17:51:52.157 993-1002/? I/OAM: [check_file_size:417]/data/log/wifi/wifi_log_1 log file beyond size=10240Byte, creat new file
03-16 17:51:52.157 993-1002/? I/OAM: [rename_old_file:122]rename_old_file
03-16 17:51:52.601 9167-9272/com.onepiecenew E/AndroidRuntime: FATAL EXCEPTION: Thread-7
                                                               Process: com.onepiecenew, PID: 9167
                                                               java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.concurrent.ExecutorService.execute(java.lang.Runnable)' on a null object reference
                                                                   at com.arialyy.aria.core.download.DownloadUtil.handleNoSupportBreakpointDownload(DownloadUtil.java:354)
                                                                   at com.arialyy.aria.core.download.DownloadUtil.handleBreakpoint(DownloadUtil.java:285)
                                                                   at com.arialyy.aria.core.download.DownloadUtil.handleConnect(DownloadUtil.java:232)
                                                                   at com.arialyy.aria.core.download.DownloadUtil.run(DownloadUtil.java:198)
                                                                   at java.lang.Thread.run(Thread.java:776)
03-16 17:51:52.616 512-808/? I/logserver: handle_logfile_events, Object Path:/data/system/dropbox/, mask=0x00000080

版本：  compile 'com.arialyy.aria:Aria:3.1.5'

**Comment by AriaLyy** [comment]
我后面处理下
