### ISSUE TITLE
android 8.0 register()报错

### ISSUE THREAD

**Issue by renzhe20092584** [AriaLyy/Aria#256]
## 版本号
~ 
3.4.1
## 什么问题
~
android 8.0 register()报错
## 如何复现此问题
~ 
app启动调用register()的时候报错
## 手机型号
~ 
华为 8.0.0
## 控制台日志
（github的issues支持图片直接粘贴复制）
~
java.io.IOException: No original dex files found for dex location /data/app/com.ixianlai.shanmahjong-X_1nTuV7WW2_YMXfcrqv1g==/split_lib_resources_apk.apk
06-12 14:17:57.336 14894-14894/com.ixianlai.shanmahjong W/System.err:     at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:86)
        at com.arialyy.aria.util.CommonUtil.getPkgClassName(CommonUtil.java:110)
        at com.arialyy.aria.util.CommonUtil.getClassName(CommonUtil.java:94)
        at com.arialyy.aria.core.common.ProxyHelper.init(ProxyHelper.java:50)
        at com.arialyy.aria.core.common.ProxyHelper.<init>(ProxyHelper.java:37)
        at com.arialyy.aria.core.common.ProxyHelper.getInstance(ProxyHelper.java:43)
        at com.arialyy.aria.core.download.DownloadReceiver.register(DownloadReceiver.java:233)
        at com.shared.xsdk.NativeInterface.init(NativeInterface.java:118)
        at org.cocos2dx.lua.XsdkNative.initXsdkNative(XsdkNative.java:19)
        at org.cocos2dx.lua.AppActivity.onCreate(AppActivity.java:139)
        at android.app.Activity.performCreate(Activity.java:7372)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)

**Comment by AriaLyy** [comment]
你apk的名字是`com.ixianlai.shanmahjong-X_1nTuV7WW2_YMXfcrqv1g==/split_lib_resources_apk.apk`这个吗？

**Comment by renzhe20092584** [comment]
是的，只在8.0的系统上有这个问题，能问下怎么解决吗？ 谢谢啦

**Comment by AriaLyy** [comment]
![image](https://user-images.githubusercontent.com/10437293/41276749-d026c08e-6e57-11e8-8810-8f369c8ac38d.png)
是这个斜杠导致的问题，你将包名的`/`去掉应该就可以了

**Comment by renzhe20092584** [comment]
包名就是 com.ixianlai.shanmahjong  
后面的 "-X_1nTuV7WW2_YMXfcrqv1g==/split_lib_resources_apk.apk" 自动生成的

**Comment by AriaLyy** [comment]
打印下`context.getPackageCodePath();`这个路径看看是什么？

**Comment by renzhe20092584** [comment]
打印这个 /data/app/com.ixianlai.shanmahjong-e1SZ6W2BSn6IMm8Q5ekAJQ==/base.apk
麻烦 谢谢啦
能加下 微信或 qq 吗？

**Comment by AriaLyy** [comment]
用这个版本 3.4.3_dev1 测试下看看，加了个文件验证

**Comment by renzhe20092584** [comment]
嗯嗯 好的 我先试试

**Comment by renzhe20092584** [comment]
大哥 我们刚试过也不行，能问下为啥 生成 "-e1SZ6W2BSn6IMm8Q5ekAJQ==/b"
谢谢啦

**Comment by renzhe20092584** [comment]
源码跑例子可以，库不行 
麻烦啦

**Comment by AriaLyy** [comment]
你把apk发给我下，直接把apk拖动isu上就行了
