### ISSUE TITLE
下载任务过多，会导致Cursor异常

### ISSUE THREAD

**Issue by wangadrian** [AriaLyy/Aria#274]
## 版本号
3.4.7

## 什么问题
下载任务过多，会导致Cursor异常

## 如何复现此问题
下载4000张图片，大概在1000张左右的时候会报错，应该是Cursor.close关闭异常

## 手机型号
模拟器

## 控制台日志（越完整越好）
07-18 10:32:43.468 2104-2104/adrian.delanfeiruo E/CursorWindow: Could not allocate CursorWindow '/data/data/adrian.delanfeiruo/databases/AndroidAria.db' of size 2097152 due to error -12.
07-18 10:32:44.471 2104-2104/adrian.delanfeiruo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: adrian.delanfeiruo, PID: 2104
                                                                  android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
                                                                      at android.database.CursorWindow.<init>(CursorWindow.java:108)
                                                                      at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
                                                                      at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
                                                                      at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
                                                                      at com.arialyy.aria.orm.DelegateFind.findData(DelegateFind.java:352)
                                                                      at com.arialyy.aria.orm.DelegateWrapper.findData(DelegateWrapper.java:125)
                                                                      at com.arialyy.aria.orm.DbEntity.findDatas(DbEntity.java:102)
                                                                      at com.arialyy.aria.core.command.normal.CancelAllCmd.removeAllDTask(CancelAllCmd.java:66)
                                                                      at com.arialyy.aria.core.command.normal.CancelAllCmd.executeCmd(CancelAllCmd.java:54)
                                                                      at com.arialyy.aria.core.AriaManager.exe(AriaManager.java:218)
                                                                      at com.arialyy.aria.core.download.DownloadReceiver.removeAllTask(DownloadReceiver.java:403)
                                                                      at adrian.delanfeiruo.WellcomeActivity.taskComplete(WellcomeActivity.java:127)
                                                                      at adrian.delanfeiruo.WellcomeActivity$$DownloadListenerProxy.onTaskComplete(WellcomeActivity$$DownloadListenerProxy.java:33)
                                                                      at adrian.delanfeiruo.WellcomeActivity$$DownloadListenerProxy.onTaskComplete(WellcomeActivity$$DownloadListenerProxy.java:16)
                                                                      at com.arialyy.aria.core.scheduler.AbsSchedulers.callback(AbsSchedulers.java:243)
                                                                      at com.arialyy.aria.core.scheduler.AbsSchedulers.callback(AbsSchedulers.java:205)
                                                                      at com.arialyy.aria.core.scheduler.AbsSchedulers.handleNormalEvent(AbsSchedulers.java:192)
                                                                      at com.arialyy.aria.core.scheduler.AbsSchedulers.handleMessage(AbsSchedulers.java:118)
                                                                      at com.arialyy.aria.core.scheduler.DownloadSchedulers.handleMessage(DownloadSchedulers.java:29)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by AriaLyy** [comment]
用3.4.9版本

**Comment by wangadrian** [comment]
android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed.

**Comment by wangadrian** [comment]
最新版本还是一直会出现
