### ISSUE TITLE
file name error

### ISSUE THREAD

**Issue by DeevD** [AriaLyy/Aria#276]
When i start download i got these error 
java.lang.IllegalArgumentException: Empty file name

**Comment by AriaLyy** [comment]
can you get me Console log ? i need log，thank :D

**Comment by theoneee** [comment]
`java.lang.IllegalArgumentException: Empty file name
        at android.content.res.AssetManager.openAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:347)
        at android.content.res.AssetManager.open(AssetManager.java:321)
        at com.arialyy.aria.util.SSLContextUtil.getSSLContextFromAssets(SSLContextUtil.java:67)
        at com.arialyy.aria.core.download.downloader.ConnectionHelp.handleConnection(ConnectionHelp.java:81)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:57)
        at java.lang.Thread.run(Thread.java:769)`

**Comment by AriaLyy** [comment]
```
    implementation 'com.arialyy.aria:aria-core:3.4.9'
    annotationProcessor 'com.arialyy.aria:aria-compiler:3.4.9'
```
This bug has been fixed
