### ISSUE TITLE
Empty file name

### ISSUE THREAD

**Issue by pinixiong** [AriaLyy/Aria#279]
## 版本号
3.4.8

## 什么问题
单任务的HTTPS下载，新建下载，就会崩溃，报Empty file name

## 如何复现此问题
链接：https://dl.genymotion.com/releases/genymotion-2.12.1/genymotion-2.12.1-vbox.exe
HTTPS的链接，新建下载任务，立马报错。

## 控制台日志（越完整越好）
07-23 15:26:55.002 27146-27146/ D/BaseCachePool: 任务【genymotion-2.12.1-vbox.exe】进入缓存队列成功
07-23 15:26:55.002 27146-27146/ D/BaseExecutePool: 任务【genymotion-2.12.1-vbox.exe】进入执行队列成功
                                                                            
                                                                            --------- beginning of system
07-23 15:26:55.029 27146-28308/ W/ActivityThread: ClassLoader.loadClass: The class loader returned by Thread.getContextClassLoader() may fail for processes that host multiple applications. You should explicitly specify a context class loader. For example: Thread.setContextClassLoader(getClass().getClassLoader());
07-23 15:26:55.029 27146-27146/ D/AriaDownTaskManager: [main(1): AriaDownTaskManager.java:206] - onPre ==> genymotion-2.12.1-vbox.exe
07-23 15:26:55.031 27146-28308/ W/JNIHelp: Discarding pending exception (java.lang.NullPointerException) to throw java/lang/IllegalArgumentException
                                                                    
                                                                    --------- beginning of crash
07-23 15:26:55.032 27146-28308/ E/AndroidRuntime: FATAL EXCEPTION: Thread-229
                                                                           Process: com.evideo.remotedownload, PID: 27146
                                                                           java.lang.IllegalArgumentException: Empty file name
                                                                               at android.content.res.AssetManager.openAsset(Native Method)
                                                                               at android.content.res.AssetManager.open(AssetManager.java:313)
                                                                               at android.content.res.AssetManager.open(AssetManager.java:287)
                                                                               at com.arialyy.aria.util.SSLContextUtil.getSSLContextFromAssets(SSLContextUtil.java:67)
                                                                               at com.arialyy.aria.core.download.downloader.ConnectionHelp.handleConnection(ConnectionHelp.java:81)
                                                                               at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:57)
                                                                               at java.lang.Thread.run(Thread.java:818)

**Comment by AriaLyy** [comment]
3.4.9已经修复了这个问题了

**Comment by pinixiong** [comment]
3.4.9是还没更新是吧，什么时候会更新?这边看到的最新的版本是3.4.8
