### ISSUE TITLE
Demo运行点击下载就会崩溃

### ISSUE THREAD

**Issue by xuchenchen** [AriaLyy/Aria#29]
只要是点击下载按钮就立即闪退
手机信息
![Uploading image.png…]()

错误日志：
 Process: com.arialyy.simple, PID: 12482
                                                                    android.database.sqlite.SQLiteException: no such column: serialVersionUID (code 1): , while compiling: SELECT rowid, * FROM DownloadEntity where downloadPath='/storage/emulated/0/Download/奇迹暖暖' AND downloadUrl='http://static.gaoshouyou.com/d/eb/f2/dfeba30541f209ab8a50d847fc1661ce.apk' AND isDownloadComplete='false' AND isRedirect='false' AND redirectUrl='' AND $change='null' AND serialVersionUID='4261567989868876910'
                                                                    #################################################################
                                                                    Error Code : 1 (SQLITE_ERROR)
                                                                    Caused By : SQL(query) error or missing database.
                                                                    	(no such column: serialVersionUID (code 1): , while compiling: SELECT rowid, * FROM DownloadEntity where downloadPath='/storage/emulated/0/Download/奇迹暖暖' AND downloadUrl='http://static.gaoshouyou.com/d/eb/f2/dfeba30541f209ab8a50d847fc1661ce.apk' AND isDownloadComplete='false' AND isRedirect='false' AND redirectUrl='' AND $change='null' AND serialVersionUID='4261567989868876910')
                                                                    #################################################################
                                                                        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1009)
                                                                        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:574)
                                                                        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
                                                                        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1518)
                                                                        at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1457)
                                                                        at com.arialyy.aria.orm.SqlHelper.findData(SqlHelper.java:216)
                                                                        at com.arialyy.aria.orm.DbUtil.findData(DbUtil.java:106)
                                                                        at com.arialyy.aria.orm.DbEntity.findData(DbEntity.java:153)
                                                                        at com.arialyy.aria.orm.DbEntity.updateRowID(DbEntity.java:171)
                                                                        at com.arialyy.aria.orm.DbEntity.insert(DbEntity.java:147)
                                                                        at com.arialyy.aria.orm.DbEntity.save(DbEntity.java:130)
                                                                        at com.arialyy.aria.core.download.DownloadTask$Builder.build(DownloadTask.java:174)
                                                                        at com.arialyy.aria.core.queue.TaskFactory.createDownloadTask(TaskFactory.java:91)
                                                                        at com.arialyy.aria.core.queue.TaskFactory.createTask(TaskFactory.java:63)
                                                                        at com.arialyy.aria.core.queue.DownloadTaskQueue.createTask(DownloadTaskQueue.java:125)
                                                                        at com.arialyy.aria.core.queue.DownloadTaskQueue.createTask(DownloadTaskQueue.java:36)
                                                                        at com.arialyy.aria.core.command.AddCmd.executeCmd(AddCmd.java:37)
                                                                        at com.arialyy.aria.core.AriaManager.exe(AriaManager.java:138)
                                                                        at com.arialyy.aria.core.inf.AbsTarget.start(AbsTarget.java:198)
                                                                        at com.arialyy.simple.download.multi_download.FileListAdapter$1.onClick(FileListAdapter.java:73)
                                                                        at android.view.View.performClick(View.java:5721)
                                                                        at android.widget.TextView.performClick(TextView.java:10949)
                                                                        at android.view.View$PerformClick.run(View.java:22624)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:7410)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by AriaLyy** [comment]
$change='null' AND serialVersionUID='4261567989868876910'  是这两个字段导致的问题，我的DownloadEntity中是没有这两个字段的，你是不是打开了InstantRun 了，如果是的话，把它关闭了，然后清空数据，再运行看看

**Comment by xuchenchen** [comment]
非常感谢您的回答，是这个原因
