### ISSUE TITLE
上传崩溃

### ISSUE THREAD

**Issue by mjnhmd** [AriaLyy/Aria#290]
## 什么问题 上传崩溃

Aria.upload(this).load(“/storage/emulated/0/download/1529648081572.jpg”)
                        .setContentType("multipart/form-data")
                        .setUploadUrl("http://10.3.240.18:9000/App/file/upload/teacher")
                        .start();

错误日志：FATAL EXCEPTION: main
                                                              Process: com.mjn.test, PID: 18162
                                                              java.lang.NullPointerException: Attempt to read from field 'boolean com.arialyy.aria.core.FtpUrlEntity.isFtps' on a null object reference
                                                                  at com.arialyy.aria.core.upload.BaseNormalTarget.checkEntity(BaseNormalTarget.java:83)
                                                                  at com.arialyy.aria.core.inf.AbsTarget.start(AbsTarget.java:217)
                                                                  at com.mjn.test.ui.activity.UploadActivity$3.onClick(UploadActivity.java:73)
                                                                  at android.view.View.performClick(View.java:6304)
                                                                  at android.view.View$PerformClick.run(View.java:24803)
                                                                  at android.os.Handler.handleCallback(Handler.java:790)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                  at android.os.Looper.loop(Looper.java:164)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6648)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:818)

**Comment by AriaLyy** [comment]
感谢反馈，`3.4.13`已经修复了这个问题

**Comment by mjnhmd** [comment]
感谢

**Comment by mjnhmd** [comment]
ok
