### ISSUE TITLE
Aria.download(this).resumeAllTask(); 恢复所有任务报错

### ISSUE THREAD

**Issue by lql7993259lql** [AriaLyy/Aria#302]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference
        at com.arialyy.aria.core.download.downloader.Downloader.onPostPre(Downloader.java:90)
        at com.arialyy.aria.core.common.AbsFileer.startFlow(AbsFileer.java:162)
        at com.arialyy.aria.core.common.AbsFileer.run(AbsFileer.java:176)
        at java.lang.Thread.run(Thread.java:764)
08-28 18:25:43.121 32479-2293/com.weile.graph E/CustomActivityOnCrash: App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference
        at com.arialyy.aria.core.download.downloader.Downloader.onPostPre(Downloader.java:90)
        at com.arialyy.aria.core.common.AbsFileer.startFlow(AbsFileer.java:162)
        at com.arialyy.aria.core.common.AbsFileer.run(AbsFileer.java:176)
        at java.lang.Thread.run(Thread.java:764)
08-28 18:25:43.122 32479-2293/com.weile.graph E/CustomActivityOnCrash: App already crashed recently, not starting custom error activity because we could enter a restart loop. Are you sure that your app does not crash directly on init?
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference
        at com.arialyy.aria.core.download.downloader.Downloader.onPostPre(Downloader.java:90)
        at com.arialyy.aria.core.common.AbsFileer.startFlow(AbsFileer.java:162)
        at com.arialyy.aria.core.common.AbsFileer.run(AbsFileer.java:176)
        at java.lang.Thread.run(Thread.java:764)

**Comment by AriaLyy** [comment]
感谢反馈。`3.5`版本已经修复了这个问题
