### ISSUE TITLE
为什么不支持android 4.4.2,android 4.3版本

### ISSUE THREAD

**Issue by ILoveChina1994** [AriaLyy/Aria#319]
##

**Comment by ILoveChina1994** [comment]
控制台日志：
10-24 16:44:13.092 28657-28657/com.zjdx.admin.wyplaningapp_ipad E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: com.zjdx.admin.wyplaningapp_ipad, PID: 28657
                                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zjdx.admin.wyplaningapp_ipad/com.zjdx.admin.wyplaningapp_ipad.main_menu.PlanDesign.PlanDesignResultActivity}: java.lang.NullPointerException
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2328)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2386)
                                                                                      at android.app.ActivityThread.access$900(ActivityThread.java:169)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1277)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:136)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5476)
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                                                                                      at dalvik.system.NativeStart.main(Native Method)
                                                                                   Caused by: java.lang.NullPointerException
                                                                                      at com.arialyy.aria.util.CommonUtil.getClassName(CommonUtil.java:89)
                                                                                      at com.arialyy.aria.core.common.ProxyHelper.init(ProxyHelper.java:50)
                                                                                      at com.arialyy.aria.core.common.ProxyHelper.<init>(ProxyHelper.java:37)
                                                                                      at com.arialyy.aria.core.common.ProxyHelper.getInstance(ProxyHelper.java:43)
                                                                                      at com.arialyy.aria.core.download.DownloadReceiver.register(DownloadReceiver.java:219)
                                                                                      at com.zjdx.admin.wyplaningapp_ipad.main_menu.PlanDesign.PlanDesignResultActivity.onCreate(PlanDesignResultActivity.java:159)
                                                                                      at android.app.Activity.performCreate(Activity.java:5473)
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2386) 
                                                                                      at android.app.ActivityThread.access$900(ActivityThread.java:169) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1277) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:136) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5476) 
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                      at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 
                                                                                      at dalvik.system.NativeStart.main(Native Method)

**Comment by ILoveChina1994** [comment]
在真机 android 4.4.2 和 4.3上面程序崩溃，错误在上一个

**Comment by AriaLyy** [comment]
Aria 使用的是哪个版本的？4.4.6以下的版本会出现多dex导致注解失败的问题

**Comment by ILoveChina1994** [comment]
compile 'com.arialyy.aria:aria-core:3.4.1' 这个版本，那我应该使用什么版本，里面的代码会不会有影响

**Comment by AriaLyy** [comment]
使用最新版本

**Comment by ILoveChina1994** [comment]
好的，谢谢

**Comment by ILoveChina1994** [comment]
compile 'com.arialyy.aria:aria-core:3.5.1'
    annotationProcessor 'com.arialyy.aria:aria-compiler:3.5.1'
    compile('com.arialyy.aria:aria-core:<last-version>') {
        exclude group: 'com.android.support'
    }
也报上面的错误

**Comment by AriaLyy** [comment]
403 是服务器端返回的错误，我使用你提供的url地址是可以下载的呢

**Comment by ILoveChina1994** [comment]
已好，感谢大神，解囊相助！
