### ISSUE TITLE
下载档案发生SqlLite错误

### ISSUE THREAD

**Issue by sofasoso** [AriaLyy/Aria#342]
## 版本号
3.5.2

## 什么问题
下载档案有时会发生这个问题 任务直接崩溃

## 如何复现此问题
不明 因为不是常态发生

## 手机型号
ASUS P028

## 控制台日志（越完整越好）
Fatal Exception: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
       at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:743)
       at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
       at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
       at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1607)
       at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1553)
       at com.arialyy.aria.orm.DelegateUpdate.modifyData(DelegateUpdate.java:132)
       at com.arialyy.aria.orm.DelegateWrapper.modifyData(DelegateWrapper.java:104)
       at com.arialyy.aria.orm.DbEntity.update(DbEntity.java:154)
       at com.arialyy.aria.core.common.AbsThreadTask.writeConfig(AbsThreadTask.java:507)
       at com.arialyy.aria.core.common.AbsThreadTask$1.run(AbsThreadTask.java:80)
       at java.lang.Thread.run(Thread.java:761)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

**Comment by AriaLyy** [comment]
感谢反馈

**Comment by AriaLyy** [comment]
使用`3.5.3`版本，应该是不支持断点的任务没有保存任务记录导致的

**Comment by sofasoso** [comment]
感谢大佬
