### ISSUE TITLE
任务组子任务量很大时异常

### ISSUE THREAD

**Issue by Piscen** [AriaLyy/Aria#345]
## 版本号

3.5.2
## 什么问题

1.用任务组下载视频切片文件时，切片文件量很多有一千个左右，但是单个文件很小，大概就一两兆。组任务回调导页面很卡，而且没法正常暂停或者恢复，有时候暂停以后进度还在变。
2.控制台一直在报SQLIteDatabase错误

## 如何复现此问题

任务组添加大量小文件子任务，我在下载的demo里试过也会有这种问题

## 手机型号

Vivo Y67A android 6.0 API 23
## 控制台日志（越完整越好）
com.arialyy.simple E/SQLiteDatabase: Error inserting stopTime=0 fileName=resourceDownLoad%3FresourceId%3D1996%26clientId%3DA000011106034058176 isComplete=false isGroupChild=true downloadPath=%2Fstorage%2Femulated%2F0%2FDownload%2Fgroup_test_1%2FresourceDownLoad%3FresourceId%3D1996%26clientId%3DA000011106034058176 url=http%3A%2F%2Fd.quanscreen.com%2Fk%2Fdown%2FresourceDownLoad%3FresourceId%3D1996%26clientId%3DA000011106034058176 fileSize=1 groupName=88f3899a887cb71aceff9e9d24174696 state=3 currentProgress=0 isRedirect=false completeTime=0
                                                                    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: DownloadEntity.downloadPath (code 1555)
                                                                        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                                                        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:821)
                                                                        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
                                                                        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
                                                                        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1501)
                                                                        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1371)
                                                                        at com.arialyy.aria.orm.DelegateUpdate.insertData(DelegateUpdate.java:173)
                                                                        at com.arialyy.aria.orm.DelegateWrapper.insertData(DelegateWrapper.java:146)
                                                                        at com.arialyy.aria.orm.DbEntity.insert(DbEntity.java:170)
                                                                        at com.arialyy.aria.orm.DbEntity.save(DbEntity.java:153)
                                                                        at com.arialyy.aria.core.download.BaseGroupTarget.reChangeDirPath(BaseGroupTarget.java:135)
                                                                        at com.arialyy.aria.core.download.DownloadGroupTarget.checkEntity(DownloadGroupTarget.java:185)
                                                                        at com.arialyy.aria.core.inf.AbsTarget.start(AbsTarget.java:217)
                                                                        at com.arialyy.simple.download.group.DownloadGroupActivity.onClick(DownloadGroupActivity.java:94)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
                                                                        at android.view.View.performClick(View.java:5272)
                                                                        at android.view.View$PerformClick.run(View.java:21528)
                                                                        at android.os.Handler.handleCallback(Handler.java:815)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                        at android.os.Looper.loop(Looper.java:207)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5856)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1026)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:887)

**Comment by Piscen** [comment]
目前来看像是跟子任务大并发有关系，现在最新的版本支持设置任务组子任务的线程数么，我这样设置好像不起效。
<threadNum value="1" />

        
        <maxTaskNum value="1" />

**Comment by AriaLyy** [comment]
可能是子任务太多导致的，子任务没有做排队处理

**Comment by AriaLyy** [comment]
3.6 版本新增了组合任务的队列支持，详情见：https://aria.laoyuyu.me/aria_doc/start/config.html

**Comment by Piscen** [comment]
@AriaLyy 感谢大佬，现在在用别的方法下载，但还是有点小问题，我再用你这个试试
