### ISSUE TITLE
SQLiteReadOnlyDatabaseException

### ISSUE THREAD

**Issue by fairytale110** [AriaLyy/Aria#359]
## 版本号
3.5.4

## 什么问题
android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)

## 如何复现此问题
卸载已安装App，重新安装 Apk
```
//在Application初始化
 Aria.init(this)
```
然后在Presenter调用(非Activity、Fragment、Service、Application)
```
  Aria.download(this)
                                .load(file.getString(ConstantString.KEY_FILE_URL))
                                .setFilePath(FileUtils.getDownloadPath() + file.getString(ConstantString.KEY_FILE_NAME))
                                .start();
                       
```
下载文件地址：“http://dlied5.myapp.com/myapp/1106467070/pubgmhd/2017_com.tencent.tmgp.pubgmhd_h8044_0.13.5_5adcba.apk”

下载文件名称：“刺激战场.apk”
保存路径：“ /storage/emulated/0/Android/data/net.hondee.iconstruction.alpha/cache/刺激战场.apk”

## 手机型号
OD103

## 控制台日志（越完整越好）

```
 E/SQLiteLog: (1032) statement aborts at 31: [INSERT INTO DownloadEntity(isGroupChild,downloadPath,url,state,convertFileSize,isRedirect,stopTime,fileName,isComplete,fileSize,percent,currentProgress,completeTime) VALUES (?,?,?,?,?,
20251-20251/net.hondee.iconstruction.alpha E/SQLiteDatabase: Error inserting isGroupChild=false downloadPath=%2Fstorage%2Femulated%2F0%2FAndroid%2Fdata%2Fnet.hondee.iconstruction.alpha%2Fcache%2F%E5%88%BA%E6%BF%80%E6%88%98%E5%9C%BA.apk url=http%3A%2F%2Fdlied5.myapp.com%2Fmyapp%2F1106467070%2Fpubgmhd%2F2017_com.tencent.tmgp.pubgmhd_h8044_0.13.5_5adcba.apk state=4 convertFileSize=1.80gb isRedirect=false stopTime=0 fileName=%E5%88%BA%E6%BF%80%E6%88%98%E5%9C%BA.apk isComplete=false fileSize=1931236474 percent=1 currentProgress=26085568 completeTime=0
    android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1474)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1343)
        at com.arialyy.aria.orm.DelegateUpdate.insertData(DelegateUpdate.java:173)
        at com.arialyy.aria.orm.DelegateWrapper.insertData(DelegateWrapper.java:146)
        at com.arialyy.aria.orm.DbEntity.insert(DbEntity.java:191)
        at com.arialyy.aria.orm.DbEntity.save(DbEntity.java:166)
        at com.arialyy.aria.core.download.BaseNormalTarget.checkEntity(BaseNormalTarget.java:124)
        at com.arialyy.aria.core.inf.AbsTarget.start(AbsTarget.java:218)
        at net.hondee.iconstruction.mvp.presenter.app.CommonBrowserPresenter.handleJS(CommonBrowserPresenter.java:245)
        at net.hondee.iconstruction.mvp.presenter.app.CommonBrowserPresenter.onJsAction(CommonBrowserPresenter.java:112)
        at net.hondee.iconstruction.module.common.CommonBrowserFragment.hander(CommonBrowserFragment.java:343)
        at net.hondee.iconstruction.module.app.IConstructionActivity.onHandleMessage(IConstructionActivity.java:295)
        at net.hondee.iconstruction.base.MyHandler.handleMessage(MyHandler.java:42)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:6364)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
20251-20251/net.hondee.iconstruction.alpha E/SQLiteDatabase: Error inserting isChunked=false requestType=17 key=%2Fstorage%2Femulated%2F0%2FAndroid%2Fdata%2Fnet.hondee.iconstruction.alpha%2Fcache%2F%E5%88%BA%E6%BF%80%E6%88%98%E5%9C%BA.apk url=http%3A%2F%2Fdlied5.myapp.com%2Fmyapp%2F1106467070%2Fpubgmhd%2F2017_com.tencent.tmgp.pubgmhd_h8044_0.13.5_5adcba.apk charSet=utf-8 state=4 code=206 isSupportBP=true isGroupTask=false useServerFileName=false requestEnum=GET
    android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1474)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1343)
        at com.arialyy.aria.orm.DelegateUpdate.insertData(DelegateUpdate.java:173)
        at com.arialyy.aria.orm.DelegateWrapper.insertData(DelegateWrapper.java:146)
        at com.arialyy.aria.orm.DbEntity.insert(DbEntity.java:191)
        at com.arialyy.aria.orm.DbEntity.save(DbEntity.java:166)
        at com.arialyy.aria.core.download.BaseNormalTarget.checkEntity(BaseNormalTarget.java:125)
        at com.arialyy.aria.core.inf.AbsTarget.start(AbsTarget.java:218)
        at net.hondee.iconstruction.mvp.presenter.app.CommonBrowserPresenter.handleJS(CommonBrowserPresenter.java:245)
        at net.hondee.iconstruction.mvp.presenter.app.CommonBrowserPresenter.onJsAction(CommonBrowserPresenter.java:112)
        at net.hondee.iconstruction.module.common.CommonBrowserFragment.hander(CommonBrowserFragment.java:343)
        at net.hondee.iconstruction.module.app.IConstructionActivity.onHandleMessage(IConstructionActivity.java:295)
        at net.hondee.iconstruction.base.MyHandler.handleMessage(MyHandler.java:42)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:6364)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

W/StartCmd: 任务【刺激战场.apk】已经在运行
D/StateConstance: fail_num=0; start_thread_num=3; complete_num=0 （此行日志会一直循环打印，好像在下载，，）
```

**Comment by fairytale110** [comment]
临时办法是download方法传四大组件的Context，蛋疼。

**Comment by AriaLyy** [comment]
这个是外键依赖导致的问题，升级到`3.6`版本，这个版本移除了一些没必要的依赖
