### ISSUE TITLE
组下载问题

### ISSUE THREAD

**Issue by lyxc** [AriaLyy/Aria#369]
## Aria版本
com.arialyy.aria:aria-core:3.5.4

## 什么问题
组中有三个文件，在第一次组下载时，控制台提示android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed，但是三个文件可以正常下载。不在文件管理器中删除对应的下载文件，再次执行下载代码时，就只下载其中两个文件。另，每次下载之前，都Aria.download(this).removeAllTask(true);对下载任务进行了删除

## 如何复现此问题
Aria.download(this).removeAllTask(true);
Aria.download(this).taskExists(mUrls));

        Aria.download(this)
                .loadGroup(mUrls)
                .setDirPath(AppConfig.filePath +  "sign"+ File.separator)
                .setSubFileName(nameUrls)
                .setGroupAlias("阅办单下载")
                .setExtendField(extentJson.toString())
                .start();

## 控制台日志
03-11 11:14:56.006 22442-22442/com.sdjsl.swoa E/SQLiteDatabase: Error inserting urls=http%3A%2F%2F192.168.1.66%3A8087%2FLomo-office-SW-BA%2FFV%2FGWManage%2FdownYbdFile%2F9f23912023674afd83bc592eafeb6897.pdf%24%24http%3A%2F%2F192.168.1.66%3A8087%2FLomo-office-SW-BA%2F%2FFV%2FGWManage%2Fldyjpic%2F2ecde897caba4702bab9d02355025d51.jpg%24%24http%3A%2F%2F192.168.1.66%3A8087%2FLomo-office-SW-BA%2F%2FFV%2FGWManage%2Fnbyjpic%2F2ecde897caba4702bab9d02355025d51.jpg%24%24 alias=%E9%98%85%E5%8A%9E%E5%8D%95%E4%B8%8B%E8%BD%BD str=%7B%22issign%22%3A%220%22%2C%22taskid%22%3A%229f23912023674afd83bc592eafeb6897%22%2C%22forminfo%22%3A%22%7B%252B%22f_copies%252B%22%3A%252B%22%252B%22%2C%252B%22f_draftdate%252B%22%3A%252B%22%252B%22%2C%252B%22f_draftdept%252B%22%3A%252B%22%252B%22%2C%252B%22f_draftperson%252B%22%3A%252B%22%E8%B0%AD%E6%B5%B7%E6%B3%A2%252B%22%2C%252B%22f_emergency%252B%22%3A%252B%22%E6%99%AE%E9%80%9A%252B%22%2C%252B%22f_fileno%252B%22%3A%252B%22%252B%22%2C%252B%22f_fwdate%252B%22%3A%252B%222019-03-06+16%3A34%3A44%252B%22%2C%252B%22f_grab_per%252B%22%3A%252B%22%E8%B0%AD%E6%B5%B7%E6%B3%A2%252B%22%2C%252B%22f_guid%252B%22%3A%252B%229f23912023674afd83bc592eafeb6897%252B%22%2C%252B%22f_isgrab%252B%22%3A%252B%221%252B%22%2C%252B%22f_organization%252B%22%3A%252B%22%E7%94%B5%E5%AD%90%E6%94%BF%E5%8A%A1%E5%BC%80%E5%8F%91%E7%BB%84%252B%22%2C%252B%22f_orgcode%252B%22%3A%252B%22%252B%22%2C%252B%22f_secretdegree%252B%22%3A%252B%22%E6%97%A0%E5%AF%86%E7%BA%A7%252B%22%2C%252B%22f_secrettemr%252B%22%3A%252B%22%252B%22%2C%252B%22f_status%252B%22%3A%252B%220%252B%22%2C%252B%22f_title%252B%22%3A%252B%222019-03-06%E6%B5%8B%E8%AF%95AAAAAAAAAAAA%252B%22%2C%252B%22f_type%252B%22%3A%252B%22%252B%22%2C%252B%22f_way%252B%22%3A%252B%222%252B%22%2C%252B%22f_wjlb%252B%22%3A%252B%22%252B%22%2C%252B%22f_year%252B%22%3A%252B%222019%252B%22%7D%22%2C%22isgrab%22%3Afalse%2C%22sendid%22%3A%22b1ecdc70962c4515a537b106f264d5a9%22%2C%22fileid%22%3A%229f23912023674afd83bc592eafeb6897%22%7D stopTime=0 isComplete=false fileSize=1 groupName=9842c8f103b99a6bdbd71888571946a state=7 percent=0 currentProgress=0 dirPath=%2Fstorage%2Femulated%2F0%2Fswoa%2Fsign%2F completeTime=0
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: DownloadGroupEntity.groupName (code 1555)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:780)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
        at com.arialyy.aria.orm.DelegateUpdate.insertData(DelegateUpdate.java:173)
        at com.arialyy.aria.orm.DelegateWrapper.insertData(DelegateWrapper.java:146)
        at com.arialyy.aria.orm.DbEntity.insert(DbEntity.java:191)
        at com.arialyy.aria.orm.DbEntity.save(DbEntity.java:166)
        at com.arialyy.aria.core.download.DownloadGroupTarget.checkEntity(DownloadGroupTarget.java:195)
        at com.arialyy.aria.core.inf.AbsTarget.start(AbsTarget.java:218)
        at com.sdjsl.swoa.module.EbenWebviewActivity.DownGroupFile(EbenWebviewActivity.java:637)
        at com.sdjsl.swoa.module.EbenWebviewActivity.access$400(EbenWebviewActivity.java:85)
        at com.sdjsl.swoa.module.EbenWebviewActivity$4.handleMessage(EbenWebviewActivity.java:605)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at com.wanjian.cockroach.Cockroach$1.run(Cockroach.java:47)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5484)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by AriaLyy** [comment]
升级到`3.6.2_debug_6`，配置文件有更新.
