### ISSUE TITLE
组下载崩溃

### ISSUE THREAD

**Issue by 888ewe** [AriaLyy/Aria#372]
## Aria版本
3.6.2_debug_6和3.6.1版本

## 什么问题
组下载崩溃

## 如何复现此问题
点击下载就能复现

## 控制台日志
FATAL EXCEPTION: Thread-154
    Process: com.tlkj.tour, PID: 1805
    android.database.sqlite.SQLiteException: foreign key mismatch (code 1): , while compiling: UPDATE DownloadGroupEntity SET fileSize=?,dirPath=?,currentProgress=?,isComplete=?,percent=?,urls=?,groupHash=?,state=?,convertFileSize=?,completeTime=?,stopTime=? WHERE rowid=?
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
        at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1572)
        at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1520)
        at com.arialyy.aria.orm.DelegateUpdate.updateData(DelegateUpdate.java:108)
        at com.arialyy.aria.orm.DelegateWrapper.updateData(DelegateWrapper.java:103)
        at com.arialyy.aria.orm.DbEntity.update(DbEntity.java:205)
        at com.arialyy.aria.core.download.DownloadGroupListener.saveData(DownloadGroupListener.java:147)
        at com.arialyy.aria.core.download.DownloadGroupListener.onPostPre(DownloadGroupListener.java:123)
        at com.arialyy.aria.core.download.group.AbsGroupUtil.startRunningFlow(AbsGroupUtil.java:254)
        at com.arialyy.aria.core.download.group.AbsGroupUtil.run(AbsGroupUtil.java:222)
        at java.lang.Thread.run(Thread.java:841)

**Comment by AriaLyy** [comment]
是否是从老版本升级上来的？

**Comment by 888ewe** [comment]
是的，但我把老版本的build删了，还是会报错

**Comment by AriaLyy** [comment]
我用我的demo测试是正常的。你是如何调用的？能否提供下调用代码和AndroidAria.db这个数据库。
