### ISSUE TITLE
混淆后运行错误SQLiteLog: (1) no such column: entity

### ISSUE THREAD

**Issue by hlwhsunshine** [AriaLyy/Aria#386]
## Aria版本
3.5.2

## 什么问题
android混淆后报错，混淆规则使用的文档示例
-dontwarn com.arialyy.aria.**
-keep class com.arialyy.aria.**{*;}
-keep class **$$DownloadListenerProxy{ *; }
-keep class **$$UploadListenerProxy{ *; }
-keep class **$$DownloadGroupListenerProxy{ *; }
-keepclasseswithmembernames class * {
    @Download.* <methods>;
    @Upload.* <methods>;
    @DownloadGroup.* <methods>;
}

## 控制台日志
 E/SQLiteLog: (1) table DownloadTaskEntity has no column named entity
04-24 15:08:19.119 6121-6121/? E/SQLiteDatabase: Error inserting isGroupTask=false refreshInfo=true useServerFileName=false isChunked=false charSet=utf-8 entity=DownloadEntity%7BdownloadPath%3D%27%2Fdata%2Fdata%2Fnet.com.shuame.rootgeniusauuk%2Ffiles%2Frfile%2Fas.zip%27%2C+groupName%3D%27null%27%2C+md5Code%3D%27null%27%2C+disposition%3D%27null%27%2C+serverFileName%3D%27null%27%7D state=3 requestType=17 code=0 url=http%3A%2F%2F123.183.211.187%3A8564%2Fresource%2Frfile.zip removeFile=false isSupportBP=true requestEnum=GET isNewTask=false key=%2Fdata%2Fdata%2Fnet.com.shuame.rootgeniusauuk%2Ffiles%2Frfile%2Fas.zip
                                                 android.database.sqlite.SQLiteException: table DownloadTaskEntity has no column named entity (code 1): , while compiling: INSERT INTO DownloadTaskEntity(isGroupTask,refreshInfo,useServerFileName,isChunked,charSet,entity,state,requestType,code,url,removeFile,isSupportBP,requestEnum,isNewTask,key) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
                                                     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                                                     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                                                     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                     at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                     at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1467)
                                                     at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1339)
                                                     at com.arialyy.aria.orm.DelegateUpdate.insertData(Unknown Source)
                                                     at com.arialyy.aria.orm.DelegateWrapper.insertData(Unknown Source)
                                                     at com.arialyy.aria.orm.DbEntity.insert(Unknown Source)
                                                     at com.arialyy.aria.orm.DbEntity.save(Unknown Source)
                                                     at com.arialyy.aria.core.download.BaseNormalTarget.checkEntity(Unknown Source)
                                                     at com.arialyy.aria.core.inf.AbsTarget.start(Unknown Source)
                                                     at org.liux.android.demo.tit.tools..(Unknown Source)
                                                     at org.liux.android.demo.tit.CallTools.(Unknown Source)
                                                     at org.liux.android.demo.tit.CallTools.(Unknown Source)
                                                     at org.liux.android.demo.tit..handleMessage(Unknown Source)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5072)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                     at dalvik.system.NativeStart.main(Native Method)
04-24 15:08:19.149 6121-6160/? E/SQLiteLog: (1) no such column: entity
04-24 15:08:19.149 6121-6160/? E/AndroidRuntime: FATAL EXCEPTION: Thread-442
                                                 Process: net.com.shuame.rootgeniusauuk:adf, PID: 6121
                                                 android.database.sqlite.SQLiteException: no such column: entity (code 1): , while compiling: UPDATE DownloadTaskEntity SET isGroupTask=?,refreshInfo=?,useServerFileName=?,isChunked=?,charSet=?,entity=?,state=?,requestType=?,code=?,url=?,removeFile=?,isSupportBP=?,requestEnum=?,isNewTask=?,key=? WHERE rowid=?
                                                     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                                                     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                                                     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                     at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                     at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1572)
                                                     at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1520)
                                                     at com.arialyy.aria.orm.DelegateUpdate.modifyData(Unknown Source)
                                                     at com.arialyy.aria.orm.DelegateWrapper.modifyData(Unknown Source)
                                                     at com.arialyy.aria.orm.DbEntity.update(Unknown Source)
                                                     at com.arialyy.aria.core.inf.AbsTaskEntity.update(Unknown Source)
                                                     at com.arialyy.aria.core.download.BaseDListener.saveData(Unknown Source)
                                                     at com.arialyy.aria.core.common.BaseListener.onPre(Unknown Source)
                                                     at com.arialyy.aria.core.download.downloader.SimpleDownloadUtil.run(Unknown Source)
                                                     at java.lang.Thread.run(Thread.java:841)

**Comment by hlwhsunshine** [comment]
这个问题解决了，是注解被混淆掉了，但是出现了新的问题，log显示文件已经下载成功，但是没有走回调，对比成功下载的log差异之处在于：“ DownloadReceiver: 没有Aria的注解方法“

**Comment by hlwhsunshine** [comment]
已解决，当前register的类名不能被混淆
