### ISSUE TITLE
执行队列已满，剩余任务如何自动进行？

### ISSUE THREAD

**Issue by xiaxiayang** [AriaLyy/Aria#395]
## Aria版本
3.6.3
## 什么问题
组合任务下载中，共有 16 个文件需要下载，然后日志打印，执行队列已满，值下载了12个文件，之后不回调任何方法，onWait 等都不回调，导致无法判断下载是否结束
## 如何复现此问题
目前一直可以复现

## 控制台日志

2019-05-15 13:59:39.353 14454-14454/com.nposclient D/BaseCachePool: 任务【任务组->95a0fe5949d414aa0df5e30dac835c30】进入缓存队列成功
2019-05-15 13:59:39.354 14454-14454/com.nposclient D/BaseExecutePool: 任务【任务组->95a0fe5949d414aa0df5e30dac835c30】进入执行队列成功
2019-05-15 13:59:39.363 14454-14803/com.nposclient D/SimpleSubQueue: 执行队列已满，任务进入缓存器中，key: https://img-dev.xiniunet.com/801689539428098048/photo/1120629041624387584.jpg?x-oss-process=image/resize,w_1080
2019-05-15 13:59:39.363 14454-14803/com.nposclient D/SimpleSubQueue: 执行队列已满，任务进入缓存器中，key: https://img-dev.xiniunet.com/801689539428098048/801689539881086976/1126456621543854080.jpg?x-oss-process=image/resize,w_1080
2019-05-15 13:59:39.364 14454-14803/com.nposclient D/SimpleSubQueue: 执行队列已满，任务进入缓存器中，key: https://img-dev.xiniunet.com/801689539428098048/801689539881086976/1126456911508672512.jpg?x-oss-process=image/resize,w_1080
2019-05-15 13:59:39.364 14454-14803/com.nposclient D/SimpleSubQueue: 执行队列已满，任务进入缓存器中，key: https://img-dev.xiniunet.com/801689539428098048/801689539881086976/1126457062646222848.jpg?x-oss-process=image/resize,w_1080
2019-05-15 13:59:39.364 14454-14803/com.nposclient D/SimpleSubQueue: 执行队列已满，任务进入缓存器中，key: https://img-dev.xiniunet.com/801689539428098048/801689539881086976/1126457168774696960.jpg?x-oss-process=image/resize,w_1080
2019-05-15 13:59:39.364 14454-14803/com.nposclient D/SimpleSubQueue: 执行队列已满，任务进入缓存器中，key: https://img-dev.xiniunet.com/801689539428098048/801689539881086976/852717556153585664.jpg?x-oss-process=image/resize,w_1080
2019-05-15 13:59:39.364 14454-14803/com.nposclient D/SimpleSubQueue: 执行队列已满，任务进入缓存器中，key: https://img-dev.xiniunet.com/801689539428098048/801689539881086976/852717556153585664.jpg?x-oss-process=image/resize,w_1080
2019-05-15 13:59:39.364 14454-14803/com.nposclient D/SimpleSubQueue: 执行队列已满，任务进入缓存器中，key: https://img-dev.xiniunet.com/801689539428098048/801689539881086976/852717556153585664.jpg?x-oss-process=image/resize,w_1080
2019-05-15 13:59:39.364 14454-14803/com.nposclient D/SimpleSubQueue: 执行队列已满，任务进入缓存器中，key: http://xiniunet-dev.oss.aliyuncs.com/801689539428098048/801689539881086976/871653152171364352.gif?x-oss-process=image/resize,w_1080
2019-05-15 13:59:39.364 14454-14803/com.nposclient D/SimpleSubQueue: 执行队列已满，任务进入缓存器中，key: https://img-dev.xiniunet.com/801689539428098048/801689539881086976/852719541019873280.jpg?x-oss-process=image/resize,w_1080
2019-05-15 13:59:39.364 14454-14803/com.nposclient D/SimpleSubQueue: 执行队列已满，任务进入缓存器中，key: https://img-dev.xiniunet.com/801689539428098048/801689539881086976/852719541019873280.jpg?x-oss-process=image/resize,w_1080
2019-05-15 13:59:39.364 14454-14803/com.nposclient D/SimpleSubQueue: 执行队列已满，任务进入缓存器中，key: https://img-dev.xiniunet.com/801689539428098048/801689539881086976/852717556153585664.jpg?x-oss-process=image/resize,w_1080
2019-05-15 13:59:39.364 14454-14803/com.nposclient D/SimpleSubQueue: 执行队列已满，任务进入缓存器中，key: http://xiniunet-dev.oss.aliyuncs.com/801689539428098048/801689539881086976/852706264189636608.jpeg?x-oss-process=image/resize,w_1080
2019-05-15 13:59:39.633 14454-14815/com.nposclient D/HttpThreadTask: 任务【1120629462988361728.jpg】线程__0__开始下载【开始位置 : 0，结束位置：18639】
2019-05-15 13:59:39.661 14454-14817/com.nposclient D/HttpThreadTask: 任务【1120629111182725120.jpg】线程__0__开始下载【开始位置 : 0，结束位置：110189】
2019-05-15 13:59:39.676 14454-14822/com.nposclient D/HttpThreadTask: 任务【1120626706407886848.jpg】线程__0__开始下载【开始位置 : 0，结束位置：199679】
2019-05-15 13:59:39.749 14454-14815/com.nposclient I/HttpThreadTask: 任务【1120629462988361728.jpg】线程__0__下载完毕
2019-05-15 13:59:39.779 14454-14454/com.nposclient D/SimpleSchedulers: 子任务【1120629462988361728.jpg】完成
2019-05-15 13:59:39.789 14454-14454/com.nposclient D/SimpleSchedulers: 总任务数：16，完成的任务数：1，失败的任务数：0，停止的任务数：0
2019-05-15 13:59:39.789 14454-14454/com.nposclient D/SimpleSchedulers: 启动任务：1120629041624387584.jpg
2019-05-15 13:59:39.920 14454-14873/com.nposclient D/HttpThreadTask: 任务【1120629041624387584.jpg】线程__0__开始下载【开始位置 : 0，结束位置：63561】
2019-05-15 13:59:39.952 14454-14822/com.nposclient I/HttpThreadTask: 任务【1120626706407886848.jpg】线程__0__下载完毕
2019-05-15 13:59:39.961 14454-14454/com.nposclient D/SimpleSchedulers: 子任务【1120626706407886848.jpg】完成
2019-05-15 13:59:39.968 14454-14454/com.nposclient D/SimpleSchedulers: 总任务数：16，完成的任务数：2，失败的任务数：0，停止的任务数：0
2019-05-15 13:59:39.968 14454-14454/com.nposclient D/SimpleSchedulers: 启动任务：1126456621543854080.jpg
2019-05-15 13:59:40.027 14454-14873/com.nposclient I/HttpThreadTask: 任务【1120629041624387584.jpg】线程__0__下载完毕
2019-05-15 13:59:40.044 14454-14454/com.nposclient D/SimpleSchedulers: 子任务【1120629041624387584.jpg】完成
2019-05-15 13:59:40.051 14454-14454/com.nposclient D/SimpleSchedulers: 总任务数：16，完成的任务数：3，失败的任务数：0，停止的任务数：0
2019-05-15 13:59:40.051 14454-14454/com.nposclient D/SimpleSchedulers: 启动任务：1126456911508672512.jpg
2019-05-15 13:59:40.088 14454-14815/com.nposclient D/HttpThreadTask: 任务【1126456621543854080.jpg】线程__0__开始下载【开始位置 : 0，结束位置：115708】
2019-05-15 13:59:40.100 14454-14817/com.nposclient I/HttpThreadTask: 任务【1120629111182725120.jpg】线程__0__下载完毕
2019-05-15 13:59:40.117 14454-14454/com.nposclient D/SimpleSchedulers: 子任务【1120629111182725120.jpg】完成
2019-05-15 13:59:40.122 14454-14454/com.nposclient D/SimpleSchedulers: 总任务数：16，完成的任务数：4，失败的任务数：0，停止的任务数：0
2019-05-15 13:59:40.122 14454-14454/com.nposclient D/SimpleSchedulers: 启动任务：1456456911508672566.jpg
2019-05-15 13:59:40.173 14454-14822/com.nposclient D/HttpThreadTask: 任务【1126456911508672512.jpg】线程__0__开始下载【开始位置 : 0，结束位置：64785】
2019-05-15 13:59:40.290 14454-14822/com.nposclient I/HttpThreadTask: 任务【1126456911508672512.jpg】线程__0__下载完毕
2019-05-15 13:59:40.299 14454-14454/com.nposclient D/SimpleSchedulers: 子任务【1126456911508672512.jpg】完成
2019-05-15 13:59:40.305 14454-14454/com.nposclient D/SimpleSchedulers: 总任务数：16，完成的任务数：5，失败的任务数：0，停止的任务数：0
2019-05-15 13:59:40.305 14454-14454/com.nposclient D/SimpleSchedulers: 启动任务：1126457168774696960.jpg
2019-05-15 13:59:40.396 14454-14873/com.nposclient D/HttpThreadTask: 任务【1126457168774696960.jpg】线程__0__开始下载【开始位置 : 0，结束位置：22048】
2019-05-15 13:59:40.486 14454-14815/com.nposclient I/HttpThreadTask: 任务【1126456621543854080.jpg】线程__0__下载完毕
2019-05-15 13:59:40.491 14454-14817/com.nposclient D/HttpThreadTask: 任务【1456456911508672566.jpg】线程__0__开始下载【开始位置 : 0，结束位置：65427】
2019-05-15 13:59:40.498 14454-14873/com.nposclient I/HttpThreadTask: 任务【1126457168774696960.jpg】线程__0__下载完毕
2019-05-15 13:59:40.503 14454-14454/com.nposclient D/SimpleSchedulers: 子任务【1126456621543854080.jpg】完成
2019-05-15 13:59:40.516 14454-14454/com.nposclient D/SimpleSchedulers: 总任务数：16，完成的任务数：6，失败的任务数：0，停止的任务数：0
2019-05-15 13:59:40.516 14454-14454/com.nposclient D/SimpleSchedulers: 启动任务：852717556153585664.jpg
2019-05-15 13:59:40.516 14454-14454/com.nposclient D/SimpleSchedulers: 子任务【1126457168774696960.jpg】完成
2019-05-15 13:59:40.521 14454-14454/com.nposclient D/SimpleSchedulers: 总任务数：16，完成的任务数：7，失败的任务数：0，停止的任务数：0
2019-05-15 13:59:40.522 14454-14454/com.nposclient D/SimpleSchedulers: 启动任务：871653152171364352.gif
2019-05-15 13:59:40.623 14454-14817/com.nposclient I/HttpThreadTask: 任务【1456456911508672566.jpg】线程__0__下载完毕
2019-05-15 13:59:40.635 14454-14454/com.nposclient D/SimpleSchedulers: 子任务【1456456911508672566.jpg】完成
2019-05-15 13:59:40.644 14454-14822/com.nposclient D/HttpThreadTask: 任务【852717556153585664.jpg】线程__0__开始下载【开始位置 : 0，结束位置：134204】
2019-05-15 13:59:40.651 14454-14454/com.nposclient D/SimpleSchedulers: 总任务数：16，完成的任务数：8，失败的任务数：0，停止的任务数：0
2019-05-15 13:59:40.651 14454-14454/com.nposclient D/SimpleSchedulers: 启动任务：852719541019873280.jpg
2019-05-15 13:59:40.774 14454-14815/com.nposclient D/HttpThreadTask: 任务【852719541019873280.jpg】线程__0__开始下载【开始位置 : 0，结束位置：134204】
2019-05-15 13:59:40.997 14454-14815/com.nposclient I/HttpThreadTask: 任务【852719541019873280.jpg】线程__0__下载完毕
2019-05-15 13:59:41.053 14454-14454/com.nposclient D/SimpleSchedulers: 子任务【852719541019873280.jpg】完成
2019-05-15 13:59:41.073 14454-14454/com.nposclient D/SimpleSchedulers: 总任务数：16，完成的任务数：9，失败的任务数：0，停止的任务数：0
2019-05-15 13:59:41.073 14454-14454/com.nposclient D/SimpleSchedulers: 启动任务：852706264189636608.jpeg
2019-05-15 13:59:41.335 14454-14822/com.nposclient I/HttpThreadTask: 任务【852717556153585664.jpg】线程__0__下载完毕
2019-05-15 13:59:41.346 14454-14817/com.nposclient I/HttpThreadTask: 任务下载完成
2019-05-15 13:59:41.346 14454-14454/com.nposclient D/SimpleSchedulers: 子任务【852706264189636608.jpeg】完成
2019-05-15 13:59:41.353 14454-14454/com.nposclient D/SimpleSchedulers: 总任务数：16，完成的任务数：10，失败的任务数：0，停止的任务数：0
2019-05-15 13:59:41.353 14454-14454/com.nposclient I/SimpleSchedulers: 没有下一子任务
2019-05-15 13:59:41.353 14454-14454/com.nposclient D/SimpleSchedulers: 子任务【852717556153585664.jpg】完成
2019-05-15 13:59:41.359 14454-14454/com.nposclient D/SimpleSchedulers: 总任务数：16，完成的任务数：11，失败的任务数：0，停止的任务数：0
2019-05-15 13:59:41.359 14454-14454/com.nposclient I/SimpleSchedulers: 没有下一子任务
2019-05-15 13:59:43.446 14454-14873/com.nposclient I/HttpThreadTask: 任务下载完成
2019-05-15 13:59:43.447 14454-14454/com.nposclient D/SimpleSchedulers: 子任务【871653152171364352.gif】完成
2019-05-15 13:59:43.456 14454-14454/com.nposclient D/SimpleSchedulers: 总任务数：16，完成的任务数：12，失败的任务数：0，停止的任务数：0
2019-05-15 13:59:43.456 14454-14454/com.nposclient I/SimpleSchedulers: 没有下一子任务

**Comment by AriaLyy** [comment]
升级到`3.6.4_dev_3`看看，组合任务修复了一些bug

**Comment by xiaxiayang** [comment]
升级到3.6.4_dev_3 依然这样。
代码调用：
`Aria.download(this)
                //设置一主任务，参数为List<String>
                .loadGroup(urls)
                //设置任务组的文件夹路径
                .setDirPath(groupDirPath)
                .setFileSize(urls.size())
                .setSubFileName(subNames)
                .start();`

日志输出：
2019-05-15 19:39:07.953 2552-2552/com.nposclient D/BaseCachePool: 任务【任务组->c2ebaeeca65929823b0124f137f323e1】进入缓存队列成功
2019-05-15 19:39:07.953 2552-2552/com.nposclient D/StartCmd: 开始新任务, 任务状态：3
2019-05-15 19:39:07.953 2552-2552/com.nposclient D/BaseExecutePool: 任务【任务组->c2ebaeeca65929823b0124f137f323e1】进入执行队列成功
2019-05-15 19:39:07.959 2552-3055/com.nposclient D/SimpleSubQueue: 开始执行子任务：resize,w_1080
2019-05-15 19:39:07.960 2552-3055/com.nposclient D/SimpleSubQueue: 开始执行子任务：resize,w_1080
2019-05-15 19:39:07.960 2552-3055/com.nposclient D/SimpleSubQueue: 开始执行子任务：resize,w_1080
2019-05-15 19:39:07.965 2552-3055/com.nposclient D/SimpleSubQueue: 开始执行子任务：resize,w_1080
2019-05-15 19:39:07.971 2552-3055/com.nposclient D/SimpleSubQueue: 开始执行子任务：resize,w_1080
2019-05-15 19:39:07.985 2552-3055/com.nposclient D/SimpleSubQueue: 开始执行子任务：resize,w_1080
2019-05-15 19:39:07.994 2552-3055/com.nposclient D/SimpleSubQueue: 开始执行子任务：resize,w_1080
2019-05-15 19:39:08.010 2552-3055/com.nposclient D/SimpleSubQueue: 执行队列已满，任务进入缓存器中，key: https://img-dev.xiniunet.com/801689539428098048/photo/1128541976543760384.jpg?x-oss-process=image/resize,w_1080
2019-05-15 19:39:08.010 2552-3055/com.nposclient D/SimpleSubQueue: 执行队列已满，任务进入缓存器中，key: https://img-dev.xiniunet.com/801689539428098048/photo/1128541976543760384.jpg?x-oss-process=image/resize,w_1080
2019-05-15 19:39:08.093 2552-3057/com.nposclient D/HttpFileInfoThread: 长度不一致，任务为新任务
2019-05-15 19:39:08.101 2552-3058/com.nposclient D/HttpFileInfoThread: 长度不一致，任务为新任务
2019-05-15 19:39:08.111 2552-3067/com.nposclient D/AbsFileer: 初始化记录，任务为新任务
2019-05-15 19:39:08.112 2552-3068/com.nposclient D/AbsFileer: 初始化记录，任务为新任务
2019-05-15 19:39:08.115 2552-3060/com.nposclient D/HttpFileInfoThread: 长度不一致，任务为新任务
2019-05-15 19:39:08.119 2552-3061/com.nposclient D/HttpFileInfoThread: 长度不一致，任务为新任务
2019-05-15 19:39:08.132 2552-3063/com.nposclient D/HttpFileInfoThread: 长度不一致，任务为新任务
2019-05-15 19:39:08.138 2552-3069/com.nposclient W/AbsFileer: 文件【/storage/emulated/0/com.nposclient/media/1128625853308076032/resize,w_1080】不存在，任务将重新开始
2019-05-15 19:39:08.140 2552-3070/com.nposclient W/AbsFileer: 文件【/storage/emulated/0/com.nposclient/media/1128625853308076032/resize,w_1080】不存在，任务将重新开始
2019-05-15 19:39:08.140 2552-3072/com.nposclient D/HttpThreadTask: 任务【resize,w_1080】线程__0__开始下载【开始位置 : 0，结束位置：18639】
2019-05-15 19:39:08.142 2552-3071/com.nposclient W/AbsFileer: 文件【/storage/emulated/0/com.nposclient/media/1128625853308076032/resize,w_1080】不存在，任务将重新开始
2019-05-15 19:39:08.156 2552-3074/com.nposclient D/HttpThreadTask: 任务【resize,w_1080】线程__0__开始下载【开始位置 : 0，结束位置：18639】
2019-05-15 19:39:08.164 2552-3069/com.nposclient D/AbsFileer: 初始化记录，任务为新任务
2019-05-15 19:39:08.165 2552-3070/com.nposclient D/AbsFileer: 初始化记录，任务为新任务
2019-05-15 19:39:08.166 2552-3071/com.nposclient D/AbsFileer: 初始化记录，任务为新任务
2019-05-15 19:39:08.173 2552-3059/com.nposclient D/HttpFileInfoThread: 长度不一致，任务为新任务
2019-05-15 19:39:08.186 2552-3076/com.nposclient D/HttpThreadTask: 任务【resize,w_1080】线程__0__开始下载【开始位置 : 0，结束位置：63561】
2019-05-15 19:39:08.196 2552-3078/com.nposclient D/HttpThreadTask: 任务【resize,w_1080】线程__0__开始下载【开始位置 : 0，结束位置：63561】
2019-05-15 19:39:08.245 2552-3072/com.nposclient I/HttpThreadTask: 任务【resize,w_1080】线程__0__下载完毕
2019-05-15 19:39:08.254 2552-3074/com.nposclient I/HttpThreadTask: 任务【resize,w_1080】线程__0__下载完毕
2019-05-15 19:39:08.256 2552-3072/com.nposclient I/AbsThreadTask: 任务【resize,w_1080】完成
2019-05-15 19:39:08.264 2552-3074/com.nposclient I/AbsThreadTask: 任务【resize,w_1080】完成
2019-05-15 19:39:08.267 2552-2552/com.nposclient D/SimpleSchedulers: 子任务【resize,w_1080】完成
2019-05-15 19:39:08.269 2552-3072/com.nposclient D/HttpThreadTask: 任务【resize,w_1080】线程__0__开始下载【开始位置 : 0，结束位置：63561】
2019-05-15 19:39:08.276 2552-2552/com.nposclient D/SimpleSchedulers: 总任务数：9，完成的任务数：1，失败的任务数：0，停止的任务数：0
2019-05-15 19:39:08.276 2552-2552/com.nposclient D/SimpleSchedulers: 启动任务：resize,w_1080
2019-05-15 19:39:08.277 2552-2552/com.nposclient D/SimpleSubQueue: 开始执行子任务：resize,w_1080
2019-05-15 19:39:08.290 2552-2552/com.nposclient D/SimpleSchedulers: 子任务【resize,w_1080】完成
2019-05-15 19:39:08.297 2552-2552/com.nposclient D/SimpleSchedulers: 总任务数：9，完成的任务数：2，失败的任务数：0，停止的任务数：0
2019-05-15 19:39:08.297 2552-2552/com.nposclient I/SimpleSchedulers: 没有下一子任务
2019-05-15 19:39:08.341 2552-3076/com.nposclient I/HttpThreadTask: 任务【resize,w_1080】线程__0__下载完毕
2019-05-15 19:39:08.352 2552-3076/com.nposclient I/AbsThreadTask: 任务【resize,w_1080】完成
2019-05-15 19:39:08.436 2552-3065/com.nposclient D/HttpFileInfoThread: 长度不一致，任务为新任务
2019-05-15 19:39:08.441 2552-3081/com.nposclient D/HttpFileInfoThread: 长度不一致，任务为新任务
2019-05-15 19:39:08.451 2552-2552/com.nposclient D/SimpleSchedulers: 子任务【resize,w_1080】完成
2019-05-15 19:39:08.494 2552-3078/com.nposclient I/HttpThreadTask: 任务【resize,w_1080】线程__0__下载完毕
2019-05-15 19:39:08.526 2552-2552/com.nposclient D/SimpleSchedulers: 总任务数：9，完成的任务数：3，失败的任务数：0，停止的任务数：0
2019-05-15 19:39:08.527 2552-2552/com.nposclient I/SimpleSchedulers: 没有下一子任务
2019-05-15 19:39:08.534 2552-3082/com.nposclient D/AbsFileer: 任务【resize,w_1080】线程__0__恢复任务
2019-05-15 19:39:08.534 2552-3082/com.nposclient D/AbsFileer: 任务【resize,w_1080】线程__1__已完成
2019-05-15 19:39:08.535 2552-3082/com.nposclient D/AbsFileer: 任务【resize,w_1080】线程__2__已完成
2019-05-15 19:39:08.545 2552-3078/com.nposclient I/AbsThreadTask: 任务【resize,w_1080】完成
2019-05-15 19:39:08.545 2552-3083/com.nposclient D/AbsFileer: 任务【resize,w_1080】线程__0__恢复任务
2019-05-15 19:39:08.545 2552-3083/com.nposclient D/AbsFileer: 任务【resize,w_1080】线程__1__已完成
2019-05-15 19:39:08.545 2552-3083/com.nposclient D/AbsFileer: 任务【resize,w_1080】线程__2__已完成
2019-05-15 19:39:08.545 2552-3083/com.nposclient D/AbsFileer: 任务【resize,w_1080】线程__3__已完成
2019-05-15 19:39:08.580 2552-2552/com.nposclient D/SimpleSchedulers: 子任务【resize,w_1080】完成
2019-05-15 19:39:08.592 2552-3076/com.nposclient D/HttpThreadTask: 任务【resize,w_1080】线程__0__开始下载【开始位置 : 0，结束位置：34339】
2019-05-15 19:39:08.595 2552-3074/com.nposclient D/HttpThreadTask: 任务【resize,w_1080】线程__4__开始下载【开始位置 : 137356，结束位置：171699】
2019-05-15 19:39:08.596 2552-3078/com.nposclient D/HttpThreadTask: 任务【resize,w_1080】线程__3__开始下载【开始位置 : 103017，结束位置：137356】
2019-05-15 19:39:08.609 2552-2552/com.nposclient D/SimpleSchedulers: 总任务数：9，完成的任务数：4，失败的任务数：0，停止的任务数：0
2019-05-15 19:39:08.609 2552-2552/com.nposclient I/SimpleSchedulers: 没有下一子任务
2019-05-15 19:39:08.688 2552-3078/com.nposclient I/HttpThreadTask: 任务【resize,w_1080】线程__3__下载完毕
2019-05-15 19:39:08.696 2552-3078/com.nposclient D/HttpThreadTask: 任务【resize,w_1080】线程__4__开始下载【开始位置 : 137356，结束位置：171699】
2019-05-15 19:39:08.696 2552-3074/com.nposclient I/HttpThreadTask: 任务【resize,w_1080】线程__4__下载完毕
2019-05-15 19:39:08.705 2552-3074/com.nposclient D/HttpThreadTask: 任务【resize,w_1080】线程__0__开始下载【开始位置 : 0，结束位置：34339】
2019-05-15 19:39:08.709 2552-3076/com.nposclient I/HttpThreadTask: 任务【resize,w_1080】线程__0__下载完毕
2019-05-15 19:39:08.755 2552-3072/com.nposclient I/HttpThreadTask: 任务【resize,w_1080】线程__0__下载完毕
2019-05-15 19:39:08.761 2552-3072/com.nposclient I/AbsThreadTask: 任务【resize,w_1080】完成
2019-05-15 19:39:08.764 2552-2552/com.nposclient D/SimpleSchedulers: 子任务【resize,w_1080】完成
2019-05-15 19:39:08.772 2552-2552/com.nposclient D/SimpleSchedulers: 总任务数：9，完成的任务数：5，失败的任务数：0，停止的任务数：0
2019-05-15 19:39:08.772 2552-2552/com.nposclient I/SimpleSchedulers: 没有下一子任务
2019-05-15 19:39:08.787 2552-3078/com.nposclient I/HttpThreadTask: 任务【resize,w_1080】线程__4__下载完毕
2019-05-15 19:39:08.854 2552-3074/com.nposclient I/HttpThreadTask: 任务【resize,w_1080】线程__0__下载完毕

**Comment by xiaxiayang** [comment]
看了还有一些报错信息：
2019-05-15 19:53:47.955 11592-11592/com.nposclient E/SQLiteDatabase: Error inserting stopTime=0 fileName=1120629462988361728.jpg isComplete=false isGroupChild=true groupHash=fd731ce3664cf1b9f906baf80bc30b92 downloadPath=%2Fstorage%2Femulated%2F0%2Fcom.nposclient%2Fmedia%2F1128629544773746688%2F%2F1120629462988361728.jpg url=https%3A%2F%2Fimg-dev.xiniunet.com%2F801689539428098048%2Fphoto%2F1120629462988361728.jpg fileSize=0 state=3 currentProgress=0 percent=0 isRedirect=false completeTime=0
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: DownloadEntity.downloadPath (code 1555)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1472)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1343)
        at com.arialyy.aria.orm.DelegateUpdate.insertManyData(DelegateUpdate.java:117)
        at com.arialyy.aria.orm.DelegateWrapper.insertManyData(DelegateWrapper.java:186)
        at com.arialyy.aria.orm.DbEntity.saveAll(DbEntity.java:214)
        at com.arialyy.aria.core.download.HttpGroupDelegate.saveEntity(HttpGroupDelegate.java:141)
        at com.arialyy.aria.core.download.HttpGroupDelegate.checkEntity(HttpGroupDelegate.java:135)
        at com.arialyy.aria.core.download.DownloadGroupTarget.checkEntity(DownloadGroupTarget.java:173)
        at com.arialyy.aria.core.inf.AbsTarget.start(AbsTarget.java:247)
        at com.nposclient.manager.CltDbManager.downFile(CltDbManager.java:601)
        at com.nposclient.manager.CltDbManager.doDownloadData(CltDbManager.java:450)
        at com.nposclient.manager.CltDbManager.isSyncFinished(CltDbManager.java:737)
        at com.nposclient.manager.CltDbManager.access$900(CltDbManager.java:54)
        at com.nposclient.manager.CltDbManager$4.onResponse(CltDbManager.java:818)
        at com.nposclient.manager.CltDbManager$4.onResponse(CltDbManager.java:799)
        at com.nposclient.biz.XNHttpRequest2$1.onPostExecute(XNHttpRequest2.java:63)
        at com.nposclient.biz.XNHttpRequest2$1.onPostExecute(XNHttpRequest2.java:39)
        at android.os.AsyncTask.finish(AsyncTask.java:660)
        at android.os.AsyncTask.-wrap1(AsyncTask.java)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by xiaxiayang** [comment]
你好，详细看了下数据，是因为下载的9条数据里面其实只有3条不同的，其余都是重复的。
进行数据去重后，就没问题了

**Comment by AriaLyy** [comment]
感谢反馈，后面我会增加一个url重复的检查
