### ISSUE TITLE
有没有什么重新下载的好方案呢

### ISSUE THREAD

**Issue by moeshin** [AriaLyy/Aria#403]
## Aria版本
3.6.4

## 什么问题
使用 reStart 这个函数，也没法实现重新下载

```java
public class MainActivity extends AppCompatActivity {

    private final static String URL = "https://music.163.com/song/media/outer/url?id=1321297488";

    @SuppressLint("SdCardPath")
    private final static String PATH = "/sdcard/Download/test.mp3";

    private DownloadReceiver download;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        download = Aria.download(this);
        download.register();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        download.unRegister();
    }

    public void onStart(View view) {
        download.load(URL).setFilePath(PATH).start();
    }

    public void onRestart(View view) {
        final String TAG = "onRestart";
        Log.d(TAG, "taskExists: " +  download.load(URL).taskExists());
        download.load(URL).reStart();
        Log.d(TAG, "taskExists: " +  download.load(URL).taskExists());
    }

    public void onCheck(View view) {
        final String TAG = "onCheck";
        Log.d(TAG, "taskExists: " +  download.load(URL).taskExists());
    }

    public void onCancel(View view) {
        final String TAG = "onCancel";
        Log.d(TAG, "taskExists: " +  download.load(URL).taskExists());
        download.load(URL).cancel();
        Log.d(TAG, "taskExists: " +  download.load(URL).taskExists());
    }

    @Download.onTaskStart
    public void onTaskStart(DownloadTask task) {
        final String TAG = "onTaskStart";
        Log.d(TAG, "");
    }

    @Download.onTaskRunning
    public void onTaskRunning(DownloadTask task) {
        final String TAG = "onTaskRunning";
        Log.d(TAG, "getPercent: " + task.getPercent());
    }
}
```

下载时还有一条警告
`W/System.err: java.io.IOException: open failed: EACCES (Permission denied)`
我有给权限，也下载得下来，不知道咋回事

## 控制台日志
```
按下 Start 按钮
D/BaseCachePool: 任务【test.mp3】进入缓存队列成功
D/StartCmd: 开始新任务, 任务状态：3
D/BaseExecutePool: 任务【test.mp3】进入执行队列成功

莫名警告，不知道怎么回事
W/System.err: java.io.IOException: open failed: EACCES (Permission denied)
        at java.io.File.createNewFile(File.java:941)
        at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
        at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
        at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
        at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:209)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:123)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:83)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at java.io.File.createNewFile(File.java:934)
    	... 7 more
    java.io.IOException: open failed: EACCES (Permission denied)
        at java.io.File.createNewFile(File.java:941)
        at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
        at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
        at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
        at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:209)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:123)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:83)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at java.io.File.createNewFile(File.java:934)
    	... 7 more
    java.io.IOException: open failed: EACCES (Permission denied)
        at java.io.File.createNewFile(File.java:941)
        at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
        at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
        at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
        at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:209)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:123)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:83)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at java.io.File.createNewFile(File.java:934)
    	... 7 more
    java.io.IOException: open failed: EACCES (Permission denied)
        at java.io.File.createNewFile(File.java:941)
        at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
        at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
        at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
        at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:209)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:123)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:83)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at java.io.File.createNewFile(File.java:934)
    	... 7 more
    java.io.IOException: open failed: EACCES (Permission denied)
        at java.io.File.createNewFile(File.java:941)
        at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
        at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
        at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
        at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:209)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:123)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:83)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at java.io.File.createNewFile(File.java:934)
    	... 7 more
D/HttpFileInfoThread: 30x跳转，新url为【https://m10.music.126.net/20190521230848/916649d03d1a078a0a5958736bcc401e/ymusic/73fa/3ca0/97ee/18278f358765a5357d4c9a0d5d4d2f09.mp3】
W/System: Ignoring header Cookie because its value was null.
W/System.err: java.io.IOException: open failed: EACCES (Permission denied)
        at java.io.File.createNewFile(File.java:941)
        at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
        at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
        at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
        at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:209)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:123)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleUrlReTurn(HttpFileInfoThread.java:304)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:208)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:83)
        at java.lang.Thread.run(Thread.java:818)
W/System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at java.io.File.createNewFile(File.java:934)
    	... 9 more
    java.io.IOException: open failed: EACCES (Permission denied)
        at java.io.File.createNewFile(File.java:941)
        at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
        at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
        at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
        at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:209)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:123)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleUrlReTurn(HttpFileInfoThread.java:304)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:208)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:83)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at java.io.File.createNewFile(File.java:934)
    	... 9 more
    java.io.IOException: open failed: EACCES (Permission denied)
        at java.io.File.createNewFile(File.java:941)
        at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
        at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
        at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
        at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:209)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:123)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleUrlReTurn(HttpFileInfoThread.java:304)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:208)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:83)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at java.io.File.createNewFile(File.java:934)
    	... 9 more
    java.io.IOException: open failed: EACCES (Permission denied)
        at java.io.File.createNewFile(File.java:941)
        at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
        at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
        at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
        at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:209)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:123)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleUrlReTurn(HttpFileInfoThread.java:304)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:208)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:83)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at java.io.File.createNewFile(File.java:934)
    	... 9 more
    java.io.IOException: open failed: EACCES (Permission denied)
        at java.io.File.createNewFile(File.java:941)
        at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
        at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
        at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
        at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:209)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:123)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleUrlReTurn(HttpFileInfoThread.java:304)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:208)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:83)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at java.io.File.createNewFile(File.java:934)
    	... 9 more
D/HttpFileInfoThread: 长度不一致，任务为新任务
D/AbsFileer: path: /sdcard/Download/test.mp3
D/AbsFileer: 初始化记录，任务为新任务
D/AbsFileer: 保存记录，线程记录数：3
D/AbsFileer: 启动定时器
D/HttpThreadTask: 任务【test.mp3】线程__1__开始下载【开始位置 : 1998695，结束位置：3997390】
D/HttpThreadTask: 任务【test.mp3】线程__0__开始下载【开始位置 : 0，结束位置：1998695】
D/onTaskRunning: getPercent: 0
......
D/onTaskRunning: getPercent: 65
I/HttpThreadTask: 任务【test.mp3】线程__0__下载完毕
D/HttpThreadTask: 任务【test.mp3】线程__2__开始下载【开始位置 : 3997390，结束位置：5996086】
I/HttpThreadTask: 任务【test.mp3】线程__1__下载完毕
D/onTaskRunning: getPercent: 66
......
D/onTaskRunning: getPercent: 99
I/HttpThreadTask: 任务【test.mp3】线程__2__下载完毕
I/AbsThreadTask: 任务【test.mp3】完成
W/CommonUtil: 记录为空
D/AbsTaskQueue: 从执行池删除任务【test.mp3】成功
D/AbsSchedulers: complete_next
I/AbsSchedulers: 没有等待中的任务
-----------------------------------------------------------
按下 Restart 按钮
D/onRestart: taskExists: true
D/BaseCachePool: 任务【test.mp3】进入缓存队列成功
W/StartCmd: 任务【test.mp3】已经在运行
D/onRestart: taskExists: true
D/AbsTaskQueue: 从缓存池删除任务【test.mp3】成功
D/AbsSchedulers: stop_next
I/AbsSchedulers: 没有等待中的任务
```

## 尝试其他方法

先 `removeRecord()` 或者 `cancel(true)`
再 `start()` ，也是不能重新下载

**Comment by AriaLyy** [comment]
1、警告可以忽略，具体可以看源码
2、你需要到重新下载是什么样的？我这理是删除原记录后重新下载文件

**Comment by moeshin** [comment]
就是删除记录后马上接着自己重新下载，我用上面的几种方法都不行

**Comment by AriaLyy** [comment]
先调用：`Aria.download(this).load(DOWNLOAD_URL).cancel(true);`在调用`start()`
这个方式我这是是可行的

**Comment by moeshin** [comment]
我调用 `cancel(true);` 后，马上 `start();` 不能重新下载
如果开一个线程就再 `start();`

### 马上 `start`
```java
    public void onRestart(View view) {

        final String TAG = "onRestart";

        Log.d(TAG, "taskExists: " +  download.load(URL).taskExists());

        final DownloadTarget target = download.load(URL);

        target.cancel(true);

        Log.d(TAG, "taskExists: " +  download.load(URL).taskExists());

        target.start();
    }
```

```
D/onRestart: taskExists: true
D/BaseCachePool: 任务【test.mp3】进入缓存队列成功
D/onRestart: taskExists: false
W/StartCmd: 任务【test.mp3】已经在运行
D/AbsTaskQueue: 从缓存池删除任务【test.mp3】成功
D/AbsSchedulers: stop_next
I/AbsSchedulers: 没有等待中的任务
```

### 线程 `start`
```java
    public void onRestart(View view) {

        final String TAG = "onRestart";

        Log.d(TAG, "taskExists: " +  download.load(URL).taskExists());

        final DownloadTarget target = download.load(URL);

        target.cancel(true);

        Log.d(TAG, "taskExists: " +  download.load(URL).taskExists());

        new Thread(new Runnable() {
            @Override
            public void run() {
                target.start();
            }
        }).start();
    }
```
```
D/onRestart: taskExists: true
D/BaseCachePool: 任务【test.mp3】进入缓存队列成功
D/onRestart: taskExists: false
D/AbsTaskQueue: 从缓存池删除任务【test.mp3】成功
D/AbsSchedulers: stop_next
I/AbsSchedulers: 没有等待中的任务
D/BaseCachePool: 任务【test.mp3】进入缓存队列成功
D/StartCmd: 开始新任务, 任务状态：7
D/BaseExecutePool: 任务【test.mp3】进入执行队列成功
W/System.err: java.io.IOException: open failed: EACCES (Permission denied)
        at java.io.File.createNewFile(File.java:941)
        at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
        at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
        at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
        at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:209)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:123)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:83)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at java.io.File.createNewFile(File.java:934)
    	... 7 more
    java.io.IOException: open failed: EACCES (Permission denied)
        at java.io.File.createNewFile(File.java:941)
        at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
        at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
        at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
        at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:209)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:123)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:83)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at java.io.File.createNewFile(File.java:934)
    	... 7 more
    java.io.IOException: open failed: EACCES (Permission denied)
        at java.io.File.createNewFile(File.java:941)
        at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
        at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
        at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
        at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:209)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:123)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:83)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at java.io.File.createNewFile(File.java:934)
    	... 7 more
W/System.err: java.io.IOException: open failed: EACCES (Permission denied)
        at java.io.File.createNewFile(File.java:941)
        at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
        at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
        at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
        at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:209)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:123)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:83)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at java.io.File.createNewFile(File.java:934)
    	... 7 more
    java.io.IOException: open failed: EACCES (Permission denied)
        at java.io.File.createNewFile(File.java:941)
        at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
        at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
        at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
        at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:209)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:123)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:83)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at java.io.File.createNewFile(File.java:934)
    	... 7 more
D/HttpFileInfoThread: 30x跳转，新url为【https://m10.music.126.net/20190522141744/9f7d1d22b3b49895a1a29a5018e51bae/ymusic/73fa/3ca0/97ee/18278f358765a5357d4c9a0d5d4d2f09.mp3】
W/System: Ignoring header Cookie because its value was null.
W/System.err: java.io.IOException: open failed: EACCES (Permission denied)
        at java.io.File.createNewFile(File.java:941)
        at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
        at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
        at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
        at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:209)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:123)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleUrlReTurn(HttpFileInfoThread.java:304)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:208)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:83)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at java.io.File.createNewFile(File.java:934)
    	... 9 more
    java.io.IOException: open failed: EACCES (Permission denied)
        at java.io.File.createNewFile(File.java:941)
        at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
        at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
        at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
        at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:209)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:123)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleUrlReTurn(HttpFileInfoThread.java:304)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:208)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:83)
        at java.lang.Thread.run(Thread.java:818)
W/System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at java.io.File.createNewFile(File.java:934)
    	... 9 more
    java.io.IOException: open failed: EACCES (Permission denied)
        at java.io.File.createNewFile(File.java:941)
        at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
        at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
        at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
        at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:209)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:123)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleUrlReTurn(HttpFileInfoThread.java:304)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:208)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:83)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at java.io.File.createNewFile(File.java:934)
    	... 9 more
    java.io.IOException: open failed: EACCES (Permission denied)
        at java.io.File.createNewFile(File.java:941)
        at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
        at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
        at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
        at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:209)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:123)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleUrlReTurn(HttpFileInfoThread.java:304)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:208)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:83)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at java.io.File.createNewFile(File.java:934)
    	... 9 more
    java.io.IOException: open failed: EACCES (Permission denied)
        at java.io.File.createNewFile(File.java:941)
        at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
        at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
        at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
        at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:209)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:123)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleUrlReTurn(HttpFileInfoThread.java:304)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:208)
        at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:83)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at java.io.File.createNewFile(File.java:934)
    	... 9 more
D/AbsFileer: path: /sdcard/Download/test.mp3
D/AbsFileer: 初始化记录，任务为新任务
D/AbsFileer: 保存记录，线程记录数：3
D/AbsFileer: 启动定时器
D/HttpThreadTask: 任务【test.mp3】线程__1__开始下载【开始位置 : 1998695，结束位置：3997390】
D/HttpThreadTask: 任务【test.mp3】线程__0__开始下载【开始位置 : 0，结束位置：1998695】
D/onTaskRunning: getPercent: 0
D/onTaskRunning: getPercent: 1
D/onTaskRunning: getPercent: 39
I/HttpThreadTask: 任务【test.mp3】线程__1__下载完毕
D/HttpThreadTask: 任务【test.mp3】线程__2__开始下载【开始位置 : 3997390，结束位置：5996086】
I/HttpThreadTask: 任务【test.mp3】线程__0__下载完毕
D/onTaskRunning: getPercent: 78
I/HttpThreadTask: 任务【test.mp3】线程__2__下载完毕
I/AbsThreadTask: 任务【test.mp3】完成
W/CommonUtil: 记录为空
D/AbsTaskQueue: 从执行池删除任务【test.mp3】成功
D/AbsSchedulers: complete_next
I/AbsSchedulers: 没有等待中的任务
```

但实际上在我的项目里，我是是用了延迟 500ms 才能重新下载

**Comment by AriaLyy** [comment]
3.6.5_dev_1 已经修复了这个问题

**Comment by moeshin** [comment]
没问题了，感谢

**Comment by moeshin** [comment]
`reStart` 后，这个任务 `isComplete` 应该重置为 `false` 吧？

**Comment by moeshin** [comment]
`reStart` 里，是不是应该调用 `@Download.onTaskCancel`，方便处理

**Comment by AriaLyy** [comment]
是有这个状态更新的问题。
重新下载后是不会回调onTaskCancel的

**Comment by AriaLyy** [comment]
3.6.5_dev_2 已经修复了那个状态错误的问题

**Comment by moeshin** [comment]
有时候 `stop` 任务会出现这种情况

```
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.arialyy.aria.core.download.DownloadTask.setHighestPriority(boolean)' on a null object reference
        at com.arialyy.aria.core.queue.DownloadTaskQueue.stopTask(DownloadTaskQueue.java:115)
        at com.arialyy.aria.core.queue.DownloadTaskQueue.stopTask(DownloadTaskQueue.java:33)
        at com.arialyy.aria.core.command.normal.AbsNormalCmd.stopTask(AbsNormalCmd.java:108)
        at com.arialyy.aria.core.command.normal.StopCmd.executeCmd(StopCmd.java:39)
        at com.arialyy.aria.core.AriaManager.exe(AriaManager.java:259)
        at com.arialyy.aria.core.inf.AbsTarget.stop(AbsTarget.java:310)
        at site.littlehands.adm.DownloadAdapter$ViewHolder$1.onClick(DownloadAdapter.java:63)
```

**Comment by AriaLyy** [comment]
如何出现的？

**Comment by moeshin** [comment]
頻繁暫停恢復或者要要下載完成的時候

**Comment by AriaLyy** [comment]
使用`3.6.4_dev_5`，这个是改你这个issues引发的新问题
