### ISSUE TITLE
HttpThreadTask cannot be cast to java.lang.Long

### ISSUE THREAD

**Issue by dingyong666** [AriaLyy/Aria#414]
## Aria版本
3.6.5_beta_2

## 什么问题
貌似是下载失败触发的

## 如何复现此问题
如上

## 控制台日志
E/CrashReport: java.lang.ClassCastException: com.arialyy.aria.core.download.downloader.HttpThreadTask cannot be cast to java.lang.Long
        at com.arialyy.aria.core.common.ThreadStateManager.handleMessage(ThreadStateManager.java:109)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at com.arialyy.aria.core.common.AbsFileer.startFlow(AbsFileer.java:112)
        at com.arialyy.aria.core.common.AbsFileer.run(AbsFileer.java:119)
        at java.lang.Thread.run(Thread.java:764)

**Comment by AriaLyy** [comment]
`3.6.5`已经修复来这个问题

**Comment by zhukai123** [comment]
我在fregment中unRegist后还会继续下载! 然后停留在其他页面后就会报此bug

**Comment by zhukai123** [comment]
2019-08-22 17:50:15.388 11986-12177/com.androidapp.xmosy E/kkError:AndroidRuntime: --->onUncaughtExceptionHappened:Thread[Thread-23,5,main]<---
    java.lang.ClassCastException: com.arialyy.aria.core.download.downloader.HttpThreadTask cannot be cast to java.lang.Long
        at com.arialyy.aria.core.common.ThreadStateManager.handleMessage(ThreadStateManager.java:105)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:201)
        at com.arialyy.aria.core.common.AbsFileer.startFlow(AbsFileer.java:109)
        at com.arialyy.aria.core.common.AbsFileer.run(AbsFileer.java:116)
        at java.lang.Thread.run(Thread.java:764)
