### ISSUE TITLE
no such table: DownloadGroupEntity 

### ISSUE THREAD

**Issue by illdvm** [AriaLyy/Aria#420]
## Aria版本
3.6.4

## 什么问题
3.6.4是不是没有DownloadGroupEntity表了

## 如何复现此问题
Aria由3.2.0升级到3.6.4，手机中安装的app版本是集成3.2.0的旧版本，然后覆盖安装集成3.6.4的新版本app ，走到初始化Aria的时候就崩了。

## 控制台日志
Caused by: android.database.sqlite.SQLiteException: no such table: DownloadGroupEntity (code 1 SQLITE_ERROR[1]): , while compiling: DELETE FROM DownloadGroupEntity WHERE groupName='' OR groupName IS NULL
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1229)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:703)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
        at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2227)
        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2155)
        at com.arialyy.aria.orm.SqlHelper.handle314AriaUpdate(SqlHelper.java:275)
        at com.arialyy.aria.orm.SqlHelper.onUpgrade(SqlHelper.java:98)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:400)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
        at com.arialyy.aria.orm.SqlHelper.getDb(SqlHelper.java:125)
        at com.arialyy.aria.orm.DelegateWrapper.<init>(DelegateWrapper.java:39)
        at com.arialyy.aria.orm.DelegateWrapper.init(DelegateWrapper.java:46)
        at com.arialyy.aria.core.AriaManager.initDb(AriaManager.java:120)
        at com.arialyy.aria.core.AriaManager.<init>(AriaManager.java:87)
        at com.arialyy.aria.core.AriaManager.getInstance(AriaManager.java:97)
        at com.arialyy.aria.core.Aria.init(Aria.java:128)

**Comment by AriaLyy** [comment]
使用`3.6.5_beta_3`

**Comment by illdvm** [comment]
> 使用`3.6.5_beta_3`

Aria由3.2.0升级到3.6.5_beta_3，手机中安装的app版本是集成3.2.0的旧版本，然后覆盖安装集成3.6.5_beta_3的新版本app ，走到初始化Aria的时候依然崩溃。

**Comment by AriaLyy** [comment]
能否提供下初问题的数据库？

**Comment by illdvm** [comment]
> 能否提供下初问题的数据库？

测试机无法root 导不出data下的数据库文件啊

**Comment by AriaLyy** [comment]
使用`3.6.5_beta_4`

**Comment by illdvm** [comment]
> 使用`3.6.5_beta_4`

3.6.5_beta_4好使了 不报错了
