### ISSUE TITLE
running回调数值返回null

### ISSUE THREAD

**Issue by Zvirtuey** [AriaLyy/Aria#421]
## Aria版本
3.4.16

## 什么问题
@Download.onTaskRunning
    protected void running(DownloadTask task) {
        // Log.e("MyFragment","----ontaskrunning");
        int p = task.getPercent();    //任务进度百分比
        download_progressBar.setProgress(p); //282行,为null
        tv_percent.setText(p + "%");
    }

## 如何复现此问题
    点击下载，然后马上点击取消

## 控制台日志

 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ProgressBar.setProgress(int)' on a null object reference
	at com.rzt.phone.fragment.MyFragment.running(MyFragment.java:282)
	at com.rzt.phone.fragment.MyFragment$$DownloadListenerProxy.onTaskRunning(MyFragment$$DownloadListenerProxy.java:57)
	at com.rzt.phone.fragment.MyFragment$$DownloadListenerProxy.onTaskRunning(MyFragment$$DownloadListenerProxy.java:16)
	at com.arialyy.aria.core.scheduler.AbsSchedulers.callback(AbsSchedulers.java:228)
	at com.arialyy.aria.core.scheduler.AbsSchedulers.callback(AbsSchedulers.java:205)
	at com.arialyy.aria.core.scheduler.AbsSchedulers.handleNormalEvent(AbsSchedulers.java:192)
	at com.arialyy.aria.core.scheduler.AbsSchedulers.handleMessage(AbsSchedulers.java:118)
	at com.arialyy.aria.core.scheduler.DownloadSchedulers.handleMessage(DownloadSchedulers.java:29)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5737)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by AriaLyy** [comment]
使用`3.6.5_beta_3`
