### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.String java.io.File.getPath()' on a null object reference

### ISSUE THREAD

**Issue by EchoYuQ** [AriaLyy/Aria#429]
## Aria版本
3.6.3

## 什么问题
进入App, 在Application初始化的时候调用Aria.init(this)产生的崩溃

## 如何复现此问题
我是在Firebase平台收集到的用户崩溃，发生了100多次，自己没有复现过

## 控制台日志
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getPath()' on a null object reference
       at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase + 722(SQLiteDatabase.java:722)
       at com.arialyy.aria.orm.DatabaseContext.openOrCreateDatabase + 91(DatabaseContext.java:91)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked + 223(SQLiteOpenHelper.java:223)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase + 163(SQLiteOpenHelper.java:163)
       at com.arialyy.aria.orm.SqlHelper.getDb + 128(SqlHelper.java:128)
       at com.arialyy.aria.orm.DelegateWrapper.(DelegateWrapper.java:39)
       at com.arialyy.aria.orm.DelegateWrapper.init + 46(DelegateWrapper.java:46)
       at com.arialyy.aria.core.AriaManager.initDb + 120(AriaManager.java:120)
       at com.arialyy.aria.core.AriaManager.(AriaManager.java:87)
       at com.arialyy.aria.core.AriaManager.getInstance + 97(AriaManager.java:97)
       at com.arialyy.aria.core.Aria.init + 128(Aria.java:128)
       at com.youdao.uclass.UClassApplication.onCreate + 118(UClassApplication.java:118)
       at android.app.Instrumentation.callApplicationOnCreate + 1024(Instrumentation.java:1024)
       at android.app.ActivityThread.handleBindApplication + 5014(ActivityThread.java:5014)
       at android.app.ActivityThread.access$1700 + 188(ActivityThread.java:188)
       at android.app.ActivityThread$H.handleMessage + 1587(ActivityThread.java:1587)
       at android.os.Handler.dispatchMessage + 111(Handler.java:111)
       at android.os.Looper.loop + 207(Looper.java:207)
       at android.app.ActivityThread.main + 5790(ActivityThread.java:5790)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 1015(ZygoteInit.java:1015)
       at com.android.internal.os.ZygoteInit.main + 876(ZygoteInit.java:876)

**Comment by AriaLyy** [comment]
`3.6.6_beta_1`已经修复了这个问题
