### ISSUE TITLE
3.6.6_beta_1 空指针

### ISSUE THREAD

**Issue by w0080626** [AriaLyy/Aria#431]
## Aria版本
3.6.6_beta_1

## 什么问题
空指针异常

## 如何复现此问题
组下载

## 控制台日志
崩溃信息:
Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference

类名:Downloader.java

方法:onPostPre

行数:109

类型:java.lang.NullPointerException

时间2019-07-25 01:13

设备名称:Android SDK built for x86

设备厂商:google

系统版本:28

全部信息:
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference
	at com.arialyy.aria.core.download.downloader.Downloader.onPostPre(Downloader.java:109)
	at com.arialyy.aria.core.common.AbsFileer.startFlow(AbsFileer.java:106)
	at com.arialyy.aria.core.common.AbsFileer.run(AbsFileer.java:116)
	at java.lang.Thread.run(Thread.java:919)

**Comment by AriaLyy** [comment]
`3.6.6_beta_3`已经修复了这个问题
