### ISSUE TITLE
Aria.download(Context).stopAllTask()方法的问题

### ISSUE THREAD

**Issue by huangyuan0pplabs** [AriaLyy/Aria#435]
## Aria版本
3.6.4

## 什么问题
使用框架下载一个游戏整合包，整合包内含数十个1G的压缩包分卷，总大小36G左右，在红米6手机上开始整合包数十个文件的下载后，使用Aria.download(Context).stopAllTask()方法和Aria.download(Context).resumeAllTask()方法全部暂停暂停全部恢复，发现全部暂停有问题，有一次捕获到框架代码报错，有数次发现全部暂停时Aria.download(Context).stopAllTask()方法一直在执行，多次发现执行Aria.download(Context).stopAllTask()方法后有任务并未停止，单独停止该任务有时也会一直执行stop方法而不停止，或者执行stop()方法后任务不停止，此时执行删除任务无效，有时执行完了没有效果，有时一直在执行。

全部恢复方法并未发现执行问题。

杀死应用进程后，再进入应用，使用全部恢复和全部停止任务方法并未出现什么异常状况。

红米6手机全部存储空间大小8G，当时剩余2G到3G的空间，使用全部存储空间128G的当时剩余20多G空间的小米6试验，并未出现上述问题。

## 如何复现此问题
如上

## 控制台日志
报错代码

E/SQLiteDatabase: Error inserting isGroupRecord=false fileName=%E5%B8%A6%E5%B7%A5%E5%85%B7%E6%B8%B8%E6%88%8F%E6%9C%AC%E4%BD%93.part07.rar isBlock=false filePath=%2Fstorage%2Femulated%2F0%2FEnfi%2F%E5%B8%A6%E5%B7%A5%E5%85%B7%E6%B8%B8%E6%88%8F%E6%9C%AC%E4%BD%93.part07.rar isOpenDynamicFile=false threadNum=3 fileLength=728172845
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: TaskRecord.filePath (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:796)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1564)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1433)
        at com.arialyy.aria.orm.DelegateUpdate.insertData(DelegateUpdate.java:135)
        at com.arialyy.aria.orm.DelegateWrapper.insertData(DelegateWrapper.java:179)
        at com.arialyy.aria.orm.DbEntity.insert(DbEntity.java:289)
        at com.arialyy.aria.orm.DbEntity.save(DbEntity.java:263)
        at com.arialyy.aria.core.common.AbsFileer.saveRecord(AbsFileer.java:526)
        at com.arialyy.aria.core.common.AbsFileer.handleBreakpoint(AbsFileer.java:642)
        at com.arialyy.aria.core.common.AbsFileer.startFlow(AbsFileer.java:178)
        at com.arialyy.aria.core.common.AbsFileer.run(AbsFileer.java:187)
        at java.lang.Thread.run(Thread.java:764)

**Comment by AriaLyy** [comment]
使用`3.6.5`以上的版本
