### ISSUE TITLE
数据库bug

### ISSUE THREAD

**Issue by Zvirtuey** [AriaLyy/Aria#442]
## Aria版本
3.6.5

## 什么问题
应用打不开，直接闪退

## 如何复现此问题
刚从老版本升上来就出现这问题，旧版出现问题是这样的

旧版3.4.16日志：
  java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.Set.clear()' on a null object reference
	at com.arialyy.aria.core.manager.ThreadTaskManager.stopTaskThread(ThreadTaskManager.java:98)
	at com.arialyy.aria.core.common.AbsFileer.cancel(AbsFileer.java:258)
	at com.arialyy.aria.core.download.downloader.SimpleDownloadUtil.cancel(SimpleDownloadUtil.java:65)
	at com.arialyy.aria.core.download.DownloadTask.cancel(DownloadTask.java:133)
	at com.arialyy.aria.core.queue.AbsTaskQueue.cancelTask(AbsTaskQueue.java:216)
	at com.arialyy.aria.core.command.normal.AbsNormalCmd.removeTask(AbsNormalCmd.java:119)
	at com.arialyy.aria.core.command.normal.CancelCmd.executeCmd(CancelCmd.java:45)
	at com.arialyy.aria.core.AriaManager.exe(AriaManager.java:218)
	at com.arialyy.aria.core.inf.AbsTarget.cancel(AbsTarget.java:295)
	at com.rzt.internal.fragment.MyFragment$5.onClick(MyFragment.java:253)
	at android.view.View.performClick(View.java:5265)
	at android.view.View$PerformClick.run(View.java:21534)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5737)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

## 控制台日志

新版3.6.5日志：
2019-08-02 18:18:06:
java.lang.RuntimeException: Unable to resume activity {com.rzt.internal/com.rzt.internal.activity.LoginActivity}: android.database.sqlite.SQLiteException: near ",": syntax error (code 1): , while compiling: DELETE FROM ThreadRecord WHERE (key, threadId, endLocation) IN (SELECT key, threadId, endLocation FROM ThreadRecord GROUP BY key, threadId, endLocation HAVING COUNT(*) > 1) AND rowid NOT IN (SELECT MIN(rowid) FROM ThreadRecord GROUP BY key, threadId, endLocation HAVING COUNT(*)> 1)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3318)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3349)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2663)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1492)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5737)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
Caused by: android.database.sqlite.SQLiteException: near ",": syntax error (code 1): , while compiling: DELETE FROM ThreadRecord WHERE (key, threadId, endLocation) IN (SELECT key, threadId, endLocation FROM ThreadRecord GROUP BY key, threadId, endLocation HAVING COUNT(*) > 1) AND rowid NOT IN (SELECT MIN(rowid) FROM ThreadRecord GROUP BY key, threadId, endLocation HAVING COUNT(*)> 1)
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:896)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:507)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1704)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1635)
	at com.arialyy.aria.orm.SqlHelper.delRepeatThreadRecord(SqlHelper.java:248)
	at com.arialyy.aria.orm.SqlHelper.handle360AriaUpdate(SqlHelper.java:287)
	at com.arialyy.aria.orm.SqlHelper.onUpgrade(SqlHelper.java:100)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
	at com.arialyy.aria.orm.SqlHelper.getDb(SqlHelper.java:133)
	at com.arialyy.aria.orm.DelegateWrapper.<init>(DelegateWrapper.java:39)
	at com.arialyy.aria.orm.DelegateWrapper.init(DelegateWrapper.java:47)
	at com.arialyy.aria.core.AriaManager.initDb(AriaManager.java:176)
	at com.arialyy.aria.core.AriaManager.<init>(AriaManager.java:99)
	at com.arialyy.aria.core.AriaManager.getInstance(AriaManager.java:111)
	at com.arialyy.aria.core.Aria.get(Aria.java:118)
	at com.arialyy.aria.core.Aria.download(Aria.java:92)
	at com.rzt.internal.activity.LoginActivity.onResume(LoginActivity.java:295)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1268)
	at android.app.Activity.performResume(Activity.java:6384)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3303)
	... 10 more

**Comment by AriaLyy** [comment]
使用`3.6.6+beta_3`https://github.com/AriaLyy/Aria/issues/426#issuecomment-517157215
