### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=8192; index=8192

### ISSUE THREAD

**Issue by fandeus** [AriaLyy/Aria#446]
## Aria版本
3.6.3

## 什么问题
ArrayIndexOutOfBoundsException

## 控制台日志
java.lang.ArrayIndexOutOfBoundsException: length=8192; index=8192
    at com.android.okhttp.okio.Buffer.writeUtf8(Buffer.java:818)
    at com.android.okhttp.okio.Buffer.writeUtf8(Buffer.java:793)
    at com.android.okhttp.okio.RealBufferedSink.writeUtf8(RealBufferedSink.java:57)
    at com.android.okhttp.internal.http.Http1xStream.writeRequest(Http1xStream.java:167)
    at com.android.okhttp.internal.http.Http1xStream.writeRequestHeaders(Http1xStream.java:123)
    at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:593)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:163)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:207)
    at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:618)
    at java.net.URLConnection.getContentLengthLong(URLConnection.java:490)
    at java.net.URLConnection.getContentLength(URLConnection.java:474)
    at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getContentLength(DelegatingHttpsURLConnection.java:146)
    at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getContentLength(Unknown Source:0)
    at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:112)
    at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:82)
    at java.lang.Thread.run(Thread.java:764)

**Comment by AriaLyy** [comment]
升级到`3.6.6`版本
