### ISSUE TITLE
在fragment注解无效

### ISSUE THREAD

**Issue by zhouzunlai** [AriaLyy/Aria#451]
## Aria版本

    implementation 'com.arialyy.aria:aria-core:3.6.6'
    annotationProcessor 'com.arialyy.aria:aria-compiler:3.6.6'
## 什么问题
我在fragment中使用ftp上传文件，但是通过注解没有收到任何回调信息。
![image](https://user-images.githubusercontent.com/16833138/63084970-0066ce00-bf7f-11e9-936e-09e465a5c509.png)

![image](https://user-images.githubusercontent.com/16833138/63085036-1e343300-bf7f-11e9-9c73-6ab11b5efe21.png)

## 控制台日志
2019-08-15 16:53:03.444 23800-24405/org.smile.meise.demo D/AbsSchedulers: 任务【meicam_1565859112753.mp4】开始重试
2019-08-15 16:53:03.563 23800-24414/org.smile.meise.demo I/AbsFtpInfoThread: D_FTP 服务器不支持开启UTF8编码，尝试使用Aria手动设置的编码
2019-08-15 16:53:08.633 23800-24414/org.smile.meise.demo W/System.err: com.arialyy.aria.exception.AriaIOException: FTP错误信息，code：227，msg：227 Entering Passive Mode (192,168,1,23,109,239)
2019-08-15 16:53:08.633 23800-24414/org.smile.meise.demo W/System.err: connect timed out
2019-08-15 16:53:08.633 23800-24414/org.smile.meise.demo W/System.err:     at com.arialyy.aria.core.common.ftp.AbsFtpInfoThread.run(AbsFtpInfoThread.java:164)
2019-08-15 16:53:08.633 23800-24414/org.smile.meise.demo W/System.err:     at java.lang.Thread.run(Thread.java:761)
2019-08-15 16:53:10.633 23800-24439/org.smile.meise.demo D/AbsSchedulers: 任务【meicam_1565859112753.mp4】开始重试
2019-08-15 16:53:10.737 23800-24454/org.smile.meise.demo I/AbsFtpInfoThread: D_FTP 服务器不支持开启UTF8编码，尝试使用Aria手动设置的编码
2019-08-15 16:53:15.815 23800-24454/org.smile.meise.demo W/System.err: com.arialyy.aria.exception.AriaIOException: FTP错误信息，code：227，msg：227 Entering Passive Mode (192,168,1,23,79,72)
2019-08-15 16:53:15.815 23800-24454/org.smile.meise.demo W/System.err: connect timed out
2019-08-15 16:53:15.815 23800-24454/org.smile.meise.demo W/System.err:     at com.arialyy.aria.core.common.ftp.AbsFtpInfoThread.run(AbsFtpInfoThread.java:164)
2019-08-15 16:53:15.815 23800-24454/org.smile.meise.demo W/System.err:     at java.lang.Thread.run(Thread.java:761)
2019-08-15 16:53:17.816 23800-24493/org.smile.meise.demo D/AbsSchedulers: 任务【meicam_1565859112753.mp4】开始重试
2019-08-15 16:53:17.906 23800-24511/org.smile.meise.demo I/AbsFtpInfoThread: D_FTP 服务器不支持开启UTF8编码，尝试使用Aria手动设置的编码
2019-08-15 16:53:22.986 23800-24511/org.smile.meise.demo W/System.err: com.arialyy.aria.exception.AriaIOException: FTP错误信息，code：227，msg：227 Entering Passive Mode (192,168,1,23,114,47)
2019-08-15 16:53:22.986 23800-24511/org.smile.meise.demo W/System.err: connect timed out
2019-08-15 16:53:22.987 23800-24511/org.smile.meise.demo W/System.err:     at com.arialyy.aria.core.common.ftp.AbsFtpInfoThread.run(AbsFtpInfoThread.java:164)
2019-08-15 16:53:22.991 23800-24511/org.smile.meise.demo W/System.err:     at java.lang.Thread.run(Thread.java:761)
2019-08-15 16:53:24.985 23800-24521/org.smile.meise.demo D/AbsSchedulers: 任务【meicam_1565859112753.mp4】开始重试
2019-08-15 16:53:25.070 23800-24523/org.smile.meise.demo I/AbsFtpInfoThread: D_FTP 服务器不支持开启UTF8编码，尝试使用Aria手动设置的编码
2019-08-15 16:53:30.141 23800-23800/org.smile.meise.demo D/AbsTaskQueue: 从执行池删除任务【meicam_1565859112753.mp4】成功
2019-08-15 16:53:30.142 23800-24523/org.smile.meise.demo W/System.err: com.arialyy.aria.exception.AriaIOException: FTP错误信息，code：227，msg：227 Entering Passive Mode (192,168,1,23,101,179)
2019-08-15 16:53:30.142 23800-24523/org.smile.meise.demo W/System.err: connect timed out
2019-08-15 16:53:30.142 23800-24523/org.smile.meise.demo W/System.err:     at com.arialyy.aria.core.common.ftp.AbsFtpInfoThread.run(AbsFtpInfoThread.java:164)
2019-08-15 16:53:30.143 23800-24523/org.smile.meise.demo W/System.err:     at java.lang.Thread.run(Thread.java:761)
2019-08-15 16:53:30.143 23800-23800/org.smile.meise.demo I/AbsSchedulers: 没有等待中的任务
2019-08-15 16:53:30.144 23800-23800/org.smile.meise.demo I/UploadTask: taskFail=com.arialyy.aria.core.upload.UploadTask@de886f0

**Comment by AriaLyy** [comment]
3.6.5以上版本做了间隔处理 https://github.com/AriaLyy/Aria/issues/427#issuecomment-513618323

**Comment by AriaLyy** [comment]
参考 https://aria.laoyuyu.me/aria_doc/other/annotaion_invalid.html
