### ISSUE TITLE
你好，我在使用ftp上传的时候，出现code：227，msg：227 Entering Passive Mode (0,0,0,0,107,76)这个错误

### ISSUE THREAD

**Issue by zhouzunlai** [AriaLyy/Aria#460]
## Aria版本
3.6.6

## 什么问题
我在使用ftp进行上传的时候出现了com.arialyy.aria.exception.AriaIOException: FTP错误信息，code：227，msg：227 Entering Passive Mode (0,0,0,0,107,76）这个异常！我不知道这个是否确实是mode的问题，如果是的话，是否可以修改一下上传的模式，但是我看是否没有修改的位置！
## 如何复现此问题
 Aria.upload(this).loadFtp(filePath).setUploadUrl("ftp://139.9.154.188:21/meisei/111.mp4").login("ftpuser", "********").start();
调用上传的代码如下
## 控制台日志
rr: failed to connect to localhost/127.0.0.1 (port 29301) from /127.0.0.1 (port 52844) after 5000ms: isConnected failed: ECONNREFUSED (Connection refused)
2019-08-21 16:08:54.231 17391-20759/org.smile.meise.demo W/System.err:     at com.arialyy.aria.core.common.ftp.AbsFtpInfoThread.run(AbsFtpInfoThread.java:164)
2019-08-21 16:08:54.231 17391-20759/org.smile.meise.demo W/System.err:     at java.lang.Thread.run(Thread.java:784)
2019-08-21 16:08:54.243 17391-17391/org.smile.meise.demo W/Thread-59: type=1400 audit(0.0:63456): avc: granted { create } for name="AriaCrash_2019-08-21_16_08_54.log" scontext=u:r:untrusted_app:s0:c168,c257,c512,c768 tcontext=u:object_r:sdcardfs:s0:c168,c257,c512,c768 tclass=file
2019-08-21 16:08:56.234 17391-20761/org.smile.meise.demo D/AbsSchedulers: 任务【meicam_1566374902730.mp4】开始重试
2019-08-21 16:08:56.316 17391-20765/org.smile.meise.demo I/AbsFtpInfoThread: D_FTP 服务器不支持开启UTF8编码，尝试使用Aria手动设置的编码
2019-08-21 16:08:56.398 17391-20765/org.smile.meise.demo W/System.err: com.arialyy.aria.exception.AriaIOException: FTP错误信息，code：227，msg：227 Entering Passive Mode (0,0,0,0,88,40)
2019-08-21 16:08:56.398 17391-20765/org.smile.meise.demo W/System.err: failed to connect to localhost/127.0.0.1 (port 22568) from /127.0.0.1 (port 58064) after 5000ms: isConnected failed: ECONNREFUSED (Connection refused)
2019-08-21 16:08:56.399 17391-20765/org.smile.meise.demo W/System.err:     at com.arialyy.aria.core.common.ftp.AbsFtpInfoThread.run(AbsFtpInfoThread.java:164)
2019-08-21 16:08:56.399 17391-20765/org.smile.meise.demo W/System.err:     at java.lang.Thread.run(Thread.java:784)
2019-08-21 16:08:56.399 17391-17391/org.smile.meise.demo D/AbsTaskQueue: 从执行池删除任务【meicam_1566374902730.mp4】成功
2019-08-21 16:08:56.402 17391-17391/org.smile.meise.demo I/AbsSchedulers: 没有等待中的任务

**Comment by AriaLyy** [comment]
检查下你的服务器配置，ftp中，客户端一般是被动模式

**Comment by zhouzunlai** [comment]
> 检查下你的服务器配置，ftp中，客户端一般是被动模式

是的，我想问的就是 是否可以增加一个设置，让我可以设置为主动模式

**Comment by AriaLyy** [comment]
忘记回复了，3.8版本已经增加了主动模式，现在可以使用最新版本3.8.5，详情见：https://aria.laoyuyu.me/aria_doc/api/ftp_params.html#%E4%B8%89%E3%80%81%E4%B8%BB%E5%8A%A8%E6%A8%A1%E5%BC%8F
