### ISSUE TITLE
下载进度转换抛异常不能强制转换为Long型

### ISSUE THREAD

**Issue by shiguangshuo** [AriaLyy/Aria#463]
## Aria版本
3.6.5

## 什么问题

下载进度转换抛异常不能强制转换为Long型

## 如何复现此问题
无

## 控制台日志
java.lang.ClassCastException: com.arialyy.aria.core.download.downloader.HttpThreadTask cannot be cast to java.lang.Long
	at com.arialyy.aria.core.common.ThreadStateManager.handleMessage(ThreadStateManager.java:105)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:166)
	at com.arialyy.aria.core.common.AbsFileer.startFlow(AbsFileer.java:109)
	at com.arialyy.aria.core.common.AbsFileer.run(AbsFileer.java:116)
	at java.lang.Thread.run(Thread.java:784)

**Comment by AriaLyy** [comment]
设计3.6.6 https://github.com/AriaLyy/Aria/issues/444
