### ISSUE TITLE
java.lang.ClassCastException: com.arialyy.aria.core.download.downloader.HttpThreadTask cannot be cast to java.lang.Long     at com.arialyy.aria.core.common.ThreadStateManager.handleMessage(ThreadStateManager.java:105)     at android.os.Handler.dispatchMessage(Handler.java:104)     at android.os.Looper.loop(Looper.java:166)     at com.arialyy.aria.core.common.AbsFileer.startFlow(AbsFileer.java:109)     at com.arialyy.aria.core.common.AbsFileer.run(AbsFileer.java:116)     at java.lang.Thread.run(Thread.java:784)

### ISSUE THREAD

**Issue by shiguangshuo** [AriaLyy/Aria#465]
## Aria版本
3.6.5

## 什么问题
java.lang.ClassCastException: com.arialyy.aria.core.download.downloader.HttpThreadTask cannot be cast to java.lang.Long
    at com.arialyy.aria.core.common.ThreadStateManager.handleMessage(ThreadStateManager.java:105)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loop(Looper.java:166)
    at com.arialyy.aria.core.common.AbsFileer.startFlow(AbsFileer.java:109)
    at com.arialyy.aria.core.common.AbsFileer.run(AbsFileer.java:116)
    at java.lang.Thread.run(Thread.java:784)

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/issues/444
