### ISSUE TITLE
M3U8视频报错

### ISSUE THREAD

**Issue by NSocket** [AriaLyy/Aria#473]
版本3.6.6

代码
 url="https://cdn.mb33.vip/20190915/VkizE7hq/index.m3u8";
        Aria.download(this)
                .load(url)
                .setFilePath(new File(this.getExternalCacheDir(),"download.m3u8").getAbsolutePath(),true)
                .asM3U8()
                .asVod()
                .setFileSize(9999999)
                .start();

日志
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.m3u8.cache/com.m3u8.cache.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2947)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3082)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1832)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6820)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
        at com.arialyy.aria.core.download.m3u8.M3U8TaskConfig.getBandWidthUrlConverter(M3U8TaskConfig.java:150)
        at com.arialyy.aria.core.download.DNormalConfigHandler.checkM3U8(DNormalConfigHandler.java:131)
        at com.arialyy.aria.core.download.DNormalConfigHandler.checkEntity(DNormalConfigHandler.java:106)
        at com.arialyy.aria.core.download.DownloadTarget.checkEntity(DownloadTarget.java:151)
        at com.arialyy.aria.core.inf.AbsTarget.checkConfig(AbsTarget.java:208)
        at com.arialyy.aria.core.inf.AbsTarget.start(AbsTarget.java:283)
        at com.arialyy.aria.core.common.BaseDelegate.start(BaseDelegate.java:36)
        at com.m3u8.cache.MainActivity.onCreate(MainActivity.java:53)
        at android.app.Activity.performCreate(Activity.java:7224)
        at android.app.Activity.performCreate(Activity.java:7213)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3082) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1832) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:6820)

**Comment by gzy13543479929** [comment]
真巧，我也跟你一个问题，专门下这个框架下载m3u8视频，没想到还有这些问题

**Comment by qq61821191** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
        at com.arialyy.aria.core.download.m3u8.M3U8TaskConfig.getBandWidthUrlConverter(M3U8TaskConfig.java:150)
        at com.arialyy.aria.core.download.DNormalConfigHandler.checkM3U8(DNormalConfigHandler.java:131)
        at com.arialyy.aria.core.download.DNormalConfigHandler.checkEntity(DNormalConfigHandler.java:106)
        at com.arialyy.aria.core.download.DownloadTarget.checkEntity(DownloadTarget.java:151)
        at com.arialyy.aria.core.inf.AbsTarget.checkConfig(AbsTarget.java:208)
        at com.arialyy.aria.core.inf.AbsTarget.start(AbsTarget.java:283)
        at com.arialyy.aria.core.common.BaseDelegate.start(BaseDelegate.java:36)


同样的问题。希望作者早日解决。

**Comment by qq61821191** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
        at com.arialyy.aria.core.download.m3u8.M3U8TaskConfig.getBandWidthUrlConverter(M3U8TaskConfig.java:150)
        at com.arialyy.aria.core.download.DNormalConfigHandler.checkM3U8(DNormalConfigHandler.java:131)
        at com.arialyy.aria.core.download.DNormalConfigHandler.checkEntity(DNormalConfigHandler.java:106)
        at com.arialyy.aria.core.download.DownloadTarget.checkEntity(DownloadTarget.java:151)
        at com.arialyy.aria.core.inf.AbsTarget.checkConfig(AbsTarget.java:208)
        at com.arialyy.aria.core.inf.AbsTarget.start(AbsTarget.java:283)
        at com.arialyy.aria.core.common.BaseDelegate.start(BaseDelegate.java:36)


同样的问题。希望作者早日解决。

**Comment by joefei** [comment]
跑Demo倒是没什么问题，把M3U8下载器单独拎出来用就有这个问题了。
楼上的同志们解决了这个问题了吗？

`    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
        at com.arialyy.aria.core.download.m3u8.M3U8TaskConfig.getMergeHandler(M3U8TaskConfig.java:190)
        at com.arialyy.aria.core.download.m3u8.M3U8VodLoader$VodStateManager.mergeFile(M3U8VodLoader.java:613)
        at com.arialyy.aria.core.download.m3u8.M3U8VodLoader$VodStateManager.handleMessage(M3U8VodLoader.java:548)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at com.arialyy.aria.core.common.AbsFileer.startFlow(AbsFileer.java:109)
        at com.arialyy.aria.core.common.AbsFileer.run(AbsFileer.java:116)
        at java.lang.Thread.run(Thread.java:764)
`

**Comment by joefei** [comment]
解决了。
那几个Handler和Converter貌似是必填的，否则会报空指针。

`setBandWidthUrlConverter(new IBandWidthUrlConverter() {
                            @Override
                            public String convert(String bandWidthUrl) {
                                int index = mUrl.lastIndexOf("/");
                                return mUrl.substring(0, index + 1) + bandWidthUrl;
                            }
                        })
                        .setTsUrlConvert(new IVodTsUrlConverter() {
                            @Override
                            public List<String> convert(String m3u8Url, List<String> tsUrls) {
                                int index = m3u8Url.lastIndexOf("/");
                                String parentUrl = m3u8Url.substring(0, index + 1);
                                List<String> newUrls = new ArrayList<>();
                                for (String url : tsUrls) {
                                    newUrls.add(parentUrl + url);
                                }

                                return newUrls;
                            }
                        }).setMergeHandler(new ITsMergeHandler() {
                    @Override
                    public boolean merge(@Nullable M3U8KeyInfo keyInfo, List<String> tsPath) {
                        ALog.d(TAG, "合并TS....");
                        return false;
                    }
                })`

**Comment by AriaLyy** [comment]
不是这个原因，是WeakReference导致的问题，后面改成SoftReference

**Comment by deepdream88** [comment]
> 不是这个原因，是WeakReference导致的问题，后面改成SoftReference

您好，该问题有临时解决的方案么？

**Comment by NSocket** [comment]
我是自己实现了m3u8缓存

**Comment by AriaLyy** [comment]
3.7.2已修复这个问题
