### ISSUE TITLE
下载的时候数据库报错直接导致程序崩溃

### ISSUE THREAD

**Issue by xicong** [AriaLyy/Aria#475]
## Aria版本
3.6.6

## 什么问题
下载的时候数据库报错

## 如何复现此问题
![image](https://user-images.githubusercontent.com/11675597/64750383-56fa0480-d54b-11e9-9bf8-a15e125aaaf8.png)
偶然出现的，但是当我把程序卸载后重新装的时候又正常了

## 控制台日志
AndroidRuntime: FATAL EXCEPTION: main
    Process: com.a3xh1.medical.knowledge, PID: 26227
    android.database.sqlite.SQLiteException: no such table: TaskRecord (Sqlite code 1 SQLITE_ERROR): , while compiling: SELECT rowid, * FROM TaskRecord WHERE filePath=?, (OS error - 2:No such file or directory)
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:948)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:559)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:603)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:63)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1493)
        at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1427)
        at com.arialyy.aria.orm.DelegateFind.exeNormalDataSql(DelegateFind.java:416)
        at com.arialyy.aria.orm.DelegateFind.findData(DelegateFind.java:331)
        at com.arialyy.aria.orm.DelegateWrapper.findData(DelegateWrapper.java:138)
        at com.arialyy.aria.orm.DbEntity.findFirst(DbEntity.java:174)
        at com.arialyy.aria.core.manager.DTaskWrapperFactory.getEntity(DTaskWrapperFactory.java:79)
        at com.arialyy.aria.core.manager.DTaskWrapperFactory.create(DTaskWrapperFactory.java:56)
        at com.arialyy.aria.core.manager.DTaskWrapperFactory.create(DTaskWrapperFactory.java:29)
        at com.arialyy.aria.core.manager.TaskWrapperManager.getHttpTaskWrapper(TaskWrapperManager.java:84)
        at com.arialyy.aria.core.download.DNormalConfigHandler.initTarget(DNormalConfigHandler.java:62)
        at com.arialyy.aria.core.download.DNormalConfigHandler.<init>(DNormalConfigHandler.java:57)
        at com.arialyy.aria.core.download.DownloadTarget.<init>(DownloadTarget.java:41)
        at com.arialyy.aria.core.download.DownloadReceiver.load(DownloadReceiver.java:80)
        at com.a3xh1.medical.knowledge.modules.video.cache.v2.CacheAdapter$onBindViewHolder$1.onClick(CacheAdapter.kt:91)
        at android.view.View.performClick(View.java:6668)
        at android.view.View.performClickInternal(View.java:6639)
        at android.view.View.access$3100(View.java:794)
        at android.view.View$PerformClick.run(View.java:26200)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7586)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by AriaLyy** [comment]
同样的问题，https://github.com/AriaLyy/Aria/issues/547，使用`3.7.10_pre_4`版本
