### ISSUE TITLE
Kotlin 注释回调未运行

### ISSUE THREAD

**Issue by xz-dev** [AriaLyy/Aria#481]
## Aria版本
3.6.6

## 什么问题
编写 Android 应用，
已添加
<code> implementation 'com.arialyy.aria:aria-core:3.6.6' </code>
<code> kapt 'com.arialyy.aria:aria-compiler:3.6.6' </code>
正常生成 $$DownloadListenerProxy 文件
文件下载时不生效
![源代码](https://user-images.githubusercontent.com/32761048/66188521-04c78180-e6ba-11e9-83d0-6d78bc9b9ac4.png)
![DownloadListenerProxy](https://user-images.githubusercontent.com/32761048/66188534-0b55f900-e6ba-11e9-8847-471947166e2f.png)

## 如何复现此问题
![Android 应用源码](https://github.com/xz-dev/UpgradeAll/blob/master/app/src/main/kotlin/net/xzos/upgradeAll/utils/AriaDownloader.kt#L77-#L101)已开源，你可以尝试下载、运行

## 控制台日志
```
2019-10-04 15:07:54.906 4699-4754/net.xzos.upgradeall W/xzos.upgradeal: Accessing hidden method Landroid/os/storage/StorageManager;->getVolumePaths()[Ljava/lang/String; (light greylist, reflection)
2019-10-04 15:07:54.911 4699-4754/net.xzos.upgradeall W/System.err: java.io.IOException: Permission denied
2019-10-04 15:07:54.911 4699-4754/net.xzos.upgradeall W/System.err:     at java.io.UnixFileSystem.createFileExclusively0(Native Method)
2019-10-04 15:07:54.911 4699-4754/net.xzos.upgradeall W/System.err:     at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
2019-10-04 15:07:54.911 4699-4754/net.xzos.upgradeall W/System.err:     at java.io.File.createNewFile(File.java:1008)
2019-10-04 15:07:54.911 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
2019-10-04 15:07:54.911 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
2019-10-04 15:07:54.911 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
2019-10-04 15:07:54.911 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:206)
2019-10-04 15:07:54.913 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:123)
2019-10-04 15:07:54.913 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:85)
2019-10-04 15:07:54.913 4699-4754/net.xzos.upgradeall W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-10-04 15:07:54.916 4699-4754/net.xzos.upgradeall W/System.err: java.io.IOException: Permission denied
2019-10-04 15:07:54.916 4699-4754/net.xzos.upgradeall W/System.err:     at java.io.UnixFileSystem.createFileExclusively0(Native Method)
2019-10-04 15:07:54.916 4699-4754/net.xzos.upgradeall W/System.err:     at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
2019-10-04 15:07:54.916 4699-4754/net.xzos.upgradeall W/System.err:     at java.io.File.createNewFile(File.java:1008)
2019-10-04 15:07:54.916 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
2019-10-04 15:07:54.916 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.util.FileUtil.getStorageDirectories(FileUtil.java:317)
2019-10-04 15:07:54.916 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:177)
2019-10-04 15:07:54.916 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:206)
2019-10-04 15:07:54.916 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:123)
2019-10-04 15:07:54.916 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:85)
2019-10-04 15:07:54.918 4699-4754/net.xzos.upgradeall W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-10-04 15:07:54.921 4699-4754/net.xzos.upgradeall W/HttpFileInfoThread: Content-Disposition对于端字段为空，使用服务器端文件名失败
2019-10-04 15:07:54.921 4699-4754/net.xzos.upgradeall D/HttpFileInfoThread: 30x跳转，新url为【http://dl-cdn.coolapkmarket.com/down/apk_upload/2019/0919/add26db7a71a030e7304320e24e65fbe-0-o_1dl41so911js01los1e4e3pc1j0m6-uid-408649.apk?_upt=65f2f51b1570174678】
2019-10-04 15:07:54.924 4699-4754/net.xzos.upgradeall W/System: Ignoring header Cookie because its value was null.
2019-10-04 15:07:55.051 4699-4754/net.xzos.upgradeall W/System.err: java.io.IOException: Permission denied
2019-10-04 15:07:55.051 4699-4754/net.xzos.upgradeall W/System.err:     at java.io.UnixFileSystem.createFileExclusively0(Native Method)
2019-10-04 15:07:55.054 4699-4754/net.xzos.upgradeall W/System.err:     at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
2019-10-04 15:07:55.054 4699-4754/net.xzos.upgradeall W/System.err:     at java.io.File.createNewFile(File.java:1008)
2019-10-04 15:07:55.054 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
2019-10-04 15:07:55.054 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.util.FileUtil.getVolumeList(FileUtil.java:210)
2019-10-04 15:07:55.056 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:175)
2019-10-04 15:07:55.057 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:206)
2019-10-04 15:07:55.057 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:123)
2019-10-04 15:07:55.058 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleUrlReTurn(HttpFileInfoThread.java:315)
2019-10-04 15:07:55.059 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:213)
2019-10-04 15:07:55.062 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:85)
2019-10-04 15:07:55.062 4699-4754/net.xzos.upgradeall W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-10-04 15:07:55.064 4699-4754/net.xzos.upgradeall W/System.err: java.io.IOException: Permission denied
2019-10-04 15:07:55.064 4699-4754/net.xzos.upgradeall W/System.err:     at java.io.UnixFileSystem.createFileExclusively0(Native Method)
2019-10-04 15:07:55.064 4699-4754/net.xzos.upgradeall W/System.err:     at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
2019-10-04 15:07:55.065 4699-4754/net.xzos.upgradeall W/System.err:     at java.io.File.createNewFile(File.java:1008)
2019-10-04 15:07:55.066 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:240)
2019-10-04 15:07:55.068 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.util.FileUtil.getStorageDirectories(FileUtil.java:317)
2019-10-04 15:07:55.068 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.util.FileUtil.getSDPathList(FileUtil.java:177)
2019-10-04 15:07:55.068 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.util.CommonUtil.checkSDMemorySpace(CommonUtil.java:206)
2019-10-04 15:07:55.068 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:123)
2019-10-04 15:07:55.069 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleUrlReTurn(HttpFileInfoThread.java:315)
2019-10-04 15:07:55.071 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.handleConnect(HttpFileInfoThread.java:213)
2019-10-04 15:07:55.071 4699-4754/net.xzos.upgradeall W/System.err:     at com.arialyy.aria.core.download.downloader.HttpFileInfoThread.run(HttpFileInfoThread.java:85)
2019-10-04 15:07:55.071 4699-4754/net.xzos.upgradeall W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-10-04 15:07:55.075 4699-4754/net.xzos.upgradeall W/HttpFileInfoThread: Content-Disposition对于端字段为空，使用服务器端文件名失败
2019-10-04 15:07:55.075 4699-4754/net.xzos.upgradeall D/HttpFileInfoThread: 长度不一致，任务为新任务
2019-10-04 15:07:55.088 4699-4763/net.xzos.upgradeall D/RecordHandler: 保存记录，线程记录数：3
2019-10-04 15:07:55.092 4699-4763/net.xzos.upgradeall D/Downloader: 任务【12.11.10.9.8.7.6.5.4.3.2.1.0.9.6】线程__0__恢复任务
2019-10-04 15:07:55.094 4699-4763/net.xzos.upgradeall D/Downloader: 任务【12.11.10.9.8.7.6.5.4.3.2.1.0.9.6】线程__1__恢复任务
2019-10-04 15:07:55.094 4699-4763/net.xzos.upgradeall D/Downloader: 任务【12.11.10.9.8.7.6.5.4.3.2.1.0.9.6】线程__2__恢复任务
2019-10-04 15:07:55.100 4699-4763/net.xzos.upgradeall D/Downloader: 启动定时器
2019-10-04 15:07:55.102 4699-4764/net.xzos.upgradeall D/HttpThreadTask: 任务【12.11.10.9.8.7.6.5.4.3.2.1.0.9.6.0.part】线程__0__开始下载【开始位置 : 0，结束位置：9650923】
2019-10-04 15:07:55.102 4699-4765/net.xzos.upgradeall D/HttpThreadTask: 任务【12.11.10.9.8.7.6.5.4.3.2.1.0.9.6.1.part】线程__1__开始下载【开始位置 : 9650923，结束位置：19301846】
2019-10-04 15:07:55.103 4699-4766/net.xzos.upgradeall D/HttpThreadTask: 任务【12.11.10.9.8.7.6.5.4.3.2.1.0.9.6.2.part】线程__2__开始下载【开始位置 : 19301846，结束位置：28952771】
2019-10-04 15:07:57.367 4699-4764/net.xzos.upgradeall I/AbsThreadTask: 任务【12.11.10.9.8.7.6.5.4.3.2.1.0.9.6.0.part】完成
2019-10-04 15:07:59.692 4699-4766/net.xzos.upgradeall I/AbsThreadTask: 任务【12.11.10.9.8.7.6.5.4.3.2.1.0.9.6.2.part】完成
2019-10-04 15:08:00.303 4699-4765/net.xzos.upgradeall I/AbsThreadTask: 任务【12.11.10.9.8.7.6.5.4.3.2.1.0.9.6.1.part】完成
2019-10-04 15:08:00.304 4699-4763/net.xzos.upgradeall D/ThreadTaskStateManager: isComplete, completeNum = 3
2019-10-04 15:08:00.438 4699-4699/net.xzos.upgradeall D/AbsTaskQueue: 从执行池删除任务【12.11.10.9.8.7.6.5.4.3.2.1.0.9.6】成功
2019-10-04 15:08:00.438 4699-4699/net.xzos.upgradeall D/AbsSchedulers: 任务【12.11.10.9.8.7.6.5.4.3.2.1.0.9.6】处理完成
2019-10-04 15:08:00.439 4699-4699/net.xzos.upgradeall I/AbsSchedulers: 没有等待中的任务
2019-10-04 15:08:01.115 4699-4767/net.xzos.upgradeall D/Downloader: isComplete = true; isFail = false; isRunning = true; isBreak = false
```

**Comment by xz-dev** [comment]
在 <code>init</code> 代码块中加入 <code>Aria.download(this).register()</code> 后回调正常
