### ISSUE TITLE
多任务下载暂停后恢复闪退

### ISSUE THREAD

**Issue by renjiazhuo321** [AriaLyy/Aria#492]
## Aria版本

3.72
## 什么问题

多任务下载点击暂停，然后点击恢复直接闪退，直接下载源代码运行也是这样

## 如何复现此问题
点击http下载，点击多任务下载，随便下载两个，然后点击下载列表，点击暂停，然后点击恢复
直接闪退
手机：小米6X，华为P30都有，查看文件管理器地址，是存在下载的文件

## 控制台日志
2019-10-30 15:38:46.001 3278-3850/? I/TrafficManageService: mina mTrafficStatsReceiver onReceive
2019-10-30 15:38:46.402 23292-23292/? W/TcmReceiver: type=1400 audit(0.0:2708): avc: denied { write } for name="tcm" dev="tmpfs" ino=23415 scontext=u:r:mediaprovider:s0:c512,c768 tcontext=u:object_r:dpmtcm_socket:s0 tclass=sock_file permissive=0
2019-10-30 15:38:46.539 2154-2299/? D/NtpTrustedTime: currentTimeMillis() cache hit
2019-10-30 15:38:46.579 2154-2299/? D/NtpTrustedTime: currentTimeMillis() cache hit
2019-10-30 15:38:46.582 3278-3850/? I/TrafficManageService: mina mTrafficStatsReceiver onReceive
2019-10-30 15:38:47.063 2154-2299/? D/NtpTrustedTime: currentTimeMillis() cache hit
2019-10-30 15:38:47.104 2154-2299/? D/NtpTrustedTime: currentTimeMillis() cache hit
2019-10-30 15:38:47.106 3278-3850/? I/TrafficManageService: mina mTrafficStatsReceiver onReceive
2019-10-30 15:38:47.412 23292-23292/? W/TcmReceiver: type=1400 audit(0.0:2709): avc: denied { write } for name="tcm" dev="tmpfs" ino=23415 scontext=u:r:mediaprovider:s0:c512,c768 tcontext=u:object_r:dpmtcm_socket:s0 tclass=sock_file permissive=0
2019-10-30 15:38:47.602 2154-2299/? D/NtpTrustedTime: currentTimeMillis() cache hit
2019-10-30 15:38:47.637 2154-2299/? D/NtpTrustedTime: currentTimeMillis() cache hit
2019-10-30 15:38:47.640 3278-3850/? I/TrafficManageService: mina mTrafficStatsReceiver onReceive
2019-10-30 15:38:48.174 2154-2299/? D/NtpTrustedTime: currentTimeMillis() cache hit
2019-10-30 15:38:48.207 2154-2299/? D/NtpTrustedTime: currentTimeMillis() cache hit
2019-10-30 15:38:48.211 3278-3850/? I/TrafficManageService: mina mTrafficStatsReceiver onReceive
2019-10-30 15:38:48.422 23292-23292/? W/TcmReceiver: type=1400 audit(0.0:2710): avc: denied { write } for name="tcm" dev="tmpfs" ino=23415 scontext=u:r:mediaprovider:s0:c512,c768 tcontext=u:object_r:dpmtcm_socket:s0 tclass=sock_file permissive=0
2019-10-30 15:38:48.705 2154-2299/? D/NtpTrustedTime: currentTimeMillis() cache hit
2019-10-30 15:38:48.740 2154-2299/? D/NtpTrustedTime: currentTimeMillis() cache hit
2019-10-30 15:38:48.743 3278-3850/? I/TrafficManageService: mina mTrafficStatsReceiver onReceive
2019-10-30 15:38:48.862 2154-2175/? W/MiuiGesturePointerEventListener: onActionDown end: mGestureStatus = 0
2019-10-30 15:38:48.878 864-885/? I/mmid: select timeout: wait for receiving msg
2019-10-30 15:38:48.952 2154-2175/? W/MiuiGesturePointerEventListener: onActionUp: mGestureStatus = 0  mTailDistance = 0.0  mIsEnterRecents = false
2019-10-30 15:38:49.051 23572-23957/com.stereo.hythreevideos D/AbsThreadTask: 任务【王者荣耀】thread__0__停止【当前线程停止位置：5438773】
2019-10-30 15:38:49.060 23572-23579/com.stereo.hythreevideos I/zygote64: Do full code cache collection, code=1004KB, data=667KB
2019-10-30 15:38:49.065 23572-23579/com.stereo.hythreevideos I/zygote64: After code cache collection, code=1000KB, data=588KB
2019-10-30 15:38:49.067 23572-23957/com.stereo.hythreevideos D/AbsThreadTask: 任务【王者荣耀】thread__1__停止【当前线程停止位置：467164431】
2019-10-30 15:38:49.075 23572-23957/com.stereo.hythreevideos D/AbsThreadTask: 任务【王者荣耀】thread__2__停止【当前线程停止位置：930266352】
2019-10-30 15:38:49.093 23572-23572/com.stereo.hythreevideos D/AbsSchedulers: 停止任务【王者荣耀】成功，尝试开始下一任务
2019-10-30 15:38:49.373 2154-2299/? D/NtpTrustedTime: currentTimeMillis() cache hit
2019-10-30 15:38:49.408 2154-2299/? D/NtpTrustedTime: currentTimeMillis() cache hit
2019-10-30 15:38:49.411 3278-3850/? I/TrafficManageService: mina mTrafficStatsReceiver onReceive
2019-10-30 15:38:49.422 23292-23292/? W/TcmReceiver: type=1400 audit(0.0:2711): avc: denied { write } for name="tcm" dev="tmpfs" ino=23415 scontext=u:r:mediaprovider:s0:c512,c768 tcontext=u:object_r:dpmtcm_socket:s0 tclass=sock_file permissive=0
2019-10-30 15:38:49.979 2154-2299/? D/NtpTrustedTime: currentTimeMillis() cache hit
2019-10-30 15:38:50.009 2154-2299/? D/NtpTrustedTime: currentTimeMillis() cache hit
2019-10-30 15:38:50.012 3278-3850/? I/TrafficManageService: mina mTrafficStatsReceiver onReceive
2019-10-30 15:38:50.432 23292-23292/? W/TcmReceiver: type=1400 audit(0.0:2712): avc: denied { write } for name="tcm" dev="tmpfs" ino=23415 scontext=u:r:mediaprovider:s0:c512,c768 tcontext=u:object_r:dpmtcm_socket:s0 tclass=sock_file permissive=0
2019-10-30 15:38:50.619 2154-2299/? D/NtpTrustedTime: currentTimeMillis() cache hit
2019-10-30 15:38:50.669 2154-2299/? D/NtpTrustedTime: currentTimeMillis() cache hit
2019-10-30 15:38:50.673 3278-3850/? I/TrafficManageService: mina mTrafficStatsReceiver onReceive
2019-10-30 15:38:51.200 2154-2299/? D/NtpTrustedTime: currentTimeMillis() cache hit
2019-10-30 15:38:51.227 2154-2299/? D/NtpTrustedTime: currentTimeMillis() cache hit
2019-10-30 15:38:51.230 3278-3850/? I/TrafficManageService: mina mTrafficStatsReceiver onReceive
2019-10-30 15:38:51.378 2154-2175/? W/MiuiGesturePointerEventListener: onActionDown end: mGestureStatus = 0
2019-10-30 15:38:51.442 23292-23292/? W/TcmReceiver: type=1400 audit(0.0:2713): avc: denied { write } for name="tcm" dev="tmpfs" ino=23415 scontext=u:r:mediaprovider:s0:c512,c768 tcontext=u:object_r:dpmtcm_socket:s0 tclass=sock_file permissive=0
2019-10-30 15:38:51.476 2154-2175/? W/MiuiGesturePointerEventListener: onActionUp: mGestureStatus = 0  mTailDistance = 0.0  mIsEnterRecents = false
2019-10-30 15:38:51.507 23572-23572/com.stereo.hythreevideos E/CheckDEntityUtil: 下载失败，文件保存路径为null
2019-10-30 15:38:51.513 23572-23572/com.stereo.hythreevideos D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2019-10-30 15:38:51.516 23572-23572/com.stereo.hythreevideos E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.stereo.hythreevideos, PID: 23572
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.arialyy.aria.core.download.DownloadEntity com.arialyy.aria.core.task.DownloadTask.getEntity()' on a null object reference
        at com.stereo.hythreevideos.activity.MultiDownloadActivity.taskFail(MultiDownloadActivity.java:118)
        at com.stereo.hythreevideos.activity.MultiDownloadActivity$$DownloadListenerProxy.onTaskFail(MultiDownloadActivity$$DownloadListenerProxy.java:55)
        at com.stereo.hythreevideos.activity.MultiDownloadActivity$$DownloadListenerProxy.onTaskFail(MultiDownloadActivity$$DownloadListenerProxy.java:12)
        at com.arialyy.aria.core.scheduler.TaskSchedulers.normalTaskCallback(TaskSchedulers.java:460)
        at com.arialyy.aria.core.scheduler.TaskSchedulers.handlePreFailTask(TaskSchedulers.java:384)
        at com.arialyy.aria.core.scheduler.TaskSchedulers.handleMessage(TaskSchedulers.java:174)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6635)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by AriaLyy** [comment]
这是activity中的崩溃代码，onFail回调有可能会出现实体为空的现象，因为在某些错误下，如：路径错误、url错误，会直接回调并不会创建人刷，所以在onFail中，请先判断task是否为空

**Comment by renjiazhuo321** [comment]
好的，谢谢，我在恢复下载的时候修改为id，不是url就好了
