### ISSUE TITLE
给的demo中，多任务下载，点击崩溃

### ISSUE THREAD

**Issue by cugkuan** [AriaLyy/Aria#506]
## Aria版本

3.7.4
## 什么问题

demo 中多任务点击下载就崩溃

## 控制台日志

2019-11-07 10:16:05.722 10665-10665/com.arialyy.simple E/SQLiteDatabase: Error inserting urls=http%3A%2F%2Fhzdown.muzhiwan.com%2F2017%2F05%2F08%2Fnl.noio.kingdom_59104935e56f0.apk%24%24http%3A%2F%2Fhzdown.muzhiwan.com%2F2017%2F09%2F05%2Fcom.mir.iphone.empire83jie.mzw_59ae6d5a3638d.apk%24%24 alias=%E4%BB%BB%E5%8A%A1%E7%BB%84_1 stopTime=0 isComplete=false groupHash=aec7b62fea2be9403c0f8dea83515baf fileSize=0 state=3 currentProgress=0 percent=0 dirPath=%2Fstorage%2Femulated%2F0%2FDownload%2F%E4%BB%BB%E5%8A%A1%E7%BB%84_1 completeTime=0
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: DownloadGroupEntity.groupHash (code 2067)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1474)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1343)
        at com.arialyy.aria.orm.DelegateUpdate.insertData(DelegateUpdate.java:136)
        at com.arialyy.aria.orm.DelegateWrapper.insertData(DelegateWrapper.java:182)
        at com.arialyy.aria.orm.DbEntity.insert(DbEntity.java:293)
        at com.arialyy.aria.orm.DbEntity.save(DbEntity.java:267)
        at com.arialyy.aria.core.download.CheckDGEntityUtil.saveEntity(CheckDGEntityUtil.java:156)
        at com.arialyy.aria.core.download.CheckDGEntityUtil.checkEntity(CheckDGEntityUtil.java:151)
        at com.arialyy.aria.core.common.controller.FeatureController.checkEntity(FeatureController.java:175)
        at com.arialyy.aria.core.common.controller.FeatureController.checkConfig(FeatureController.java:117)
        at com.arialyy.aria.core.common.controller.BuilderController.create(BuilderController.java:53)
        at com.arialyy.aria.core.common.AbsBuilderTarget.create(AbsBuilderTarget.java:54)
        at com.arialyy.simple.core.download.mutil.FileListAdapter$1.onClick(FileListAdapter.java:77)
        at android.view.View.performClick(View.java:5647)
        at android.view.View$PerformClick.run(View.java:22465)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6238)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by AriaLyy** [comment]
3.7.5 已经修复了这个问题
