### ISSUE TITLE
任务组下载，崩溃

### ISSUE THREAD

**Issue by cugkuan** [AriaLyy/Aria#508]
## Aria版本
3.7.4

## 控制台日志

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.arialyy.aria.http.HttpTaskOption.setFileLenAdapter(com.arialyy.aria.core.processor.IHttpFileLenAdapter)' on a null object reference
        at com.arialyy.aria.http.download.DGroupLoaderUtil.cloneHeader(DGroupLoaderUtil.java:185)
        at com.arialyy.aria.http.download.DGroupLoaderUtil.access$100(DGroupLoaderUtil.java:43)
        at com.arialyy.aria.http.download.DGroupLoaderUtil$1.run(DGroupLoaderUtil.java:113)
        at java.lang.Thread.run(Thread.java:760)

**Comment by AriaLyy** [comment]
3.7.5 已经修复了这个问题
