### ISSUE TITLE
 您好，两个页面都是用ftp上传，来回跳转出现问题

### ISSUE THREAD

**Issue by gjk666** [AriaLyy/Aria#533]
W/ResumeThread: 任务已存在
W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
        at java.util.regex.Matcher.reset(Matcher.java:995)
        at java.util.regex.Matcher.<init>(Matcher.java:174)
        at java.util.regex.Pattern.matcher(Pattern.java:1006)
        at com.arialyy.aria.ftp.AbsFtpInfoThread.createFtpClient(AbsFtpInfoThread.java:199)
W/System.err:     at com.arialyy.aria.ftp.AbsFtpInfoThread.run(AbsFtpInfoThread.java:90)

**Comment by AriaLyy** [comment]
使用`3.7.8-pre-3`看看呢

**Comment by gjk666** [comment]
可以啦大佬

**Comment by gjk666** [comment]
大佬是不是后台开啦append权限断点续传就自动有啦

**Comment by AriaLyy** [comment]
是的

**Comment by gjk666** [comment]
大佬给您写啦个新的session
