### ISSUE TITLE
当我多次下载任务的时候，以前已经下好了的任务重新进入缓冲队列。

### ISSUE THREAD

**Issue by cblsyp** [AriaLyy/Aria#535]
当多次重复进入一个下载页面的时候，以前下好了的任务重新进入缓冲队列。

log:

handlerUri: 即将加密的url  :https://fangao.qfxmj.com/video/20190917/8682b36ee96a42c891602dfb6b871758/cloudv-transfer/55555555r5881r445556q165prs6o2q8_78f1c7ccbc3b48faab9cb0e5d52a7b18_0_4.m3u8
2019-11-25 19:08:35.260 17537-17537/com.piglet I/chen debug: getPhpSD_Time2: 1574680115260
2019-11-25 19:08:35.266 17537-17537/com.piglet W/RecordUtil: 修改任务记录失败，新文件路径和旧文件路径一致
2019-11-25 19:08:35.266 17537-17537/com.piglet I/CheckDEntityUtil: 将任务重命名为：0cb03ba486634b0eecd2d1395d5a5efc.ts
2019-11-25 19:08:35.273 17537-20441/com.piglet D/BaseCachePool: 任务【0cb03ba486634b0eecd2d1395d5a5efc.ts】进入缓存队列成功
2019-11-25 19:08:35.273 17537-20441/com.piglet D/StartCmd: 开始新任务, 任务状态：3
2019-11-25 19:08:35.273 17537-20441/com.piglet D/BaseExecutePool: 任务【0cb03ba486634b0eecd2d1395d5a5efc.ts】进入执行队列成功
2019-11-25 19:08:35.280 17537-20442/com.piglet I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-11-25 19:08:35.280 17537-20442/com.piglet I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-11-25 19:08:35.299 17537-20443/com.piglet D/BaseCachePool: 任务【949ef8711a630af711c100e96b93c835.ts】进入缓存队列成功
2019-11-25 19:08:35.299 17537-20443/com.piglet D/BaseExecutePool: 任务【949ef8711a630af711c100e96b93c835.ts】进入执行队列成功
2019-11-25 19:08:35.303 17537-20443/com.piglet D/BaseCachePool: 任务【729265649ac57fa7f54693350751bf87.ts】进入缓存队列成功
2019-11-25 19:08:35.303 17537-20443/com.piglet D/BaseExecutePool: 任务【729265649ac57fa7f54693350751bf87.ts】进入执行队列成功
2019-11-25 19:08:35.304 17537-20446/com.piglet I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-11-25 19:08:35.304 17537-20446/com.piglet I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-11-25 19:08:35.311 17537-20443/com.piglet D/BaseCachePool: 任务【9e6cc40b8a108b93c11deb3928c1c38e.ts】进入缓存队列成功
2019-11-25 19:08:35.312 17537-20443/com.piglet W/ResumeThread: 任务已存在
2019-11-25 19:08:35.312 17537-20447/com.piglet I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-11-25 19:08:35.312 17537-20447/com.piglet I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2019-11-25 19:08:35.399 17537-20446/com.piglet W/System.err: com.arialyy.aria.exception.M3U8Exception: M3U8 Exception:不支持的响应，code: 403
2019-11-25 19:08:35.399 17537-20446/com.piglet W/System.err:     at com.arialyy.aria.m3u8.M3U8InfoThread.failDownload(M3U8InfoThread.java:339)
2019-11-25 19:08:35.399 17537-20446/com.piglet W/System.err:     at com.arialyy.aria.m3u8.M3U8InfoThread.handleConnect(M3U8InfoThread.java:206)
2019-11-25 19:08:35.399 17537-20446/com.piglet W/System.err:     at com.arialyy.aria.m3u8.M3U8InfoThread.run(M3U8InfoThread.java:100)
2019-11-25 19:08:35.399 17537-20446/com.piglet W/System.err:     at java.lang.Thread.run(Thread.java:

代码：
 /**
     *
     */
    @RequiresApi(api = Build.VERSION_CODES.O)
    private void downloadM3U8(@Nullable String taskUrl, String taskFilePath, long size, String dataExtraParams) {
        Log.i(TAG, "downloadM3U8: 初始化下载的任务");
       
    
        File file = new File(path_File, taskFilePath);
        if (!file.exists()) {
            try {
                file.createNewFile();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        String file_path = file.toPath().toString();
        String url_path = handlerUri(taskUrl);
        M3U8VodOption option = initOptions(taskUrl, size);
        Log.i(TAG, "下载得地址：  downloadM3U8: file_path:  " + file_path);
        long taskId = Aria.download(this)
                .load(url_path)
                .setExtendField(dataParams)
                .setFilePath(file_path, true)
                .m3u8VodOption(option)
                .create();

    }
path_File  是一个常量 ，/RecordUtil: 修改任务记录失败，新文件路径和旧文件路径一致  。
/RecordUtil: 修改任务记录失败，新文件路径和旧文件路径一致  想知道这个警告是什么意思。

**Comment by AriaLyy** [comment]
path_File 是ts切片路径，那个警告不需要管

**Comment by cblsyp** [comment]
上面的问题还是没有解决。大佬有时间看一下。主要就是在有一些任务下载好了之后，下一次会重现进入缓冲队列的问题，群里有人貌似也有相同的问题。

**Comment by AriaLyy** [comment]
`3.7.8-pre-3`已经修改了这个问题
