### ISSUE TITLE
3.5.1升级3.7.9数据库报错，SQLiteException

### ISSUE THREAD

**Issue by kieferHuan** [AriaLyy/Aria#547]
## 版本
* 框架版本
3.7.9
* 系统版本
6.0.1
## 错误日志
android.database.sqlite.SQLiteException: (no such column: DownloadGroupEntity.percent (code 1): , while compiling: SELECT DownloadGroupEntity.rowid AS prowid,DownloadGroupEntity.completeTime AS pcompleteTime,DownloadGroupEntity.convertFileSize AS pconvertFileSize,DownloadGroupEntity.currentProg
at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1255)
at com.arialyy.aria.orm.DelegateFind.exeRelationSql(61)
at com.arialyy.aria.orm.DelegateFind.findRelationData(1)
at com.arialyy.aria.orm.DelegateWrapper.findRelationData(1)
at com.arialyy.aria.orm.DbEntity.findRelationData(1)
at com.arialyy.aria.core.download.DownloadReceiver.getGroupTaskList(1)
at com.arialyy.aria.core.download.DownloadReceiver.getTotalTaskList(3)
at com.ruoshui.ai.ui.fragment.DownloadedFragment.k(3)
at com.ruoshui.ai.ui.fragment.BaseFragment.onCreateView(7)
at android.app.Fragment.performCreateView(Fragment.java:2220)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:981)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1156)
at android.app.BackStackRecord.run(BackStackRecord.java:793)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1551)
at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
at androidx.legacy.app.b.finishUpdate(4)
at androidx.viewpager.widget.ViewPager.populate(51)
at androidx.viewpager.widget.ViewPager.populate(1)
at androidx.viewpager.widget.ViewPager.onMeasure(25)
at android.view.View.measure(View.java:18831)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5990)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
at android.view.View.measure(View.java:18831)
at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
at android.view.View.measure(View.java:18831)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5990)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at androidx.appcompat.widget.ContentFrameLayout.onMeasure(21)
at android.view.View.measure(View.java:18831)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5990)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
at android.view.View.measure(View.java:18831)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5990)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:18831)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5990)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
at android.view.View.measure(View.java:18831)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5990)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2692)
at android.view.View.measure(View.java:18831)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2233)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1318)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1554)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1209)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6330)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:862)
at android.view.Choreographer.doCallbacks(Choreographer.java:674)
at android.view.Choreographer.doFrame(Choreographer.java:610)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:848)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:179)
at android.app.ActivityThread.main(ActivityThread.java:5769)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)

## 重现步骤

1.3.5.1下载文件
2.升级aria到3.7.9
3.打开报错

**Comment by AriaLyy** [comment]
使用`3.7.10_pre_4`版本

**Comment by kieferHuan** [comment]
好的 收到！ 谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lyy"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月2日(星期一) 晚上7:38
收件人:&nbsp;"AriaLyy/Aria"<Aria@noreply.github.com&gt;;
抄送:&nbsp;"桓"<281425219@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AriaLyy/Aria] 3.5.1升级3.7.9数据库报错，SQLiteException (#547)




使用3.7.10_pre_4版本
