### ISSUE TITLE
单任务下载失败，没有回调，downloadEntity状态为4

### ISSUE THREAD

**Issue by 2455429680** [AriaLyy/Aria#553]
## 版本
* 框架版本
3.7.10
* 系统版本
7.1.1
## 错误日志

com.arialyy.aria.exception.AriaIOException: 文件下载失败，savePath: 、, url: 
2019-12-05 19:45:05.914 27772-27925/com.feioou.deliprint.deliprint W/System.err: timeout
2019-12-05 19:45:05.914 27772-27925/com.feioou.deliprint.deliprint W/System.err:     at com.arialyy.aria.http.download.HttpDThreadTaskAdapter.readDynamicFile(HttpDThreadTaskAdapter.java:226)
2019-12-05 19:45:05.914 27772-27925/com.feioou.deliprint.deliprint W/System.err:     at com.arialyy.aria.http.download.HttpDThreadTaskAdapter.handlerThreadTask(HttpDThreadTaskAdapter.java:108)
2019-12-05 19:45:05.914 27772-27925/com.feioou.deliprint.deliprint W/System.err:     at com.arialyy.aria.core.task.AbsThreadTaskAdapter.call(AbsThreadTaskAdapter.java:54)
2019-12-05 19:45:05.914 27772-27925/com.feioou.deliprint.deliprint W/System.err:     at com.arialyy.aria.core.task.ThreadTask.call(ThreadTask.java:486)
2019-12-05 19:45:05.914 27772-27925/com.feioou.deliprint.deliprint W/System.err:     at com.arialyy.aria.core.task.ThreadTask.call(ThreadTask.java:48)
2019-12-05 19:45:05.914 27772-27925/com.feioou.deliprint.deliprint W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
2019-12-05 19:45:05.914 27772-27925/com.feioou.deliprint.deliprint W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2019-12-05 19:45:05.914 27772-27925/com.feioou.deliprint.deliprint W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2019-12-05 19:45:05.914 27772-27925/com.feioou.deliprint.deliprint W/System.err:     at java.lang.Thread.run(Thread.java:761)

## 重现步骤

1.多个单任务同时下载，部分下载失败，但是没有回调，失败后未完成列表中DownloadEntity state仍为4，但是可以通过resume继续下载

**Comment by 2455429680** [comment]
杀掉进程重新进入后，state为刷新为2
