### ISSUE TITLE
组任务下载问题

### ISSUE THREAD

**Issue by pz-bottle** [AriaLyy/Aria#555]
## 版本
* 框架版本
3.7.10
* 系统版本
Android7.0
## 错误日志

12-07 15:50:20.634 12769-12769/com.xp.xyz W/System.err: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: DownloadGroupEntity.groupHash (code 2067)
12-07 15:50:20.634 12769-12769/com.xp.xyz W/System.err:     at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
12-07 15:50:20.634 12769-12769/com.xp.xyz W/System.err:     at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:732)
12-07 15:50:20.634 12769-12769/com.xp.xyz W/System.err:     at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
12-07 15:50:20.634 12769-12769/com.xp.xyz W/System.err:     at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
12-07 15:50:20.634 12769-12769/com.xp.xyz W/System.err:     at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1576)
12-07 15:50:20.634 12769-12769/com.xp.xyz W/System.err:     at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1522)
12-07 15:50:20.634 12769-12769/com.xp.xyz W/System.err:     at com.arialyy.aria.orm.DelegateUpdate.updateData(DelegateUpdate.java:63)
12-07 15:50:20.635 12769-12769/com.xp.xyz W/System.err:     at com.arialyy.aria.orm.DelegateWrapper.updateData(DelegateWrapper.java:117)
12-07 15:50:20.635 12769-12769/com.xp.xyz W/System.err:     at com.arialyy.aria.orm.DbEntity.update(DbEntity.java:256)
12-07 15:50:20.635 12769-12769/com.xp.xyz W/System.err:     at com.arialyy.aria.orm.DbEntity.save(DbEntity.java:265)
12-07 15:50:20.635 12769-12769/com.xp.xyz W/System.err:     at com.arialyy.aria.core.download.CheckDGEntityUtil.saveEntity(CheckDGEntityUtil.java:155)
12-07 15:50:20.635 12769-12769/com.xp.xyz W/System.err:     at com.arialyy.aria.core.download.CheckDGEntityUtil.checkEntity(CheckDGEntityUtil.java:150)
12-07 15:50:20.635 12769-12769/com.xp.xyz W/System.err:     at com.arialyy.aria.core.common.controller.FeatureController.checkEntity(FeatureController.java:193)
12-07 15:50:20.635 12769-12769/com.xp.xyz W/System.err:     at com.arialyy.aria.core.common.controller.FeatureController.checkConfig(FeatureController.java:135)
12-07 15:50:20.635 12769-12769/com.xp.xyz W/System.err:     at com.arialyy.aria.core.common.controller.NormalController.reStart(NormalController.java:122)
12-07 15:50:20.635 12769-12769/com.xp.xyz W/System.err:     at com.arialyy.aria.core.common.AbsNormalTarget.reStart(AbsNormalTarget.java:206)
12-07 15:50:20.635 12769-12769/com.xp.xyz W/System.err:     at com.xp.xyz.ui.homeFivePage.adapter.DownloadWordAdapter.start(DownloadWordAdapter.java:298)
12-07 15:50:20.635 12769-12769/com.xp.xyz W/System.err:     at com.xp.xyz.ui.homeFivePage.adapter.DownloadWordAdapter.access$100(DownloadWordAdapter.java:40)
12-07 15:50:20.635 12769-12769/com.xp.xyz W/System.err:     at com.xp.xyz.ui.homeFivePage.adapter.DownloadWordAdapter$BtClickListener.onClick(DownloadWordAdapter.java:252)
12-07 15:50:20.635 12769-12769/com.xp.xyz W/System.err:     at android.view.View.performClick(View.java:5207)
12-07 15:50:20.635 12769-12769/com.xp.xyz W/System.err:     at android.view.View$PerformClick.run(View.java:21177)
12-07 15:50:20.635 12769-12769/com.xp.xyz W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
12-07 15:50:20.635 12769-12769/com.xp.xyz W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
12-07 15:50:20.635 12769-12769/com.xp.xyz W/System.err:     at android.os.Looper.loop(Looper.java:148)
12-07 15:50:20.635 12769-12769/com.xp.xyz W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5441)
12-07 15:50:20.635 12769-12769/com.xp.xyz W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
12-07 15:50:20.635 12769-12769/com.xp.xyz W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
12-07 15:50:20.636 12769-12769/com.xp.xyz W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
12-07 15:50:20.647 12769-13420/com.xp.xyz D/FileUtil: 目标文件所在路径不存在，准备创建……

12-07 15:50:21.864 12769-12769/com.xp.xyz E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xp.xyz, PID: 12769
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: DownloadGroupEntity.groupHash (code 2067)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:732)
        at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
        at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
        at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1576)
        at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1522)
        at com.arialyy.aria.orm.DelegateUpdate.updateData(DelegateUpdate.java:63)
        at com.arialyy.aria.orm.DelegateWrapper.updateData(DelegateWrapper.java:117)
        at com.arialyy.aria.orm.DbEntity.update(DbEntity.java:256)
        at com.arialyy.aria.orm.DbEntity.save(DbEntity.java:265)
        at com.arialyy.aria.core.download.CheckDGEntityUtil.saveEntity(CheckDGEntityUtil.java:155)
        at com.arialyy.aria.core.download.CheckDGEntityUtil.checkEntity(CheckDGEntityUtil.java:150)
        at com.arialyy.aria.core.common.controller.FeatureController.checkEntity(FeatureController.java:193)
        at com.arialyy.aria.core.common.controller.FeatureController.checkConfig(FeatureController.java:135)
        at com.arialyy.aria.core.common.controller.NormalController.reStart(NormalController.java:122)
        at com.arialyy.aria.core.common.AbsNormalTarget.reStart(AbsNormalTarget.java:206)
        at com.xp.xyz.ui.homeFivePage.adapter.DownloadWordAdapter.start(DownloadWordAdapter.java:298)
        at com.xp.xyz.ui.homeFivePage.adapter.DownloadWordAdapter.access$100(DownloadWordAdapter.java:40)
        at com.xp.xyz.ui.homeFivePage.adapter.DownloadWordAdapter$BtClickListener.onClick(DownloadWordAdapter.java:252)
        at android.view.View.performClick(View.java:5207)
        at android.view.View$PerformClick.run(View.java:21177)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5441)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

## 重现步骤

1.当一个组任务正在执行下载的时候，然后创建另外一个组任务，当前的的任务变为wait转态，点击重新reStart后就出现了上面的崩溃日志，好像用resume也是同样的问题。
2.
3.
4.

**Comment by AriaLyy** [comment]
检查下你的两个组合任务的url列表是否是一样的？

**Comment by pz-bottle** [comment]
> 检查下你的两个组合任务的url列表是否是一样的？

**Comment by pz-bottle** [comment]
> 检查下你的两个组合任务的url列表是否是一样的？

嗯嗯，我再检查一下情况

**Comment by pz-bottle** [comment]
大佬我检查了一下我这边组下载的url是没有问题的，现在还是存在当一个组任务正在执行时，如果这个时候创建另外一个新的下载组任务就会出现上面的问题。

**Comment by AriaLyy** [comment]
你的两个组任务的地址方便提供下吗？我看下hash是不是一样的

**Comment by pz-bottle** [comment]
大佬我现在已经去掉使用组任务了，我现在使用普通任务加for循环来代替组任务，对了大佬你你那边怎样处理在app退出后，下载任务不会变为null，也就是在我再次打开APP是任务依然是正常的？
