### ISSUE TITLE
你好，请问FTPS下载如何设置忽略安全证书

### ISSUE THREAD

**Issue by happyCoding12138** [AriaLyy/Aria#557]
## 版本
* 框架版本
3.6.3
* 系统版本

## 重现步骤

1.
2.
3.
4.

**Comment by AriaLyy** [comment]
使用`3.7.10`版本

**Comment by happyCoding12138** [comment]
切换为3.7.10版本，下载一半提示失败，错误信息如下
`com.arialyy.aria.exception.AriaIOException: Aria Net Exception:获取流失败，错误码为：425，msg：425 Can't open passive connection.
     at com.arialyy.aria.ftp.download.FtpDThreadTaskAdapter.handlerThreadTask(FtpDThreadTaskAdapter.java:81)
     at com.arialyy.aria.core.task.AbsThreadTaskAdapter.call(AbsThreadTaskAdapter.java:54)
     at com.arialyy.aria.core.task.ThreadTask.call(ThreadTask.java:485)
     at com.arialyy.aria.core.task.ThreadTask.call(ThreadTask.java:48)
     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
     at java.lang.Thread.run(Thread.java:764)
 分块【SurveyMaster-3.6.9.bin.1.part】正在重试
 分块文件【SurveyMaster-3.6.9.bin.1.part】不存在，该分块将重新开始
26:37.242 28875-28985/com.arialyy.simple D/FtpDThreadTaskAdapter: 任务【ftp://114.84.29.110:9033/package/9/SurveyMaster/SurveyMaster-3.6.9.bin】线程__1__开始下载【开始位置 : 30471986，结束位置：60943972】
37.317 28875-28985/com.arialyy.simple I/FtpDThreadTaskAdapter: remotePath【/package/9/SurveyMaster/SurveyMaster-3.6.9.bin】
37.344 28875-28985/com.arialyy.simple W/System.err: com.arialyy.aria.exception.AriaIOException: Aria Net Exception:获取流失败，错误码为：425，msg：425 Can't open passive connection.`

**Comment by AriaLyy** [comment]
使用主动模式看看，应该是被动模式的问题
https://aria.laoyuyu.me/aria_doc/api/ftp_params.html#%E4%B8%89%E3%80%81%E4%B8%BB%E5%8A%A8%E6%A8%A1%E5%BC%8F
