### ISSUE TITLE
暂停后恢复出现空指针错误

### ISSUE THREAD

**Issue by kieferHuan** [AriaLyy/Aria#560]
## 版本
* 框架版本
3.7.10

* 系统版本
6.0

## 错误日志

java.lang.NullPointerException: (ssl_session == null)
at com.android.org.conscrypt.NativeCrypto.SSL_SESSION_cipher(Native Method)
at com.android.org.conscrypt.OpenSSLSessionImpl.getCipherSuite(OpenSSLSessionImpl.java:320)
at com.android.okhttp.Handshake.get(Handshake.java:48)
at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:105)
at com.android.okhttp.Connection.connect(Connection.java:167)
at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:209)
at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:355)
at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:344)
at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:262)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:454)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:25)
at com.arialyy.aria.http.HttpFileInfoThread.run(8)
at java.lang.Thread.run(Thread.java:818)

## 重现步骤

1.下载3.7.10版本
2.下载文件，暂停后恢复出现

**Comment by AriaLyy** [comment]
自己设置的证书还是使用默认的证书？

**Comment by kieferHuan** [comment]
> 自己设置的证书还是使用默认的证书？

默认的证书

**Comment by AriaLyy** [comment]
能否提供一份地址我？我测试的几个百度的https地址都是正常的。。。

**Comment by AriaLyy** [comment]
这个是google 的问题，https://github.com/square/okhttp/issues/3301
