### ISSUE TITLE
3.8.1ftp上传报错

### ISSUE THREAD

**Issue by yanbin92** [AriaLyy/Aria#576]
* 系统版本
    implementation 'com.arialyy.aria:core:3.8.1'
    annotationProcessor 'com.arialyy.aria:compiler:3.8.1'
    implementation 'com.arialyy.aria:ftpComponent:3.8.1'
## 错误日志
: 任务【/storage/emulated/0/santaidownload//test/sepaBeanUandT4.zip】线程__0__开始上传【开始位置 : 0，结束位置：39250307】
2019-12-23 16:23:43.716 20925-21909/com.santai.chembeango D/FtpUThreadTaskAdapter: remotePath: /sdcard/update/upgradePackage/sepaBeanUandT4.zip
2019-12-23 16:23:44.625 20925-20925/com.santai.chembeango D/OkHttp: PP = /storage/emulated/0/santaidownload//test/sepaBeanUandT4.zip0
2019-12-23 16:23:45.625 20925-20925/com.santai.chembeango D/OkHttp: PP = /storage/emulated/0/santaidownload//test/sepaBeanUandT4.zip0
2019-12-23 16:23:46.626 20925-20925/com.santai.chembeango D/OkHttp: PP = /storage/emulated/0/santaidownload//test/sepaBeanUandT4.zip0
2019-12-23 16:23:47.628 20925-20925/com.santai.chembeango D/OkHttp: PP = /storage/emulated/0/santaidownload//test/sepaBeanUandT4.zip3
2019-12-23 16:23:48.630 20925-20925/com.santai.chembeango D/OkHttp: PP = /storage/emulated/0/santaidownload//test/sepaBeanUandT4.zip6
2019-12-23 16:23:49.644 20925-20925/com.santai.chembeango D/OkHttp: PP = /storage/emulated/0/santaidownload//test/sepaBeanUandT4.zip10
2019-12-23 16:23:50.645 20925-20925/com.santai.chembeango D/OkHttp: PP = /storage/emulated/0/santaidownload//test/sepaBeanUandT4.zip13
2019-12-23 16:23:51.647 20925-20925/com.santai.chembeango D/OkHttp: PP = /storage/emulated/0/santaidownload//test/sepaBeanUandT4.zip19
2019-12-23 16:23:51.775 20925-21899/com.santai.chembeango I/aaa: sendMsg : 000013{"Request":1}
2019-12-23 16:23:51.819 20925-21898/com.santai.chembeango I/aaa: responseData:{"Response":1}
2019-12-23 16:23:52.651 20925-20925/com.santai.chembeango D/OkHttp: PP = /storage/emulated/0/santaidownload//test/sepaBeanUandT4.zip25
2019-12-23 16:23:53.653 20925-20925/com.santai.chembeango D/OkHttp: PP = /storage/emulated/0/santaidownload//test/sepaBeanUandT4.zip30
2019-12-23 16:23:53.862 20925-21909/com.santai.chembeango W/System.err: aria.apache.commons.net.io.CopyStreamException: IOException caught while copying.
2019-12-23 16:23:53.863 20925-21909/com.santai.chembeango W/System.err:     at aria.apache.commons.net.io.Util.copyStream(Util.java:125)
2019-12-23 16:23:53.863 20925-21909/com.santai.chembeango W/System.err:     at aria.apache.commons.net.ftp.FTPClient._storeFile(FTPClient.java:669)
2019-12-23 16:23:53.863 20925-21909/com.santai.chembeango W/System.err:     at aria.apache.commons.net.ftp.FTPClient.__storeFile(FTPClient.java:631)
2019-12-23 16:23:53.863 20925-21909/com.santai.chembeango W/System.err:     at aria.apache.commons.net.ftp.FTPClient.storeFile(FTPClient.java:1921)
2019-12-23 16:23:53.863 20925-21909/com.santai.chembeango W/System.err:     at com.arialyy.aria.ftp.upload.FtpUThreadTaskAdapter.upload(FtpUThreadTaskAdapter.java:163)
2019-12-23 16:23:53.863 20925-21909/com.santai.chembeango W/System.err:     at com.arialyy.aria.ftp.upload.FtpUThreadTaskAdapter.handlerThreadTask(FtpUThreadTaskAdapter.java:79)
2019-12-23 16:23:53.864 20925-21909/com.santai.chembeango W/System.err:     at com.arialyy.aria.core.task.AbsThreadTaskAdapter.call(AbsThreadTaskAdapter.java:54)
2019-12-23 16:23:53.864 20925-21909/com.santai.chembeango W/System.err:     at com.arialyy.aria.core.task.ThreadTask.call(ThreadTask.java:485)
2019-12-23 16:23:53.864 20925-21909/com.santai.chembeango W/System.err:     at com.arialyy.aria.core.task.ThreadTask.call(ThreadTask.java:47)
2019-12-23 16:23:53.864 20925-21909/com.santai.chembeango W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-12-23 16:23:53.864 20925-21909/com.santai.chembeango W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-12-23 16:23:53.864 20925-21909/com.santai.chembeango W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-12-23 16:23:53.864 20925-21909/com.santai.chembeango W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-12-23 16:23:53.882 20925-21909/com.santai.chembeango W/System.err: Caused by: java.io.IOException: read failed: EBADF (Bad file descriptor)
2019-12-23 16:23:53.882 20925-21909/com.santai.chembeango W/System.err:     at libcore.io.IoBridge.read(IoBridge.java:511)
2019-12-23 16:23:53.883 20925-21909/com.santai.chembeango W/System.err:     at java.io.RandomAccessFile.readBytes(RandomAccessFile.java:385)
2019-12-23 16:23:53.883 20925-21909/com.santai.chembeango W/System.err:     at java.io.RandomAccessFile.read(RandomAccessFile.java:414)
2019-12-23 16:23:53.883 20925-21909/com.santai.chembeango W/System.err:     at com.arialyy.aria.util.BufferedRandomAccessFile.fillBuffer(BufferedRandomAccessFile.java:185)
2019-12-23 16:23:53.883 20925-21909/com.santai.chembeango W/System.err:     at com.arialyy.aria.util.BufferedRandomAccessFile.seek(BufferedRandomAccessFile.java:217)
2019-12-23 16:23:53.883 20925-21909/com.santai.chembeango W/System.err:     at com.arialyy.aria.util.BufferedRandomAccessFile.read(BufferedRandomAccessFile.java:263)
2019-12-23 16:23:53.884 20925-21909/com.santai.chembeango W/System.err:     at com.arialyy.aria.util.BufferedRandomAccessFile.read(BufferedRandomAccessFile.java:253)
2019-12-23 16:23:53.884 20925-21909/com.santai.chembeango W/System.err:     at com.arialyy.aria.ftp.upload.FtpFISAdapter.read(FtpFISAdapter.java:54)
2019-12-23 16:23:53.884 20925-21909/com.santai.chembeango W/System.err:     at aria.apache.commons.net.io.Util.copyStream(Util.java:95)
2019-12-23 16:23:53.884 20925-21909/com.santai.chembeango W/System.err: 	... 12 more
2019-12-23 16:23:53.885 20925-21909/com.santai.chembeango W/System.err: Caused by: android.system.ErrnoException: read failed: EBADF (Bad file descriptor)
2019-12-23 16:23:53.885 20925-21909/com.santai.chembeango W/System.err:     at libcore.io.Linux.readBytes(Native Method)
2019-12-23 16:23:53.885 20925-21909/com.santai.chembeango W/System.err:     at libcore.io.Linux.read(Linux.java:184)
2019-12-23 16:23:53.885 20925-21909/com.santai.chembeango W/System.err:     at libcore.io.BlockGuardOs.read(BlockGuardOs.java:254)
2019-12-23 16:23:53.885 20925-21909/com.santai.chembeango W/System.err:     at libcore.io.IoBridge.read(IoBridge.java:501)
2019-12-23 16:23:53.885 20925-21909/com.santai.chembeango W/System.err: 	... 20 more
2019-12-23 16:23:53.887 20925-21909/com.santai.chembeango W/System.err: com.arialyy.aria.exception.AriaIOException: 文件上传错误，错误码为：226, msg：226 Transfer complete.

## 重现步骤

                            mTaskId=  Aria.upload(ChooseWhichDevice2UpdateSoftAc.this)
                                    .loadFtp(updateZip) //上传本地文件路径
                                    .setUploadUrl(ftpurl)        //上传的ftp服务器地址
                                    .ignoreFilePathOccupy()
                                    .option(new FtpOption().login("***", "***"))
                                    .create();
新版本每次ftp上传都只能传到30%就报错 ，3.6.4的版本没这问题

**Comment by AriaLyy** [comment]
https://stackoverflow.com/questions/14584755/read-failed-ebadf-bad-file-number/14584907
