### ISSUE TITLE
umeng统计到的错误信息

### ISSUE THREAD

**Issue by wjk2813** [AriaLyy/Aria#584]
java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.arialyy.aria.core.inf.IUtil.isRunning()' on a null object reference
    at com.arialyy.aria.core.task.AbsTask.start(Unknown Source:72)
    at com.arialyy.aria.core.queue.AbsTaskQueue.startTask(Unknown Source:62)
    at com.arialyy.aria.core.queue.AbsTaskQueue.startTask(Unknown Source:1)
    at com.arialyy.aria.core.queue.AbsTaskQueue.startTask(Unknown Source:2)
    at com.arialyy.aria.core.scheduler.TaskSchedulers.startNextTask(Unknown Source:31)
    at com.arialyy.aria.core.scheduler.TaskSchedulers.handleNormalEvent(Unknown Source:54)
    at com.arialyy.aria.core.scheduler.TaskSchedulers.handleMessage(Unknown Source:47)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:201)
    at android.app.ActivityThread.main(ActivityThread.java:6806)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

-------------------------------------------------------------------

java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.add(java.lang.Object)' on a null object reference
    at com.arialyy.aria.core.common.RecordHandler.initRecord(Unknown Source:69)
    at com.arialyy.aria.core.common.RecordHandler.getRecord(Unknown Source:150)
    at com.arialyy.aria.core.loader.AbsLoader.startFlow(Unknown Source:19)
    at com.arialyy.aria.core.loader.AbsLoader.run(Unknown Source:7)
    at java.lang.Thread.run(Thread.java:764)

**Comment by wjk2813** [comment]
内存溢出
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
    at java.lang.Thread.nativeCreate(Native Method)
    at java.lang.Thread.start(Thread.java:733)
    at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:970)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1388)
    at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
    at com.arialyy.aria.core.manager.ThreadTaskManager.startThread(Unknown Source:64)
    at com.arialyy.aria.core.loader.NormalLoader.startThreadTask(Unknown Source:65)
    at com.arialyy.aria.core.loader.NormalLoader.handleBreakpoint(Unknown Source:304)
    at com.arialyy.aria.core.loader.NormalLoader.handleTask(Unknown Source:8)
    at com.arialyy.aria.core.loader.AbsLoader.startFlow(Unknown Source:41)
    at com.arialyy.aria.core.loader.AbsLoader.run(Unknown Source:7)
    at java.lang.Thread.run(Thread.java:764)

**Comment by wjk2813** [comment]
umeng统计到的错误基本都是下载崩溃。。。

**Comment by AriaLyy** [comment]
感谢反馈，空指针我判断下就行了，内存溢出那个是线程数太多导致的，建议先将任务的线程数设置为1，后面我再想下方案解决下

**Comment by wjk2813** [comment]
3.8.1 的。
java.lang.NullPointerException: Attempt to invoke interface method 'void com.arialyy.aria.core.inf.IUtil.stop()' on a null object reference
    at com.arialyy.aria.core.task.AbsTask.stop()
    at com.arialyy.aria.core.task.AbsTask.stop()
    at com.arialyy.aria.core.queue.pool.DLoadExecutePool.pollFirstTask()
    at com.arialyy.aria.core.queue.pool.DLoadExecutePool.putTask()
    at com.arialyy.aria.core.queue.AbsTaskQueue.startTask()
    at com.arialyy.aria.core.queue.AbsTaskQueue.startTask()
    at com.arialyy.aria.core.queue.AbsTaskQueue.startTask()
    at com.arialyy.aria.core.scheduler.TaskSchedulers.startNextTask()
    at com.arialyy.aria.core.scheduler.TaskSchedulers.handleNormalEvent()
    at com.arialyy.aria.core.scheduler.TaskSchedulers.handleMessage()
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:232)
    at android.app.ActivityThread.main(ActivityThread.java:6910)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

**Comment by wjk2813** [comment]
老哥能发个修复版吗

**Comment by AriaLyy** [comment]
过几天吧，年底太忙了

**Comment by AriaLyy** [comment]
使用 3.8.3_beta_5 版本

**Comment by wjk2813** [comment]
还是有小概率的内存溢出。不过影响不大了。

**Comment by wjk2813** [comment]
感谢作者。
