### ISSUE TITLE
请问这种链接怎么处理？

### ISSUE THREAD

**Issue by Joker-Q4** [AriaLyy/Aria#595]
https://cn7.kankia.com/hls/20200105/570e52cf452c556cefa90de296b5e23c/1578235157/index.m3u8

请问这种m3u8为什么下载不了，我用demo也下载失败，但是异常信息为null

**Comment by Joker-Q4** [comment]
https://cn2.zuidadianying.com/20171217/VnQdwd35/index.m3u8

还有这种内部包含m3u8的直接报404的错误了0.0

**Comment by AriaLyy** [comment]
自行处理ts切片的url，https://aria.laoyuyu.me/aria_doc/download/m3u8_vod.html#%E4%BA%8C%E3%80%81url%E8%BD%AC%E6%8D%A2%E5%99%A8

二级m3u8，https://aria.laoyuyu.me/aria_doc/download/m3u8_vod.html#32%E3%80%81m3u8%E7%A0%81%E7%8E%87url%E8%BD%AC%E6%8D%A2%E5%99%A8

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/issues/597

**Comment by Joker-Q4** [comment]
如果有301重定向的话，VodTsUrlConverter中的public List<String> convert(String m3u8Url, List<String> tsUrls) 第一个参数仍然是未重定向之前的url，如何取到重定向之后的url呢

**Comment by AriaLyy** [comment]
重定向前的

**Comment by Joker-Q4** [comment]
emmmm，如何取到重定向之后的呢

**Comment by AriaLyy** [comment]
框架里面是自动获取重定向连接的，你只需要转换重定向之前的连接便可

**Comment by Joker-Q4** [comment]
https://cn7.kankia.com/hls/20200108/e1eaec074274c64fe46a3bdb5d2ba487/1578488360/index.m3u8

请问这中重定向应该怎么解决呢？下面是异常信息

2020-01-09 19:46:43.034 15889-16702/com.joker W/System.err: com.arialyy.aria.exception.TaskException: Aria Task Exception:, 连接错误，http错误码：301，url：https://cn7.kankia.com/hls/20200108/e1eaec074274c64fe46a3bdb5d2ba487/1578488360/film_00001.ts
2020-01-09 19:46:43.034 15889-16702/com.joker W/System.err:     at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handlerThreadTask(M3U8ThreadTaskAdapter.java:95)
2020-01-09 19:46:43.034 15889-16702/com.joker W/System.err:     at com.arialyy.aria.core.task.AbsThreadTaskAdapter.call(AbsThreadTaskAdapter.java:54)
2020-01-09 19:46:43.034 15889-16702/com.joker W/System.err:     at com.arialyy.aria.core.task.ThreadTask.call(ThreadTask.java:485)
2020-01-09 19:46:43.035 15889-16702/com.joker W/System.err:     at com.arialyy.aria.core.task.ThreadTask.call(ThreadTask.java:47)
2020-01-09 19:46:43.035 15889-16702/com.joker W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-01-09 19:46:43.035 15889-16702/com.joker W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2020-01-09 19:46:43.035 15889-16702/com.joker W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2020-01-09 19:46:43.035 15889-16702/com.joker W/System.err:     at java.lang.Thread.run(Thread.java:764)

**Comment by AriaLyy** [comment]
是有这个问题，ts文件没有做30x跳转，使用`3.8.3_beta_5`版本可以解决这个问题

**Comment by Joker-Q4** [comment]
好的，谢谢！😄
