### ISSUE TITLE
Only one Looper may be created per thread

### ISSUE THREAD

**Issue by Mitaxing** [AriaLyy/Aria#601]
## 版本
* 3.8.3

* android 4.4

## 错误日志
`java.lang.RuntimeException: Only one Looper may be created per thread
        at android.os.Looper.prepare(Looper.java:77)
        at android.os.Looper.prepare(Looper.java:72)
        at com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:124)
        at com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:114)
        at com.arialyy.aria.core.loader.AbsNormalLoaderUtil.start(AbsNormalLoaderUtil.java:119)
        at com.arialyy.aria.core.task.AbsTask.start(AbsTask.java:233)
        at com.arialyy.aria.core.task.AbsTask.start(AbsTask.java:211)
        at com.arialyy.aria.core.queue.AbsTaskQueue.reTryStart(AbsTaskQueue.java:341)
        at com.arialyy.aria.core.queue.AbsTaskQueue.reTryStart(AbsTaskQueue.java:42)
        at com.arialyy.aria.core.scheduler.FailureTaskHandler$2.run(FailureTaskHandler.java:92)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:816)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:632)
        at dalvik.system.NativeStart.main(Native Method)`

## 重现步骤
websocket接收到下载信息，使用基本方式下载视频，不是必现
`Aria.download(this)
                            .load(url)
                            .ignoreFilePathOccupy()
                            .setFilePath(savePath)
                            .create();`

**Comment by AriaLyy** [comment]
清空下gradle缓存，重新下载 3.8.3版本
