### ISSUE TITLE
任务fail时直接崩溃

### ISSUE THREAD

**Issue by narakai** [AriaLyy/Aria#613]
## 版本
* 框架版本
3.8.5
* 系统版本
Android 10
## 错误日志

java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter e
        at com.clem.downloader.ui.MainActivity.taskFail(Unknown Source:7)
        at com.clem.downloader.ui.MainActivity$$DownloadListenerProxy.onTaskFail(MainActivity$$DownloadListenerProxy.java:30)
        at com.clem.downloader.ui.MainActivity$$DownloadListenerProxy.onTaskFail(MainActivity$$DownloadListenerProxy.java:12)

## 重现步骤

1. 常见于上一个任务未完成，重新进入app时重新恢复下载时崩溃

**Comment by AriaLyy** [comment]
你是使用两个参数的fail？

**Comment by narakai** [comment]
是的

**Comment by AriaLyy** [comment]
使用一个参数的fail，后面会把两个参数的那个移除

**Comment by narakai** [comment]
好的，谢谢作者回答
