### ISSUE TITLE
SQLiteConstraintException

### ISSUE THREAD

**Issue by zxianwei** [AriaLyy/Aria#635]
## 版本
* 3.8.7-beta-5

* 系统版本
Android 9.0
## 错误日志

Error inserting currentProgress=0 urls=http%3A%2F%2Fshuzhibao.oss-cn-beijing.aliyuncs.com%2FiOS%2FLearnDuck%2Fclass%2F161599_1582757673684.jpg%24%24http%3A%2F%2Fshuzhibao.oss-cn-beijing.aliyuncs.com%2FiOS%2FLearnDuck%2Faudio%2F161599_1582757925503.mp3%24%24http%3A%2F%2Fshuzhibao.oss-cn-beijing.aliyuncs.com%2FiOS%2FLearnDuck%2Faudio%2F161599_1582757936714.mp3%24%24http%3A%2F%2Fshuzhibao.oss-cn-beijing.aliyuncs.com%2FiOS%2FLearnDuck%2Faudio%2F161599_1582757961011.mp3%24%24http%3A%2F%2Fshuzhibao.oss-cn-beijing.aliyuncs.com%2FiOS%2FLearnDuck%2Faudio%2F161599_1582757972623.mp3%24%24http%3A%2F%2Fshuzhibao.oss-cn-beijing.aliyuncs.com%2FiOS%2FLearnDuck%2Faudio%2F161599_1582757988254.mp3%24%24http%3A%2F%2Fshuzhibao.oss-cn-beijing.aliyuncs.com%2FiOS%2FLearnDuck%2Faudio%2F161599_1582758001556.mp3%24%24http%3A%2F%2Fshuzhibao.oss-cn-beijing.aliyuncs.com%2FiOS%2FLearnDuck%2Faudio%2F161599_1582758015484.mp3%24%24http%3A%2F%2Fshuzhibao.oss-cn-beijing.aliyuncs.com%2FiOS%2FLearnDuck%2Faudio%2F161599_1582758033123.mp3%24%24http%3A%2F%2Fshuzhibao.oss-cn-beijing.aliyuncs.com%2FiOS%2FLearnDuck%2Faudio%2F161599_1582758049310.mp3%24%24http%3A%2F%2Fshuzhibao.oss-cn-beijing.aliyuncs.com%2FiOS%2FLearnDuck%2Faudio%2F161599_1582757913208.mp3%24%24http%3A%2F%2Fshuzhibao.oss-cn-beijing.aliyuncs.com%2FiOS%2FLearnDuck%2Faudio%2F161599_1582758063147.mp3%24%24 fileSize=0 groupHash=41ebc208a56220e89f9f6e8e83b291af completeTime=0 alias=161631 stopTime=0 dirPath=%2Fstorage%2Femulated%2F0%2FAndroid%2Fdata%2Fcom.jianiao.businessschool%2Ffiles%2F161631%2F11 state=3 percent=0 isComplete=false

android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: DownloadGroupEntity.groupHash (code 2067 SQLITE_CONSTRAINT_UNIQUE)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:796)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1564)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1433)
        at com.arialyy.aria.orm.DelegateUpdate.insertData(DelegateUpdate.java:140)
        at com.arialyy.aria.orm.DelegateWrapper.insertData(DelegateWrapper.java:181)
        at com.arialyy.aria.orm.DbEntity.insert(DbEntity.java:293)
        at com.arialyy.aria.orm.DbEntity.save(DbEntity.java:267)
        at com.arialyy.aria.core.download.CheckDGEntityUtil.saveEntity(CheckDGEntityUtil.java:162)
        at com.arialyy.aria.core.download.CheckDGEntityUtil.checkEntity(CheckDGEntityUtil.java:157)
        at com.arialyy.aria.core.common.controller.FeatureController.checkEntity(FeatureController.java:209)
        at com.arialyy.aria.core.common.controller.FeatureController.checkConfig(FeatureController.java:151)
        at com.arialyy.aria.core.common.controller.BuilderController.create(BuilderController.java:55)
        at com.arialyy.aria.core.common.AbsBuilderTarget.create(AbsBuilderTarget.java:80)

![image](https://user-images.githubusercontent.com/28806891/76164143-6c14c080-6187-11ea-91c4-56f4f55e4434.png)

## 重现步骤

1.使用组合任务重复下载一组url,但是保存的地址不一样，就会报错了。第一次报错了不可以下载，第二次下载就会下载成功但是返回id还是-1.

**Comment by AriaLyy** [comment]
使用3.8.7-beta-8版本，增加了ignoreTaskOccupy 方法

**Comment by xiaoxiandezhuque** [comment]
> 使用3.8.7-beta-8版本，增加了ignoreTaskOccupy方法

可以在普通任务里面也加一个这个吗， 我普通任务，使用相同的地址，也会报这个错误
