### ISSUE TITLE
组合任务因下载地址问题 StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by yaolv7** [AriaLyy/Aria#651]
特殊的下载url时会报错

## 版本
*com.arialyy.aria:core:3.8.7-beta-8

## 错误日志
java.lang.StringIndexOutOfBoundsException: String index out of range: -123
        at java.lang.String.substring(String.java:2064)
        at com.arialyy.aria.util.DbDataHelper.createHttpSubTask(DbDataHelper.java:112)
        at com.arialyy.aria.core.download.target.HttpGroupConfigHandler.setGroupUrl(HttpGroupConfigHandler.java:59)
        at com.arialyy.aria.core.download.target.GroupBuilderTarget.<init>(GroupBuilderTarget.java:35)
        at com.arialyy.aria.core.download.target.DTargetFactory.generateGroupBuilderTarget(DTargetFactory.java:78)
        at com.arialyy.aria.core.download.DownloadReceiver.loadGroup(DownloadReceiver.java:102)

## 重现步骤

组合任务，下载任务组  loadGroup(pathList)

下载地址List里有url为：
http://192.168.8.253:8080/geoserver/gwc/service/wmts?layer=test_mepu_gis:shuifuTifLayer&style=&tilematrixset=EPSG:4326&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image/png&TileMatrix=EPSG:4326:17&TileCol=206987&TileRow=44857

url里带参数 Format=image/png 

 int lastIndex = url.lastIndexOf(File.separator);  // 值为 174
 int endIndex = url.lastIndexOf("?"); // 值为 52

导致DbDataHelper#createHttpSubTask(String groupHash, List<String> urls)112行substring报错  entity.setFileName(url.substring(lastIndex + 1,endIndex));

**Comment by DaveBoy** [comment]
介个是我的锅，后面修复了  [#633](https://github.com/AriaLyy/Aria/pull/633/commits/a65b2e31f9a9f76ee76a4aeea78676b6e2771800)你需要一个新的beta  @AriaLyy

**Comment by AriaLyy** [comment]
使用`3.8.7-beta-11`版本

**Comment by yaolv7** [comment]
> 介个是我的锅，后面修复了 [#633](https://github.com/AriaLyy/Aria/pull/633/commits/a65b2e31f9a9f76ee76a4aeea78676b6e2771800)你需要一个新的beta @AriaLyy

辛苦了，非常感谢！！！
