### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by SmallStoneDD** [AriaLyy/Aria#659]
机型 小米9se
系统版本 10

java.lang.NullPointerException: Attempt to invoke interface method 'void com.android.okhttp.internal.http.HttpStream.writeRequestHeaders(com.android.okhttp.Request)' on a null object reference
    at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:606)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
    at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
    at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
    at com.arialyy.aria.http.download.HttpDFileInfoTask.run(HttpDFileInfoTask.java:19)
    at com.arialyy.aria.core.loader.NormalLoader.handleTask(NormalLoader.java:3)
    at com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:8)
    at com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:4)
    at java.lang.Thread.run(Thread.java:919)

**Comment by DaveBoy** [comment]
看上去是okhttp内部产生的异常？
