### ISSUE TITLE
m3u8下载部分切片连接错误导致下载失败

### ISSUE THREAD

**Issue by benxin123** [AriaLyy/Aria#662]
部分切片加载失败，是不是可以跳过下载

## 版本
* 框架版本
3.8.6
* 系统版本
安卓10
## 错误日志
W/System.err: com.arialyy.aria.exception.AriaM3U8Exception: Aria M3U8 Exception:
    连接错误，http错误码：429，url：https://youku.cdn11-okzy.com/20200403/14855_a76995d2/1000k/hls/763e0e6a6c1000020.ts
W/System.err:     at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handleConn(M3U8ThreadTaskAdapter.java:141)
        at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handlerThreadTask(M3U8ThreadTaskAdapter.java:92)
        at com.arialyy.aria.core.task.AbsThreadTaskAdapter.call(AbsThreadTaskAdapter.java:54)
        at com.arialyy.aria.core.task.ThreadTask.call(ThreadTask.java:543)
        at com.arialyy.aria.core.task.ThreadTask.call(ThreadTask.java:47)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by AriaLyy** [comment]
使用`ignoreFailureTs`这个api

**Comment by benxin123** [comment]
就是使用后还是会出现这个问题

**Comment by benxin123** [comment]
重试三次后就下载错误了

**Comment by AriaLyy** [comment]
`3.8.12`已修复了这个问题，使用`ignoreFailureTs `后，失败的ts切片将不会重试

**Comment by SuperZhouyong** [comment]
跳过下载之后文件最后1合并有问题，不能播放 @AriaLyy A
