### ISSUE TITLE
domo 第一次运行点击下载崩溃，DB的问题、日志如下：

### ISSUE THREAD

**Issue by LiesLee** [AriaLyy/Aria#67]
Process: com.arialyy.simple, PID: 22038
                                                                    android.database.sqlite.SQLiteException: no such column: serialVersionUID (code 1): , while compiling: SELECT rowid, * FROM DownloadEntity where downloadPath='/storage/emulated/0/Download/阴阳师' AND downloadUrl='https://g37.gdl.netease.com/onmyoji_netease_10_1.0.20.apk' AND redirectUrl='' AND isDownloadComplete='false' AND isRedirect='false' AND $change='null' AND serialVersionUID='4261567989868876910'
                                                                        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:894)
                                                                        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:505)
                                                                        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:726)
                                                                        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1417)
                                                                        at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1356)
                                                                        at com.arialyy.aria.orm.SqlHelper.findData(SqlHelper.java:216)
                                                                        at com.arialyy.aria.orm.DbUtil.findData(DbUtil.java:106)
                                                                        at com.arialyy.aria.orm.DbEntity.findData(DbEntity.java:153)
                                                                        at com.arialyy.aria.orm.DbEntity.updateRowID(DbEntity.java:171)
                                                                        at com.arialyy.aria.orm.DbEntity.insert(DbEntity.java:147)
                                                                        at com.arialyy.aria.orm.DbEntity.save(DbEntity.java:130)
                                                                        at com.arialyy.aria.core.download.DownloadTask$Builder.build(DownloadTask.java:199)
                                                                        at com.arialyy.aria.core.queue.TaskFactory.createDownloadTask(TaskFactory.java:91)
                                                                        at com.arialyy.aria.core.queue.TaskFactory.createTask(TaskFactory.java:63)
                                                                        at com.arialyy.aria.core.queue.DownloadTaskQueue.createTask(DownloadTaskQueue.java:134)
                                                                        at com.arialyy.aria.core.queue.DownloadTaskQueue.createTask(DownloadTaskQueue.java:36)
                                                                        at com.arialyy.aria.core.command.AddCmd.executeCmd(AddCmd.java:39)
                                                                        at com.arialyy.aria.core.AriaManager.exe(AriaManager.java:138)
                                                                        at com.arialyy.aria.core.inf.AbsTarget.start(AbsTarget.java:212)
                                                                        at com.arialyy.simple.download.multi_download.FileListAdapter$1.onClick(FileListAdapter.java:73)
                                                                        at android.view.View.performClick(View.java:4763)
                                                                        at android.view.View$PerformClick.run(View.java:19821)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5274)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)

**Comment by AriaLyy** [comment]
请看这个 issue https://github.com/AriaLyy/Aria/issues/7
