### ISSUE TITLE
部分手机升级3.8.5报错:no such table: ThreadRecord

### ISSUE THREAD

**Issue by huangxiaoyu** [AriaLyy/Aria#670]
## 版本
* 现版本3.8.5 升级前3.6.4

* 系统版本
android 5.1, 6.0.1, 7.0, 7.1.2, 9
## 错误日志

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxxx.xxxx/com..xxxx.xxxx.view.activity.MainActivity}: android.database.sqlite.SQLiteException: no such table: ThreadRecord (Sqlite code 1 SQLITE_ERROR): , while compiling: UPDATE ThreadRecord SET threadId=0 WHERE threadId=-1, (OS error - 11:Try again) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
详细:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com..xxxx.xxxx/com..xxxx.xxxx.view.activity.MainActivity}: android.database.sqlite.SQLiteException: no such table: ThreadRecord (code 1): , while compiling: UPDATE ThreadRecord SET threadId=0 WHERE threadId=-1
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2566)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2626)
    at android.app.ActivityThread.access$1100(ActivityThread.java:170)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:179)
    at android.app.ActivityThread.main(ActivityThread.java:5769)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
Caused by: android.database.sqlite.SQLiteException: no such table: ThreadRecord (code 1): , while compiling: UPDATE ThreadRecord SET threadId=0 WHERE threadId=-1
    at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
    at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
    at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
    at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
    at android.database.sqlite.SQLiteProgram.(SQLiteProgram.java:58)
    at android.database.sqlite.SQLiteStatement.(SQLiteStatement.java:31)
    at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1674)
    at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
    at com.arialyy.aria.orm.SqlHelper.handle365Update(SqlHelper.java:1)
    at com.arialyy.aria.orm.SqlHelper.onUpgrade(SqlHelper.java:3)
    at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
    at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
    at com.arialyy.aria.orm.SqlHelper.getDb(SqlHelper.java:9)
    at com.arialyy.aria.orm.DelegateWrapper.(DelegateWrapper.java:4)
    at com.arialyy.aria.orm.DelegateWrapper.init(DelegateWrapper.java:4)
    at com.arialyy.aria.core.AriaManager.initDb(AriaManager.java:7)
    at com.arialyy.aria.core.AriaManager.initData(AriaManager.java:2)
    at com.arialyy.aria.core.AriaManager.init(AriaManager.java:5)
    at com.arialyy.aria.core.Aria.get(Aria.java:1)
    at com.arialyy.aria.core.Aria.download(Aria.java:3)
    at com..xxxx.xxxx.view.activity.MainActivity.e(MainActivity.java:4)
    at com..xxxx.xxxx.base.BaseActivity.onCreate(BaseActivity.java:15)
    at android.app.Activity.performCreate(Activity.java:6497)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2519)
    ... 9 more
android.database.sqlite.SQLiteException: no such table: ThreadRecord (code 1): , while compiling: UPDATE ThreadRecord SET threadId=0 WHERE threadId=-1
    at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
    at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
    at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
    at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
    at android.database.sqlite.SQLiteProgram.(SQLiteProgram.java:58)
    at android.database.sqlite.SQLiteStatement.(SQLiteStatement.java:31)
    at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1674)
    at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
    at com.arialyy.aria.orm.SqlHelper.handle365Update(SqlHelper.java:1)
    at com.arialyy.aria.orm.SqlHelper.onUpgrade(SqlHelper.java:3)
    at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
    at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
    at com.arialyy.aria.orm.SqlHelper.getDb(SqlHelper.java:9)
    at com.arialyy.aria.orm.DelegateWrapper.(DelegateWrapper.java:4)
    at com.arialyy.aria.orm.DelegateWrapper.init(DelegateWrapper.java:4)
    at com.arialyy.aria.core.AriaManager.initDb(AriaManager.java:7)
    at com.arialyy.aria.core.AriaManager.initData(AriaManager.java:2)
    at com.arialyy.aria.core.AriaManager.init(AriaManager.java:5)
    at com.arialyy.aria.core.Aria.get(Aria.java:1)
    at com.arialyy.aria.core.Aria.download(Aria.java:3)
    at com..xxxx.xxxx.view.activity.MainActivity.e(MainActivity.java:4)
    at com..xxxx.xxxx.base.BaseActivity.onCreate(BaseActivity.java:15)
    at android.app.Activity.performCreate(Activity.java:6497)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2519)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2626)
    at android.app.ActivityThread.access$1100(ActivityThread.java:170)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:179)
    at android.app.ActivityThread.main(ActivityThread.java:5769)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)

## 重现步骤

自己测试未能发现问题  但是友盟统计的不到1天的时间已经达到100次了

**Comment by huangxiaoyu** [comment]
1天的时间 已经163个同样的问题了 项目中用的地方多 麻烦看下什么问题导致的

**Comment by huangxiaoyu** [comment]
已经影响到700多人了...  大神不在么?

**Comment by AriaLyy** [comment]
麻烦提供下有问题的数据库，我这没有复现。

**Comment by huangxiaoyu** [comment]
感谢回复
我这边用了3台手机测试的 也没发现问题&nbsp;


我用的友盟上面已经提示发生了700多次这样的异常了,根据销售的反馈问题可能是体现在下载记录会丢失,就是下载视屏文件之后有记录 过两台在看就没有了,昨天开始销售这样给我反馈的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lyy"<notifications@github.com&gt;; 
发送时间: 2020年5月14日(星期四) 下午3:54
收件人: "AriaLyy/Aria"<Aria@noreply.github.com&gt;; 
抄送: "懒鱼"<592010803@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AriaLyy/Aria] 部分手机升级3.8.5报错:no such table: ThreadRecord (#670)





 
麻烦提供下有问题的数据库，我这没有复现。

**Comment by huangxiaoyu** [comment]
我看到项目历史版本中有用到3.5.4&nbsp; 有可能是这个版本直接升级3.8.5出的问题&nbsp; &nbsp;我先测试一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lyy"<notifications@github.com&gt;; 
发送时间: 2020年5月14日(星期四) 下午3:54
收件人: "AriaLyy/Aria"<Aria@noreply.github.com&gt;; 
抄送: "懒鱼"<592010803@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AriaLyy/Aria] 部分手机升级3.8.5报错:no such table: ThreadRecord (#670)





 
麻烦提供下有问题的数据库，我这没有复现。

**Comment by AriaLyy** [comment]
使用`3.8.7-beta-12`，增加了表不存在，重新创建表的操作

**Comment by huangxiaoyu** [comment]
非常感谢,昨天晚上我用3.5.4升级到3.8.5测试也没有测出来那个问题,真是奇怪了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lyy"<notifications@github.com&gt;; 
发送时间: 2020年5月14日(星期四) 晚上7:57
收件人: "AriaLyy/Aria"<Aria@noreply.github.com&gt;; 
抄送: "懒鱼"<592010803@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AriaLyy/Aria] 部分手机升级3.8.5报错:no such table: ThreadRecord (#670)





 
使用3.8.7-beta-12，增加了表不存在，重新创建表的操作

**Comment by huangxiaoyu** [comment]
友盟上还收集到一个异常,这是用户那边的手机统计到的 我这也没法测试 你看看&nbsp; 这个目前就收到2次同样的异常,是vivo x9s&nbsp; android8.1系统

java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference

&nbsp;&nbsp;&nbsp;&nbsp;at com.arialyy.aria.core.common.RecordHelper.handleSingleThreadRecord(RecordHelper.java:3)

&nbsp;&nbsp;&nbsp;&nbsp;at com.arialyy.aria.http.HttpRecordHandler.handlerTaskRecord(HttpRecordHandler.java:8)

&nbsp;&nbsp;&nbsp;&nbsp;at com.arialyy.aria.core.common.RecordHandler.getRecord(RecordHandler.java:9)

&nbsp;&nbsp;&nbsp;&nbsp;at com.arialyy.aria.core.loader.NormalLoader.startThreadTask(NormalLoader.java:6)

&nbsp;&nbsp;&nbsp;&nbsp;at com.arialyy.aria.core.loader.NormalLoader$1.onSucceed(NormalLoader.java:1)

&nbsp;&nbsp;&nbsp;&nbsp;at com.arialyy.aria.http.download.HttpDFileInfoTask.handleConnect(HttpDFileInfoTask.java:79)

&nbsp;&nbsp;&nbsp;&nbsp;at com.arialyy.aria.http.download.HttpDFileInfoTask.run(HttpDFileInfoTask.java:9)

&nbsp;&nbsp;&nbsp;&nbsp;at com.arialyy.aria.core.loader.NormalLoader.handleTask(NormalLoader.java:3)

&nbsp;&nbsp;&nbsp;&nbsp;at com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:8)

&nbsp;&nbsp;&nbsp;&nbsp;at com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:4)

&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.Thread.run(Thread.java:764)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lyy"<notifications@github.com&gt;; 
发送时间: 2020年5月14日(星期四) 晚上7:57
收件人: "AriaLyy/Aria"<Aria@noreply.github.com&gt;; 
抄送: "懒鱼"<592010803@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AriaLyy/Aria] 部分手机升级3.8.5报错:no such table: ThreadRecord (#670)





 
使用3.8.7-beta-12，增加了表不存在，重新创建表的操作

**Comment by AriaLyy** [comment]
已知问题，使用`3.8.7-beta-12`

**Comment by huangxiaoyu** [comment]
还有这个&nbsp; 这个是升级之后就发现了一次

android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: DownloadEntity.downloadPath (code 2067 SQLITE_CONSTRAINT_UNIQUE)

&nbsp;&nbsp;&nbsp;&nbsp;at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)

&nbsp;&nbsp;&nbsp;&nbsp;at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:778)

&nbsp;&nbsp;&nbsp;&nbsp;at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)

&nbsp;&nbsp;&nbsp;&nbsp;at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)

&nbsp;&nbsp;&nbsp;&nbsp;at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1669)

&nbsp;&nbsp;&nbsp;&nbsp;at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1615)

&nbsp;&nbsp;&nbsp;&nbsp;at com.arialyy.aria.orm.DelegateUpdate.updateData(DelegateUpdate.java:6)

&nbsp;&nbsp;&nbsp;&nbsp;at com.arialyy.aria.orm.DelegateWrapper.updateData(DelegateWrapper.java:1)

&nbsp;&nbsp;&nbsp;&nbsp;at com.arialyy.aria.orm.DbEntity.update(DbEntity.java:1)

&nbsp;&nbsp;&nbsp;&nbsp;at com.arialyy.aria.core.listener.BaseListener.saveData(BaseListener.java:7)

&nbsp;&nbsp;&nbsp;&nbsp;at com.arialyy.aria.core.listener.BaseListener.onPre(BaseListener.java:1)

&nbsp;&nbsp;&nbsp;&nbsp;at com.arialyy.aria.core.loader.AbsNormalLoaderUtil.start(AbsNormalLoaderUtil.java:2)

&nbsp;&nbsp;&nbsp;&nbsp;at com.arialyy.aria.core.task.AbsTask.start(AbsTask.java:12)

&nbsp;&nbsp;&nbsp;&nbsp;at com.arialyy.aria.core.queue.AbsTaskQueue.startTask(AbsTaskQueue.java:10)

&nbsp;&nbsp;&nbsp;&nbsp;at com.arialyy.aria.core.queue.AbsTaskQueue.startTask(AbsTaskQueue.java:3)

&nbsp;&nbsp;&nbsp;&nbsp;at com.arialyy.aria.core.queue.AbsTaskQueue.startTask(AbsTaskQueue.java:1)

&nbsp;&nbsp;&nbsp;&nbsp;at com.arialyy.aria.core.scheduler.TaskSchedulers.startNextTask(TaskSchedulers.java:5)

&nbsp;&nbsp;&nbsp;&nbsp;at com.arialyy.aria.core.scheduler.TaskSchedulers.handleNormalEvent(TaskSchedulers.java:15)

&nbsp;&nbsp;&nbsp;&nbsp;at com.arialyy.aria.core.scheduler.TaskSchedulers.handleMessage(TaskSchedulers.java:8)

&nbsp;&nbsp;&nbsp;&nbsp;at android.os.Handler.dispatchMessage(Handler.java:102)

&nbsp;&nbsp;&nbsp;&nbsp;at android.os.Looper.loop(Looper.java:243)

&nbsp;&nbsp;&nbsp;&nbsp;at android.app.ActivityThread.main(ActivityThread.java:7096)

&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.reflect.Method.invoke(Native Method)

&nbsp;&nbsp;&nbsp;&nbsp;at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)

&nbsp;&nbsp;&nbsp;&nbsp;at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lyy"<notifications@github.com&gt;; 
发送时间: 2020年5月16日(星期六) 上午9:43
收件人: "AriaLyy/Aria"<Aria@noreply.github.com&gt;; 
抄送: "懒鱼"<592010803@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AriaLyy/Aria] 部分手机升级3.8.5报错:no such table: ThreadRecord (#670)





 
已知问题，使用3.8.7-beta-12

**Comment by yisan** [comment]
3.5.1升级到3.8.16 也遇到了，个别设备，主要几种在5.1.1的版本，波及太大了，简直灾难级别，要命！

**Comment by yisan** [comment]
我3.5.1升级到3.8.16 也同样有这类问题：
`2022-02-24 12:41:17.566 8500-8500/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.yunzong.spacebridge, PID: 8500
    java.lang.RuntimeException: Unable to create application com.yunzong.spacebridge.BaseApplication: android.database.sqlite.SQLiteException: no such table: main.DownloadTaskEntity (code 1): , while compiling: DELETE FROM DownloadEntity WHERE downloadPath='' OR downloadPath IS NULL
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4556)
        at android.app.ActivityThread.access$1500(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
     Caused by: android.database.sqlite.SQLiteException: no such table: main.DownloadTaskEntity (code 1): , while compiling: DELETE FROM DownloadEntity WHERE downloadPath='' OR downloadPath IS NULL
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
        at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1674)
        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
        at com.arialyy.aria.orm.SqlHelper.handleLowAriaUpdate(SqlHelper.java:12)
        at com.arialyy.aria.orm.SqlHelper.onUpgrade(SqlHelper.java:1)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
        at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
        at com.arialyy.aria.orm.SqlHelper.createDbCacheDir(SqlHelper.java:6)
        at com.arialyy.aria.orm.SqlHelper.getReadableDatabase(SqlHelper.java:2)
        at com.arialyy.aria.orm.SqlHelper.getDb(SqlHelper.java:9)
        at com.arialyy.aria.orm.DelegateWrapper.<init>(DelegateWrapper.java:4)
        at com.arialyy.aria.orm.DelegateWrapper.init(DelegateWrapper.java:4)
        at com.arialyy.aria.core.AriaManager.initDb(AriaManager.java:7)
        at com.arialyy.aria.core.AriaManager.initData(AriaManager.java:2)
        at com.arialyy.aria.core.AriaManager.init(AriaManager.java:5)
        at com.arialyy.aria.core.Aria.get(Aria.java:2)
        at com.arialyy.aria.core.Aria.init(Aria.java:1)
        at com.yunzong.spacebridge.BaseApplication.onCreate(BaseApplication.java:23)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
        at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697) `
该报错也是集中在个别型号的设备上。。。这个错可把我们坑惨了，波及几千台设备。。。

**Comment by yisan** [comment]
我3.5.1升级到3.8.16 也同样有这类问题：
`2022-02-24 12:41:17.566 8500-8500/? E/AndroidRuntime: FATAL EXCEPTION: main Process: com.xxx.xxxx, PID: 8500 java.lang.RuntimeException: Unable to create application com.xxx.xxxx.BaseApplication: android.database.sqlite.SQLiteException: no such table: main.DownloadTaskEntity (code 1): , while compiling: DELETE FROM DownloadEntity WHERE downloadPath='' OR downloadPath IS NULL at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4556) at android.app.ActivityThread.access$1500(ActivityThread.java:151) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:135) at android.app.ActivityThread.main(ActivityThread.java:5254) at java.lang.reflect.Method.invoke(Native Method) at java.lang.reflect.Method.invoke(Method.java:372) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697) Caused by: android.database.sqlite.SQLiteException: no such table: main.DownloadTaskEntity (code 1): , while compiling: DELETE FROM DownloadEntity WHERE downloadPath='' OR downloadPath IS NULL at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method) at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889) at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500) at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588) at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58) at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31) at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1674) at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605) at com.arialyy.aria.orm.SqlHelper.handleLowAriaUpdate(SqlHelper.java:12) at com.arialyy.aria.orm.SqlHelper.onUpgrade(SqlHelper.java:1) at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256) at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187) at com.arialyy.aria.orm.SqlHelper.createDbCacheDir(SqlHelper.java:6) at com.arialyy.aria.orm.SqlHelper.getReadableDatabase(SqlHelper.java:2) at com.arialyy.aria.orm.SqlHelper.getDb(SqlHelper.java:9) at com.arialyy.aria.orm.DelegateWrapper.<init>(DelegateWrapper.java:4) at com.arialyy.aria.orm.DelegateWrapper.init(DelegateWrapper.java:4) at com.arialyy.aria.core.AriaManager.initDb(AriaManager.java:7) at com.arialyy.aria.core.AriaManager.initData(AriaManager.java:2) at com.arialyy.aria.core.AriaManager.init(AriaManager.java:5) at com.arialyy.aria.core.Aria.get(Aria.java:2) at com.arialyy.aria.core.Aria.init(Aria.java:1) at com.xxx.xxx.BaseApplication.onCreate(BaseApplication.java:23) at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553) at android.app.ActivityThread.access$1500(ActivityThread.java:151)  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)  at android.os.Handler.dispatchMessage(Handler.java:102)  at android.os.Looper.loop(Looper.java:135)  at android.app.ActivityThread.main(ActivityThread.java:5254)  at java.lang.reflect.Method.invoke(Native Method)  at java.lang.reflect.Method.invoke(Method.java:372)  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697) `

该报错也是集中在个别型号的设备上。。。这个错可把我们坑惨了，波及几千台设备。。。

**Comment by huangxiaoyu** [comment]
> 
我就升级那一段时间有问题返回.就赶紧又更新一板,现在用的是3.8.15 还算稳定
