### ISSUE TITLE
DownloadTask.getKey()' on a null

### ISSUE THREAD

**Issue by Zvirtuey** [AriaLyy/Aria#671]
## 版本
* 框架版本

compile('com.arialyy.aria:aria-core:3.6.6_beta_3') {
        exclude group: 'com.android.support'
    }
    annotationProcessor 'com.arialyy.aria:aria-compiler:3.6.5'

* 系统版本
 6.0
## 错误日志

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.arialyy.aria.core.download.DownloadTask.getKey()' on a null object reference
	at com.xxx.xxx.activity.LoginActivity.taskFail(LoginActivity.java:1)
	at com.xxx.xxx.activity.LoginActivity$$DownloadListenerProxy.onTaskFail(LoginActivity$$DownloadListenerProxy.java:2)
	at com.xxx.xxx.activity.LoginActivity$$DownloadListenerProxy.onTaskFail(LoginActivity$$DownloadListenerProxy.java:1)
	at com.arialyy.aria.core.scheduler.AbsSchedulers.normalTaskCallback(AbsSchedulers.java:16)
	at com.arialyy.aria.core.scheduler.AbsSchedulers.handlePreFailTask(AbsSchedulers.java:17)
	at com.arialyy.aria.core.scheduler.AbsSchedulers.handleNormalEvent(AbsSchedulers.java:1)
	at com.arialyy.aria.core.scheduler.AbsSchedulers.handleMessage(AbsSchedulers.java:7)
	at com.arialyy.aria.core.scheduler.DownloadSchedulers.handleMessage(DownloadSchedulers.java:1)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5737)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

## 重现步骤

1.
2.
3.
4.

**Comment by AriaLyy** [comment]
升级到新版本`3.8.7-beta-12`
