### ISSUE TITLE
崩溃日志

### ISSUE THREAD

**Issue by ifmvo** [AriaLyy/Aria#688]
## 版本
* aria 3.8.7

* 系统版本：小米8  android10

## 错误日志
java.lang.NullPointerException: Attempt to read from field 'boolean com.arialyy.aria.core.TaskRecord.isBlock' on a null object reference
    at com.arialyy.aria.core.group.SimpleSchedulers.handleComplete(Unknown Source:30)
    at com.arialyy.aria.core.group.SimpleSchedulers.handleMessage(Unknown Source:150)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:164)
    at com.arialyy.aria.core.group.AbsGroupLoader.startRunningFlow(Unknown Source:78)
    at com.arialyy.aria.core.group.AbsGroupLoader.run(Unknown Source:12)
    at java.lang.Thread.run(Thread.java:764)

**Comment by AriaLyy** [comment]
3.8.9 已处理了这个问题
