### ISSUE TITLE
有个广播的Log

### ISSUE THREAD

**Issue by Jasperben** [AriaLyy/Aria#689]
`2020-06-11 10:16:39.488 527-1230/system_process E/ActivityManager: Sending non-protected broadcast ARIA_TASK_INFO_ACTION from system 1535:com.oc.settings/1000 pkg com.oc.settings
    java.lang.Throwable
        at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:21453)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:22057)
        at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:22207)
        at android.app.IActivityManager$Stub.onTransact$broadcastIntent$(IActivityManager.java:10180)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:167)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3350)
        at android.os.Binder.execTransact(Binder.java:731)`

**Comment by AriaLyy** [comment]
是否是android 8.0的系统？
