### ISSUE TITLE
配置文件threadNum为1 下载失败,不会自动重试?

### ISSUE THREAD

**Issue by 1wayticket** [AriaLyy/Aria#695]
## 版本
* 框架版本 3.8.6

* 系统版本 华为Emui 10.1

## 错误日志

2020-06-16 12:01:44.135 W/System.err: com.arialyy.aria.exception.AriaHTTPException: HttpThreadTask, 文件下载失败，savePath: /storage/emulated/0/Android/data/com.example.test/cache/playbook/ffd52f3c7e12435a724a8f30fddadd9c.zip, url: xxxxxxx
2020-06-16 12:01:44.136 W/System.err:     at com.arialyy.aria.http.download.HttpDThreadTaskAdapter.readDynamicFile(HttpDThreadTaskAdapter.java:228)
2020-06-16 12:01:44.136 W/System.err:     at com.arialyy.aria.http.download.HttpDThreadTaskAdapter.handlerThreadTask(HttpDThreadTaskAdapter.java:106)
2020-06-16 12:01:44.136 W/System.err:     at com.arialyy.aria.core.task.AbsThreadTaskAdapter.call(AbsThreadTaskAdapter.java:54)
2020-06-16 12:01:44.136 W/System.err:     at com.arialyy.aria.core.task.ThreadTask.call(ThreadTask.java:543)
2020-06-16 12:01:44.137 W/System.err:     at com.arialyy.aria.core.task.ThreadTask.call(ThreadTask.java:47)

## 重现步骤

1.网络波动导致下载失败
2.触发ThreadTask fail回调
```
if (mTaskWrapper.getRequestType() == ITaskWrapper.M3U8_VOD) {
      writeConfig(false, 0);
      retryM3U8Peer(needRetry);
    } else {
      if (mTaskWrapper.isSupportBP()) {
        writeConfig(false, subCurrentLocation);
        retryBlockTask(needRetry && mConfig.startThreadNum != 1);
      } else {
        ALog.e(TAG, String.format("任务【%s】执行失败", getFileName()));
        ErrorHelp.saveError(TAG, "", ALog.getExceptionString(ex));
        sendFailMsg(null, needRetry);
      }
    }
```
retryBlockTask 因为配置的threadNum 是1所以不会重试 直接触发失败回调
请问是这样吗?

**Comment by AriaLyy** [comment]
正常来说是会重试的，我看看是什么问题

**Comment by AriaLyy** [comment]
3.8.10 已经修复了这个问题
