### ISSUE TITLE
多线程下载，网络不太好的情况下OOM

### ISSUE THREAD

**Issue by zlhuang** [AriaLyy/Aria#700]
06-22 16:54:32.202 25715-25715/com.liftcore.download_simply E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.liftcore.download_simply, PID: 25715
    java.lang.OutOfMemoryError: Could not allocate JNI Env
        at java.lang.Thread.nativeCreate(Native Method)
        at java.lang.Thread.start(Thread.java:1063)
        at com.arialyy.aria.core.loader.AbsNormalLoaderUtil.start(AbsNormalLoaderUtil.java:118)
        at com.arialyy.aria.core.task.AbsTask.start(AbsTask.java:233)
        at com.arialyy.aria.core.task.AbsTask.start(AbsTask.java:211)
        at com.arialyy.aria.core.queue.AbsTaskQueue.reTryStart(AbsTaskQueue.java:349)
        at com.arialyy.aria.core.queue.AbsTaskQueue.reTryStart(AbsTaskQueue.java:44)
        at com.arialyy.aria.core.scheduler.FailureTaskHandler$2.run(FailureTaskHandler.java:92)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5684)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
06-22 16:54:32.323 1522-2841/? E/ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ id=23, legacyType=-1, [ Transports: CELLULAR|WIFI Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
06-22 16:54:32.421 27173-27173/com.liftcore.download_simply E/CrashReport: --------------------------------------------------------------------------------------------

**Comment by zlhuang** [comment]
![Uploading 1592816865(1).jpg…]()
