### ISSUE TITLE
多线程下载时，网络不太稳定（比较差）的情况下发生OOM

### ISSUE THREAD

**Issue by zlhuang** [AriaLyy/Aria#701]
--------- beginning of crash
06-22 16:54:32.202 25715-25715/com.example.download_simply E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.liftcore.download_simply, PID: 25715
    java.lang.OutOfMemoryError: Could not allocate JNI Env
        at java.lang.Thread.nativeCreate(Native Method)
        at java.lang.Thread.start(Thread.java:1063)
        at com.arialyy.aria.core.loader.AbsNormalLoaderUtil.start(AbsNormalLoaderUtil.java:118)
        at com.arialyy.aria.core.task.AbsTask.start(AbsTask.java:233)
        at com.arialyy.aria.core.task.AbsTask.start(AbsTask.java:211)
        at com.arialyy.aria.core.queue.AbsTaskQueue.reTryStart(AbsTaskQueue.java:349)
        at com.arialyy.aria.core.queue.AbsTaskQueue.reTryStart(AbsTaskQueue.java:44)
        at com.arialyy.aria.core.scheduler.FailureTaskHandler$2.run(FailureTaskHandler.java:92)
        at android.os.Handler.handleCallback(Handler.java:742)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5684)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
06-22 16:54:32.323 1522-2841/? E/ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ id=23, legacyType=-1, [ Transports: CELLULAR|WIFI Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
06-22 16:54:32.421 27173-27173/com.example.download_simply E/CrashReport: --------------------------------------------------------------------------------------------
06-22 16:54:32.421 27173-27173/com.example.download_simply E/CrashReport: --------------------------------------------------------------------------------------------
06-22 16:54:32.753 27173-27173/com.example.download_simply E/CheckUtil: 下载失败，保存路径【/storage/emulated/0/Download/20200611001.jpg】已经被其它任务占用，请设置其它保存路径
06-22 16:54:32.757 27173-27173/com.example.download_simply E/CheckUtil: 下载失败，保存路径【/storage/emulated/0/Download/20200611002.jpg】已经被其它任务占用，请设置其它保存路径

**Comment by AriaLyy** [comment]
7.0 系统？

**Comment by zlhuang** [comment]
你好，6.0.1。还有http多任务下载，删除全部任务，再下载，多试几次后，下载速度变得很慢，但是退出app，重新进来，速度又恢复了很快。。。没有限速的
