### ISSUE TITLE
偶现异常

### ISSUE THREAD

**Issue by Zvirtuey** [AriaLyy/Aria#707]
偶现出现闪退：

2020-06-23 14:51:03:
android.database.sqlite.SQLiteException: no such column: TaskRecord.isOpenDynamicFile (code 1): , while compiling: SELECT TaskRecord.rowid AS prowid,TaskRecord.bandWidth AS pbandWidth,TaskRecord.dGroupHash AS pdGroupHash,TaskRecord.fileLength AS pfileLength,TaskRecord.fileName AS pfileName,TaskRecord.filePath AS pfilePath,TaskRecord.isBlock AS pisBlock,TaskRecord.isGroupRecord AS pisGroupRecord,TaskRecord.isOpenDynamicFile AS pisOpenDynamicFile,TaskRecord.taskType AS ptaskType,TaskRecord.threadNum AS pthreadNum,ThreadRecord.rowid AS crowid,ThreadRecord.blockLen AS cblockLen,ThreadRecord.endLocation AS cendLocation,ThreadRecord.isComplete AS cisComplete,ThreadRecord.startLocation AS cstartLocation,ThreadRecord.taskKey AS ctaskKey,ThreadRecord.threadId AS cthreadId,ThreadRecord.threadType AS cthreadType,ThreadRecord.tsUrl AS ctsUrl FROM TaskRecord INNER JOIN ThreadRecord ON TaskRecord.filePath = ThreadRecord.taskKey WHERE TaskRecord.filePath='%2Fstorage%2Femulated%2F0%2FR_Client%2FInternal5.0.1.test.apk'
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:896)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:507)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1346)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1285)
	at com.arialyy.aria.orm.DelegateFind.exeRelationSql(DelegateFind.java:61)
	at com.arialyy.aria.orm.DelegateFind.findRelationData(DelegateFind.java:1)
	at com.arialyy.aria.orm.DelegateWrapper.findRelationData(DelegateWrapper.java:1)
	at com.arialyy.aria.orm.DbEntity.findRelationData(DbEntity.java:1)
	at com.arialyy.aria.util.DbDataHelper.getTaskRecord(DbDataHelper.java:2)
	at com.arialyy.aria.core.common.RecordHandler.getRecord(RecordHandler.java:4)
	at com.arialyy.aria.core.common.AbsFileer.startFlow(AbsFileer.java:4)
	at com.arialyy.aria.core.common.AbsFileer.run(AbsFileer.java:2)
	at java.lang.Thread.run(Thread.java:818)

**Comment by AriaLyy** [comment]
哪一个版本的？

**Comment by Zvirtuey** [comment]
有点忘了，3.6.6还是3.8.9的，这个是偶现的问题，之前用3.6.6因为有下面这个问题：所以才换成3.8.9，上面问题好像是换之后后偶现出现的，应该是3.8.9的！ 

3.6.6 版本日志：
06-22 18:22:46.143 12771-13077/com.rzt.internal V/SQLiteCursor: Cursor open object=57368349
    java.lang.Throwable: stacktrace
        at android.database.sqlite.SQLiteCursor.<init>(SQLiteCursor.java:117)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:50)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1346)
        at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1285)
        at com.arialyy.aria.orm.DelegateCommon.checkDataExist(DelegateCommon.java:9)
        at com.arialyy.aria.orm.DelegateWrapper.checkDataExist(DelegateWrapper.java:2)
        at com.arialyy.aria.orm.DbEntity.checkDataExist(DbEntity.java:1)
        at com.arialyy.aria.core.download.DNormalConfigHandler.checkFilePath(DNormalConfigHandler.java:17)
        at com.arialyy.aria.core.download.DNormalConfigHandler.checkEntity(DNormalConfigHandler.java:1)
        at com.arialyy.aria.core.download.DownloadTarget.checkEntity(DownloadTarget.java:1)
        at com.arialyy.aria.core.inf.AbsTarget.checkConfig(AbsTarget.java:1)
        at com.arialyy.aria.core.inf.AbsTarget.start(AbsTarget.java:1)
        at com.rzt.internal.activity.LoginActivity$7$1.accept(LoginActivity.java:11)
        at com.rzt.internal.activity.LoginActivity$7$1.accept(LoginActivity.java:1)
        at c.a.m.e.a.d$a.onNext(ObservableDoOnEach.java:2)
        at c.a.m.e.a.l.run(ObservableScalarXMap.java:2)
        at c.a.m.e.a.i.b(ObservableJust.java:3)
        at c.a.d.a(Observable.java:41)
        at c.a.m.e.a.d.b(ObservableDoOnEach.java:1)
        at c.a.d.a(Observable.java:41)
        at c.a.m.e.a.m$b.run(ObservableSubscribeOn.java:1)
        at c.a.g$a.run(Scheduler.java:2)
        at c.a.m.g.i.run(ScheduledRunnable.java:2)
        at c.a.m.g.i.call(ScheduledRunnable.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
06-22 18:22:46.145 12771-13077/com.rzt.internal I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
06-22 18:22:46.146 12771-13077/com.rzt.internal V/SQLiteStatements: /data/user/0/com.rzt.internal/databases/AndroidAria.db: "SELECT rowid, * FROM DownloadEntity WHERE downloadPath='%2Fstorage%2Femulated%2F0%2FR_Client%2FInternal5.0.0.1092-20200619-beta.apk'"
06-22 18:22:46.146 12771-13077/com.rzt.internal V/SQLiteTime: /data/user/0/com.rzt.internal/databases/AndroidAria.db: "SELECT rowid, * FROM DownloadEntity WHERE downloadPath='%2Fstorage%2Femulated%2F0%2FR_Client%2FInternal5.0.0.1092-20200619-beta.apk'" took 1.000 ms
06-22 18:22:46.146 12771-13077/com.rzt.internal D/SQLiteCursor: received count(*) from native_fill_window: 1
06-22 18:22:46.146 12771-13077/com.rzt.internal V/SQLiteCursor: Cursor close object=57368349
06-22 18:22:46.147 12771-13077/com.rzt.internal E/DNormalDelegate: 下载失败，保存路径【/storage/emulated/0/R_Client/xxx.apk】已经被其它任务占用，请设置其它保存路径
