### ISSUE TITLE
m3u8格式无法下载问题

### ISSUE THREAD

**Issue by Zmydhy** [AriaLyy/Aria#717]
http://mgjx.awu1k.cn:8000/parse/player.m3u8?target=eb2d3ca5198516269cf356463be86573
爱奇艺的资源，通过解析获取到了

#EXTM3U
#EXT-X-TARGETDURATION:10
#EXTINF:9,
http://data.video.iqiyi.com/videos/vts/20200711/95/66/e138aa7a88848634331f0aa5b895ecb1.ts?start=0&end=1188724&contentlength=1188724&sd=0&qdv=1&qd_uid=1474789841&qd_tvid=532785500&qd_vip=1&qd_src=01010031010000000000&qd_tm=1595404825925&qd_ip=0&qd_p=0&qd_k=376e6cdaaf386ecbd95d3e22b8a59e55&ve=&sgti=14_5736859c39dcd6cc59ae4243475b3629_1595404822609&dfp=&qd_sc=66ec00423c843487cbf28f511d708252
#EXTINF:9,
http://data.video.iqiyi.com/videos/vts/20200711/95/66/e138aa7a88848634331f0aa5b895ecb1.ts?start=1188724&end=2760404&contentlength=1571680&sd=9000&qdv=1&qd_uid=1474789841&qd_tvid=532785500&qd_vip=1&qd_src=01010031010000000000&qd_tm=1595404825925&qd_ip=0&qd_p=0&qd_k=376e6cdaaf386ecbd95d3e22b8a59e55&ve=&sgti=14_5736859c39dcd6cc59ae4243475b3629_1595404822609&dfp=&qd_sc=66ec00423c843487cbf28f511d708252
#EXTINF:9,
http://data.video.iqiyi.com/videos/vts/20200711/95/66/e138aa7a88848634331f0aa5b895ecb1.ts?start=2760404&end=5468732&contentlength=2708328&sd=18000&qdv=1&qd_uid=1474789841&qd_tvid=532785500&qd_vip=1&qd_src=01010031010000000000&qd_tm=1595404825925&qd_ip=0&qd_p=0&qd_k=376e6cdaaf386ecbd95d3e22b8a59e55&ve=&sgti=14_5736859c39dcd6cc59ae4243475b3629_1595404822609&dfp=&qd_sc=66ec00423c843487cbf28f511d708252
#EXTINF:9,
http://data.video.iqiyi.com/videos/vts/20200711/95/66/e138aa7a88848634331f0aa5b895ecb1.ts?start=5468732&end=10031680&contentlength=4562948&sd=26920&qdv=1&qd_uid=1474789841&qd_tvid=532785500&qd_vip=1&qd_src=01010031010000000000&qd_tm=1595404825925&qd_ip=0&qd_p=0&qd_k=376e6cdaaf386ecbd95d3e22b8a59e55&ve=&sgti=14_5736859c39dcd6cc59ae4243475b3629_1595404822609&dfp=&qd_sc=66ec00423c843487cbf28f511d708252
#EXTINF:4,
http://data.video.iqiyi.com/videos/vts/20200711/95/66/e138aa7a88848634331f0aa5b895ecb1.ts?start=10031680&end=10346204&contentlength=314524&sd=35920&qdv=1&qd_uid=1474789841&qd_tvid=532785500&qd_vip=1&qd_src=01010031010000000000&qd_tm=1595404825925&qd_ip=0&qd_p=0&qd_k=376e6cdaaf386ecbd95d3e22b8a59e55&ve=&sgti=14_5736859c39dcd6cc59ae4243475b3629_1595404822609&dfp=&qd_sc=66ec00423c843487cbf28f511d708252
#EXTINF:7,
http://data.video.iqiyi.com/videos/vts/20200711/95/66/e138aa7a88848634331f0aa5b895ecb1.ts?start=10346204&end=10588724&contentlength=242520&sd=39600&qdv=1&qd_uid=1474789841&qd_tvid=532785500&qd_vip=1&qd_src=01010031010000000000&qd_tm=1595404825925&qd_ip=0&qd_p=0&qd_k=376e6cdaaf386ecbd95d3e22b8a59e55&ve=&sgti=14_5736859c39dcd6cc59ae4243475b3629_1595404822609&dfp=&qd_sc=66ec00423c843487cbf28f511d708252
#EXTINF:9,
http://data.video.iqiyi.com/videos/vts/20200711/95/66/e138aa7a88848634331f0aa5b895ecb1.ts?start=10588724&end=11327188&contentlength=738464&sd=46320&qdv=1&qd_uid=1474789841&qd_tvid=532785500&qd_vip=1&qd_src=01010031010000000000&qd_tm=1595404825925&qd_ip=0&qd_p=0&qd_k=376e6cdaaf386ecbd95d3e22b8a59e55&ve=&sgti=14_5736859c39dcd6cc59ae4243475b3629_1595404822609&dfp=&qd_sc=66ec00423c843487cbf28f511d708252

这种资源  为什么不能下载呢

**Comment by AriaLyy** [comment]
需要自己定义转换器：https://github.com/AriaLyy/Aria/issues/597 ，转换器直接返回地址便可

**Comment by Zmydhy** [comment]
object  VodTsUrlConverter : IVodTsUrlConverter{
        override fun convert(m3u8Url: String?, tsUrls: MutableList<String>?): MutableList<String> {
            // 转换ts文件的url地址

            // 转换ts文件的url地址
            val uri = Uri.parse(m3u8Url)
            val parentUrl = "http://" + uri.host
            val newUrls: MutableList<String> = java.util.ArrayList()
            for (url in tsUrls!!) {
                newUrls.add(parentUrl + url)
            }

            return newUrls // 返回有效的ts文件url集合

        }


使用：
                   val option = M3U8VodOption()
                            option.merge(true)
                            option.setUseDefConvert(false);
                            option.setVodTsUrlConvert(VodTsUrlConverter)


然而 并没有走这个转换器。我怀疑是m3u8文件没下载成功，请问 m3u8源文件存放路径在哪里？

**Comment by AriaLyy** [comment]
是否使用了`.m3u8VodOption(option)`，没有的话，加上

**Comment by Zmydhy** [comment]
你们   按照你写的  并且确认添加的option，
获取的地址依然是的
![image](https://user-images.githubusercontent.com/9899249/88245461-ddce5080-ccc9-11ea-8a2c-baafcc1bd431.png)
并且在转换器中的log日志没有打印

**Comment by Zmydhy** [comment]
我的源码如下：     
val option = M3U8VodOption()
                            option.setUseDefConvert(false);
                            option.setVodTsUrlConvert(VodTsUrlConverter)
                            //创建拓展信息
                            val downloadExt = DownloadExt()
                            downloadExt.thumb = img
                            val gson = Gson()
                            val toJson = gson.toJson(downloadExt)
                            val fileUrl = body?.url
                            val taskId = Aria.download(this@DownloadVideoActivity)
                                    .load(fileUrl)
                                    .setFilePath(path, true)
                                    .m3u8VodOption(option)
                                    .create()
                            //保存拓展字段
                            Aria.download(this).load(taskId).setExtendField(toJson).save()

**Comment by Zmydhy** [comment]
日志文件如下：
2020-07-23 09:55:42.897 29593-29593/com.video.meng.guo W/CheckUtil: 保存路径【/storage/emulated/0/mg_video/后来的我们*蓝光-42107.m3u8】已经被其它任务占用，当前任务将覆盖该路径的文件
2020-07-23 09:55:42.986 29593-29593/com.video.meng.guo W/CheckDEntityUtil: 由于m3u8协议的特殊性质，无法有效快速获取到正确到文件长度，如果你需要显示文件中长度，你需要自行设置文件长度：.asM3U8().asVod().setFileSize(xxx)
2020-07-23 09:55:42.987 29593-30464/com.video.meng.guo I/DTaskQueue: 获取任务，key：http://mgjx.awu1k.cn:8000/parse/player.m3u8?target=d9d5a9c43a67c443e93153a175ed4b15
2020-07-23 09:55:42.987 29593-30464/com.video.meng.guo I/DTaskQueue: 获取任务，key：http://mgjx.awu1k.cn:8000/parse/player.m3u8?target=d9d5a9c43a67c443e93153a175ed4b15
2020-07-23 09:55:42.987 29593-30464/com.video.meng.guo I/DTaskQueue: 添加任务，key：http://mgjx.awu1k.cn:8000/parse/player.m3u8?target=d9d5a9c43a67c443e93153a175ed4b15
2020-07-23 09:55:42.992 29593-29593/com.video.meng.guo I/NormalController: 保存成功
2020-07-23 09:55:43.006 29593-29593/com.video.meng.guo I/Toast: Show toast from OpPackageName:com.video.meng.guo, PackageName:com.video.meng.guo
2020-07-23 09:55:44.088 29593-32035/com.video.meng.guo W/System.err: com.arialyy.aria.exception.AriaM3U8Exception: Aria M3U8 Exception:
2020-07-23 09:55:44.088 29593-32035/com.video.meng.guo W/System.err: 连接错误，http错误码：404，url：http://mgjx.awu1k.cn:8000/parse/http://data.video.iqiyi.com/videos/vts/20200630/27/f3/e56a4a9cafacf92dbf1e0193b032e2a9.ts?start=0&end=755384&contentlength=755384&sd=0&qdv=1&qd_uid=1474789841&qd_tvid=877693800&qd_vip=1&qd_src=01010031010000000000&qd_tm=1595464869002&qd_ip=0&qd_p=0&qd_k=c8e84bbb8ce62dab6dcea17f4234a363&ve=&sgti=14_5736859c39dcd6cc59ae4243475b3629_1595464865512&dfp=&qd_sc=eb34016cd96f3e477613f1ae6d195131
2020-07-23 09:55:44.089 29593-32035/com.video.meng.guo W/System.err:     at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handleConn(M3U8ThreadTaskAdapter.java:141)
2020-07-23 09:55:44.089 29593-32035/com.video.meng.guo W/System.err:     at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handlerThreadTask(M3U8ThreadTaskAdapter.java:92)
2020-07-23 09:55:44.089 29593-32035/com.video.meng.guo W/System.err:     at com.arialyy.aria.core.task.AbsThreadTaskAdapter.call(AbsThreadTaskAdapter.java:54)
2020-07-23 09:55:44.089 29593-32035/com.video.meng.guo W/System.err:     at com.arialyy.aria.core.task.ThreadTask.call(ThreadTask.java:544)
2020-07-23 09:55:44.089 29593-32035/com.video.meng.guo W/System.err:     at com.arialyy.aria.core.task.ThreadTask.call(ThreadTask.java:48)
2020-07-23 09:55:44.089 29593-32035/com.video.meng.guo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-07-23 09:55:44.089 29593-32035/com.video.meng.guo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-07-23 09:55:44.089 29593-32035/com.video.meng.guo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-07-23 09:55:44.089 29593-32035/com.video.meng.guo W/System.err:     at java.lang.Thread.run(Thread.java:919)
2020-07-23 09:55:44.122 29593-32038/com.video.meng.guo W/System.err: com.arialyy.aria.exception.AriaM3U8Exception: Aria M3U8 Exception:
2020-07-23 09:55:44.122 29593-32038/com.video.meng.guo W/System.err: 连接错误，http错误码：404，url：http://mgjx.awu1k.cn:8000/parse/http://data.video.iqiyi.com/videos/vts/20200630/27/f3/e56a4a9cafacf92dbf1e0193b032e2a9.ts?start=2143764&end=7002060&contentlength=4858296&sd=16166&qdv=1&qd_uid=1474789841&qd_tvid=877693800&qd_vip=1&qd_src=01010031010000000000&qd_tm=1595464869002&qd_ip=0&qd_p=0&qd_k=c8e84bbb8ce62dab6dcea17f4234a363&ve=&sgti=14_5736859c39dcd6cc59ae4243475b3629_1595464865512&dfp=&qd_sc=eb34016cd96f3e477613f1ae6d195131
2020-07-23 09:55:44.122 29593-32038/com.video.meng.guo W/System.err:     at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handleConn(M3U8ThreadTaskAdapter.java:141)
2020-07-23 09:55:44.123 29593-32038/com.video.meng.guo W/System.err:     at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handlerThreadTask(M3U8ThreadTaskAdapter.java:92)
2020-07-23 09:55:44.123 29593-32038/com.video.meng.guo W/System.err:     at com.arialyy.aria.core.task.AbsThreadTaskAdapter.call(AbsThreadTaskAdapter.java:54)
2020-07-23 09:55:44.123 29593-32038/com.video.meng.guo W/System.err:     at com.arialyy.aria.core.task.ThreadTask.call(ThreadTask.java:544)
2020-07-23 09:55:44.123 29593-32038/com.video.meng.guo W/System.err:     at com.arialyy.aria.core.task.ThreadTask.call(ThreadTask.java:48)
2020-07-23 09:55:44.123 29593-32038/com.video.meng.guo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-07-23 09:55:44.123 29593-32038/com.video.meng.guo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-07-23 09:55:44.123 29593-32038/com.video.meng.guo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-07-23 09:55:44.123 29593-32038/com.video.meng.guo W/System.err:     at java.lang.Thread.run(Thread.java:919)
2020-07-23 09:55:44.137 29593-32037/com.video.meng.guo W/System.err: com.arialyy.aria.exception.AriaM3U8Exception: Aria M3U8 Exception:
2020-07-23 09:55:44.137 29593-32037/com.video.meng.guo W/System.err: 连接错误，http错误码：404，url：http://mgjx.awu1k.cn:8000/parse/http://data.video.iqiyi.com/videos/vts/20200630/27/f3/e56a4a9cafacf92dbf1e0193b032e2a9.ts?start=755384&end=2143764&contentlength=1388380&sd=8958&qdv=1&qd_uid=1474789841&qd_tvid=877693800&qd_vip=1&qd_src=01010031010000000000&qd_tm=1595464869002&qd_ip=0&qd_p=0&qd_k=c8e84bbb8ce62dab6dcea17f4234a363&ve=&sgti=14_5736859c39dcd6cc59ae4243475b3629_1595464865512&dfp=&qd_sc=eb34016cd96f3e477613f1ae6d195131
2020-07-23 09:55:44.137 29593-32037/com.video.meng.guo W/System.err:     at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handleConn(M3U8ThreadTaskAdapter.java:141)
2020-07-23 09:55:44.137 29593-32037/com.video.meng.guo W/System.err:     at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handlerThreadTask(M3U8ThreadTaskAdapter.java:92)
2020-07-23 09:55:44.137 29593-32037/com.video.meng.guo W/System.err:     at com.arialyy.aria.core.task.AbsThreadTaskAdapter.call(AbsThreadTaskAdapter.java:54)
2020-07-23 09:55:44.137 29593-32037/com.video.meng.guo W/System.err:     at com.arialyy.aria.core.task.ThreadTask.call(ThreadTask.java:544)
2020-07-23 09:55:44.137 29593-32037/com.video.meng.guo W/System.err:     at com.arialyy.aria.core.task.ThreadTask.call(ThreadTask.java:48)
2020-07-23 09:55:44.137 29593-32037/com.video.meng.guo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-07-23 09:55:44.137 29593-32037/com.video.meng.guo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-07-23 09:55:44.137 29593-32037/com.video.meng.guo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-07-23 09:55:44.137 29593-32037/com.video.meng.guo W/System.err:     at java.lang.Thread.run(Thread.java:919)
2020-07-23 09:55:44.138 29593-32039/com.video.meng.guo W/System.err: com.arialyy.aria.exception.AriaM3U8Exception: Aria M3U8 Exception:
2020-07-23 09:55:44.138 29593



请问文件长度一般设置多少，或者怎么获取

**Comment by AriaLyy** [comment]
框架版本是多少？我测试是可以的，m3u8无法获取总长度
![image](https://user-images.githubusercontent.com/10437293/88245964-98128780-cccb-11ea-8a28-a9d6dc0642c3.png)

**Comment by Zmydhy** [comment]
3.8.9

**Comment by Zmydhy** [comment]
升级到3.8.10后 问题解决 谢谢
