### ISSUE TITLE
M3u8点播下载（带码率），对应的key下载失败

### ISSUE THREAD

**Issue by pys200603027** [AriaLyy/Aria#738]
你好作者，感谢提供好用的下载库，现在使用过程遇到关于key下载失败，有两个疑问

1. 设置`M3u8BandWidthUrlConerter`之后不生效，是不是需要设置`setBandWidth`?
不过没有拿到m3u8文件之前，对应下载文件的BandWidth不知道是啥

2.  Aria会默认选中第一个码进行下载，但是对应的key地址没有转换，因此通过`M3u8KeyConverter`拼接到的地址，是不正确的

## 版本
* 框架版本 (3.8.10)

* 系统版本 (Android 9)

日志对应如下
## 错误日志
```
E/CheckUtil: 为了防止内存泄漏，请使用静态的成员类(public static class M3u8BandWidthUrlConerter)或文件类(M3u8BandWidthUrlConerter.java)
E/CheckUtil: 为了防止内存泄漏，请使用静态的成员类(public static class M3u8Converter)或文件类(M3u8Converter.java)
E/CheckUtil: 为了防止内存泄漏，请使用静态的成员类(public static class M3u8KeyConerter)或文件类(M3u8KeyConerter.java)
W/CheckDEntityUtil: 由于m3u8协议的特殊性质，无法有效快速获取到正确到文件长度，如果你需要显示文件中长度，你需要自行设置文件长度：.asM3U8().asVod().setFileSize(xxx)
W/CheckDEntityUtil: 你已经设置了码率url转换器，但是没有设置码率，Aria框架将采用第一个获取到的码率
I/DTaskQueue: 获取任务，key：http://192.168.2.1/20200401/dEmIjpgl/index.m3u8?wsSecret=723de0b3e1a1d221742843a8c0014a89&wsTime=1597568115
D/BaseCachePool: 任务【5BF134538837B35D.m3u8】进入缓存队列成功
D/StartCmd: 开始新任务, 任务状态：3
I/DTaskQueue: 添加任务，key：http://192.168.2.1/20200401/dEmIjpgl/index.m3u8wsSecret=723de0b3e1a1d221742843a8c0014a89&wsTime=1597568115
D/DLoadExecutePool: 任务【5BF134538837B35D.m3u8】进入执行队列成功
D/M3U8InfoThread: #EXTM3U
D/M3U8InfoThread: #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1205000,RESOLUTION=1920x1080
D/M3U8InfoThread: 新码率url：http://192.168.2.1/20200401/dEmIjpgl/hls/index.m3u8?wsSecret=723de0b3e1a1d221742843a8c0014a89&wsTime=1597568115
D/M3U8InfoThread: #EXTM3U
D/M3U8InfoThread: #EXT-X-VERSION:3
D/M3U8InfoThread: #EXT-X-TARGETDURATION:10
D/M3U8InfoThread: #EXT-X-MEDIA-SEQUENCE:0
D/M3U8InfoThread: #EXT-X-KEY:METHOD=AES-128,URI="key.key"
D/M3U8InfoThread: 密钥不存在，下载密钥
W/System.err: java.io.FileNotFoundException: http://192.168.2.1/20200401/dEmIjpgl/key.key
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
W/System.err:     at com.arialyy.aria.m3u8.M3U8InfoTask.downloadKey(M3U8InfoTask.java:390)
W/System.err:     at com.arialyy.aria.m3u8.M3U8InfoTask.getKeyInfo(M3U8InfoTask.java:276)
W/System.err:     at com.arialyy.aria.m3u8.M3U8InfoTask.handleConnect(M3U8InfoTask.java:184)
W/System.err:     at com.arialyy.aria.m3u8.M3U8InfoTask.handleBandWidth(M3U8InfoTask.java:352)
W/System.err:     at com.arialyy.aria.m3u8.M3U8InfoTask.handleConnect(M3U8InfoTask.java:175)
W/System.err:     at com.arialyy.aria.m3u8.M3U8InfoTask.run(M3U8InfoTask.java:104)
W/System.err:     at com.arialyy.aria.m3u8.vod.M3U8VodLoader.handleTask(M3U8VodLoader.java:145)
W/System.err:     at com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:133)
W/System.err:     at com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:115)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
D/M3U8InfoThread: #EXTINF:6.25,
D/M3U8InfoThread: k7ZdOh6N.ts?wsSecret=723de0b3e1a1d221742843a8c0014a89&wsTime=1597568115
D/M3U8InfoThread: #EXTINF:6.125,
D/M3U8InfoThread: eC9pb83B.ts?wsSecret=723de0b3e1a1d221742843a8c0014a89&wsTime=1597568115
```

**Comment by AriaLyy** [comment]
`M3u8BandWidthUrlConerter `是不需要设置bandwith的，这个是用于获取二级`m3u8`（也就是多码率的m3u8），并且只有当设置`setUseDefConvert(false)`才会生效。

升级到3.8.12，key的转换器已经增加了m3u8主地址`String m3u8Url`
```
/**
 * M3U8 密钥下载地址处理器，可用于解密被加密的密钥的下载地址
 */
public interface IKeyUrlConverter extends IEventHandler {

  /**
   * 将被加密的密钥下载地址转换为可使用的http下载地址
   *
   * @param m3u8Url 主m3u8的url地址
   * @param tsListUrl m3u8切片列表url地址
   * @param keyUrl 加密的url地址
   * @return 可正常访问的http地址
   */
  String convert(String m3u8Url, String tsListUrl, String keyUrl);
}
```

**Comment by pys200603027** [comment]
好的非常感谢！

**Comment by pys200603027** [comment]
升级`3.8.12`后发现，下载的时候直接报错

### 错误日志
```
2020-08-17 16:00:56.021 5162-5596/com.sample D/OkHttp: <-- END HTTP (268-byte body)
2020-08-17 16:00:56.022 5162-5596/com.sample E/CheckUtil: 为了防止内存泄漏，请使用静态的成员类(public static class M3u8BandWidthUrlConerter)或文件类(M3u8BandWidthUrlConerter.java)
2020-08-17 16:00:56.023 5162-5596/com.sample E/CheckUtil: 为了防止内存泄漏，请使用静态的成员类(public static class M3u8Converter)或文件类(M3u8Converter.java)
2020-08-17 16:00:56.023 5162-5596/com.sample E/CheckUtil: 为了防止内存泄漏，请使用静态的成员类(public static class M3u8KeyConerter)或文件类(M3u8KeyConerter.java)
2020-08-17 16:00:56.029 5162-5495/com.sample V/ViewRootImpl[PlayActivity]: Resizing android.view.ViewRootImpl@d196dc0: frame=[36,1057][1044,1391] contentInsets=[0,0][0,0] visibleInsets=[0,0][0,0] reportDraw=true backDropFrame=Rect(36, 1057 - 1044, 1391)
2020-08-17 16:00:56.037 5162-5596/com.sample W/CheckDEntityUtil: 由于m3u8协议的特殊性质，无法有效快速获取到正确到文件长度，如果你需要显示文件中长度，你需要自行设置文件长度：.asM3U8().asVod().setFileSize(xxx)
2020-08-17 16:00:56.037 5162-5596/com.sample W/CheckDEntityUtil: 你已经设置了码率url转换器，但是没有设置码率，Aria框架将采用第一个获取到的码率
2020-08-17 16:00:56.039 5162-5733/com.sample I/DTaskQueue: 获取任务，key：http://192.168.2.1/20200401/6EI3b83w/index.m3u8?wsSecret=0bdbf6072f7bc0050b76402d8597ba0f&wsTime=1597654731
2020-08-17 16:00:56.040 5162-5733/com.sample W/System.err: java.lang.reflect.InvocationTargetException
2020-08-17 16:00:56.040 5162-5733/com.sample W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-08-17 16:00:56.040 5162-5733/com.sample W/System.err:     at com.arialyy.aria.core.event.EventMsgUtil$2.run(EventMsgUtil.java:71)
2020-08-17 16:00:56.040 5162-5733/com.sample W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
2020-08-17 16:00:56.040 5162-5733/com.sample W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-08-17 16:00:56.040 5162-5733/com.sample W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-08-17 16:00:56.041 5162-5733/com.sample W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-08-17 16:00:56.041 5162-5733/com.sample W/System.err:     at java.lang.Thread.run(Thread.java:764)
2020-08-17 16:00:56.041 5162-5733/com.sample W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
2020-08-17 16:00:56.041 5162-5733/com.sample W/System.err:     at com.arialyy.aria.util.AriaServiceLoader$LazyLoader.loadService(AriaServiceLoader.java:180)
2020-08-17 16:00:56.041 5162-5733/com.sample W/System.err:     at com.arialyy.aria.util.AriaServiceLoader$LazyLoader.access$100(AriaServiceLoader.java:77)
2020-08-17 16:00:56.041 5162-5733/com.sample W/System.err:     at com.arialyy.aria.util.AriaServiceLoader.getService(AriaServiceLoader.java:74)
2020-08-17 16:00:56.041 5162-5733/com.sample W/System.err:     at com.arialyy.aria.util.ComponentUtil.buildListener(ComponentUtil.java:184)
2020-08-17 16:00:56.041 5162-5733/com.sample W/System.err:     at com.arialyy.aria.core.task.DownloadTask.<init>(DownloadTask.java:38)
2020-08-17 16:00:56.041 5162-5733/com.sample W/System.err:     at com.arialyy.aria.core.task.DownloadTask.<init>(DownloadTask.java:31)
2020-08-17 16:00:56.041 5162-5733/com.sample W/System.err:     at com.arialyy.aria.core.task.DownloadTask$Builder.build(DownloadTask.java:96)
2020-08-17 16:00:56.041 5162-5733/com.sample W/System.err:     at com.arialyy.aria.core.queue.TaskFactory.createDownloadTask(TaskFactory.java:102)
2020-08-17 16:00:56.041 5162-5733/com.sample W/System.err:     at com.arialyy.aria.core.queue.TaskFactory.createTask(TaskFactory.java:62)
2020-08-17 16:00:56.041 5162-5733/com.sample W/System.err:     at com.arialyy.aria.core.queue.DTaskQueue.createTask(DTaskQueue.java:114)
2020-08-17 16:00:56.041 5162-5733/com.sample W/System.err:     at com.arialyy.aria.core.queue.DTaskQueue.createTask(DTaskQueue.java:37)
2020-08-17 16:00:56.041 5162-5733/com.sample W/System.err:     at com.arialyy.aria.core.command.AbsNormalCmd.createTask(AbsNormalCmd.java:185)
2020-08-17 16:00:56.041 5162-5733/com.sample W/System.err:     at com.arialyy.aria.core.command.StartCmd.executeCmd(StartCmd.java:64)
2020-08-17 16:00:56.041 5162-5733/com.sample W/System.err:     at com.arialyy.aria.core.command.CommandManager.start(CommandManager.java:53)
2020-08-17 16:00:56.041 5162-5733/com.sample W/System.err: 	... 7 more
```

**Comment by AriaLyy** [comment]
如何复现的？我这测试没有这个情况？反编译apk看看，`meta-inf`配置中是否有下面两个文件，看看里面的内容是否为空
![image](https://user-images.githubusercontent.com/10437293/90375491-9dcf7300-e0a7-11ea-8d1a-5150cc72967a.png)

**Comment by pys200603027** [comment]
> 如何复现的？我这测试没有这个情况？反编译apk看看，`meta-inf`配置中是否有下面两个文件，看看里面的内容是否为空
> ![image](https://user-images.githubusercontent.com/10437293/90375491-9dcf7300-e0a7-11ea-8d1a-5150cc72967a.png)

应该是开启混淆导致的，混淆后这个目录下的两个文件都没有
