### ISSUE TITLE
开启混淆后，无法获取到ConvertSpeed()

### ISSUE THREAD

**Issue by pys200603027** [AriaLyy/Aria#739]
如题，开启混淆后，无法获取到`ConvertSpeed()`

`proguard-rules.pro` 混淆加入代码
```
#Aria
-dontwarn com.arialyy.aria.**
-keep class com.arialyy.aria.**{*;}
-keep class **$$DownloadListenerProxy{ *; }
-keep class **$$UploadListenerProxy{ *; }
-keep class **$$DownloadGroupListenerProxy{ *; }
-keep class **$$DGSubListenerProxy{ *; }
-keepclasseswithmembernames class * {
    @Download.* <methods>;
    @Upload.* <methods>;
    @DownloadGroup.* <methods>;
}
```

`build.gradle` 中开启混淆

```
buildTypes {
        release {
            minifyEnabled true
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        debug {
            minifyEnabled true
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
```

## 版本
* 框架版本 （3.8.10）

* 系统版本 （Android 9）

## 错误日志

打印代码
```
@Download.onTaskRunning
    void taskRunning(DownloadTask task) {
        DownloadEntity downloadEntity = task.getDownloadEntity();
        KLog.a("speech:" + downloadEntity.getSpeed() + ",cover:" + downloadEntity.getConvertSpeed());
        downloadStateAdapter.updateProgress(task.getEntity());
    }
```
打印结果

```
E/DownloadStateActivity.java: [ (DownloadStateActivity.java:178)#taskRunning ] speech:2055717,cover:null

```

**Comment by pys200603027** [comment]
补充: 
混淆后，Application中`Aira.init`的时候会报错

日志如下：
```
2020-08-16 17:25:18.631 19485-19530/com.sample W/System.err: java.io.InvalidClassException: com.arialyy.aria.core.config.BaseConfig; local class incompatible: stream classdesc serialVersionUID = -8016187050214963100, local class serialVersionUID = 1778669418760082663
2020-08-16 17:25:18.632 19485-19530/com.sample W/System.err:     at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:625)
2020-08-16 17:25:18.632 19485-19530/com.sample W/System.err:     at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1625)
2020-08-16 17:25:18.632 19485-19530/com.sample W/System.err:     at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1520)
2020-08-16 17:25:18.632 19485-19530/com.sample W/System.err:     at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1625)
2020-08-16 17:25:18.632 19485-19530/com.sample W/System.err:     at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1520)
2020-08-16 17:25:18.633 19485-19530/com.sample W/System.err:     at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1625)
2020-08-16 17:25:18.633 19485-19530/com.sample W/System.err:     at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1520)
2020-08-16 17:25:18.633 19485-19530/com.sample W/System.err:     at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1776)
2020-08-16 17:25:18.633 19485-19530/com.sample W/System.err:     at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
2020-08-16 17:25:18.633 19485-19530/com.sample W/System.err:     at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
2020-08-16 17:25:18.633 19485-19530/com.sample W/System.err:     at com.arialyy.aria.util.FileUtil.readObjFromFile(FileUtil.java:298)
2020-08-16 17:25:18.633 19485-19530/com.sample W/System.err:     at com.arialyy.aria.core.config.Configuration.<init>(Configuration.java:69)
2020-08-16 17:25:18.633 19485-19530/com.sample W/System.err:     at com.arialyy.aria.core.config.Configuration.getInstance(Configuration.java:79)
2020-08-16 17:25:18.633 19485-19530/com.sample W/System.err:     at com.arialyy.aria.core.AriaConfig.initConfig(AriaConfig.java:193)
2020-08-16 17:25:18.633 19485-19530/com.sample W/System.err:     at com.arialyy.aria.core.AriaConfig.initData(AriaConfig.java:93)
2020-08-16 17:25:18.633 19485-19530/com.sample W/System.err:     at com.arialyy.aria.core.AriaConfig.init(AriaConfig.java:74)
2020-08-16 17:25:18.633 19485-19530/com.sample W/System.err:     at com.arialyy.aria.core.AriaManager.initData(AriaManager.java:116)
2020-08-16 17:25:18.634 19485-19530/com.sample W/System.err:     at com.arialyy.aria.core.AriaManager.init(AriaManager.java:108)
2020-08-16 17:25:18.634 19485-19530/com.sample W/System.err:     at com.arialyy.aria.core.Aria.get(Aria.java:117)
2020-08-16 17:25:18.634 19485-19530/com.sample W/System.err:     at com.arialyy.aria.core.Aria.init(Aria.java:127)
```

**Comment by AriaLyy** [comment]
混淆配置是怎么写的？

**Comment by pys200603027** [comment]
```
#Aria
-dontwarn com.arialyy.aria.**
-keep class com.arialyy.aria.**{
*;
}
-keep class **$$DownloadListenerProxy{ *; }
-keep class **$$UploadListenerProxy{ *; }
-keep class **$$DownloadGroupListenerProxy{ *; }
-keep class **$$DGSubListenerProxy{ *; }
-keepclasseswithmembernames class * {
    @Download.* <methods>;
    @Upload.* <methods>;
    @DownloadGroup.* <methods>;
}

#有盟统计
-keep public class com.ad.xxx.mainapp.R$*{
public static final int *;
}
-keep class com.umeng.** {*;}
-keepclassmembers class * {
   public <init> (org.json.JSONObject);
}
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

#entity
-keep public class com.ad.xxx.mainapp.entity.**{*;}
-keep public class com.ad.xxx.mainapp.BaseResponse{*;}
-keep public class com.ad.xxx.mainapp.entity.UpdateInfo{*;}

#bugly
-dontwarn com.tencent.bugly.**
-keep public class com.tencent.bugly.**{*;}

#greendao upgrade
-keepclassmembers class * extends org.greenrobot.greendao.AbstractDao {
    public static void dropTable(org.greenrobot.greendao.database.Database, boolean);
    public static void createTable(org.greenrobot.greendao.database.Database, boolean);
}

#
-keep public class * extends android.app.Activity
-keep public class * extends android.app.Service

#保持JNI不被混淆
-keepclasseswithmembernames class * {
    native <methods>;
}

#
-keep class com.blankj.utilcode.** { *; }
-keepclassmembers class com.blankj.utilcode.** { *; }
-dontwarn com.blankj.utilcode.**

#rxjava
-dontwarn java.util.concurrent.Flow*
	-dontwarn sun.misc.**
-keepclassmembers class rx.internal.util.unsafe.*ArrayQueue*Field* {
    long producerIndex;
    long consumerIndex;
}

#evenbus
-keepattributes *Annotation*
-keepclassmembers class * {
    @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }

# Only required if you use AsyncExecutor
-keepclassmembers class * extends org.greenrobot.eventbus.util.ThrowableFailureEvent {
    <init>(java.lang.Throwable);
}

# glide
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}

# Gson
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

#############################################
#
# 运行错误
#
#############################################
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn okhttp3.**

-keep class okio.** { *; }
-keep interface okio.** { *; }
-dontwarn okio.**

-keep class com.hitomi.** { *; }
-keep interface com.hitomi.** { *; }
-dontwarn com.hitomi.**

-dontwarn retrofit2.**
-keep class retrofit2.** { *; }
-keepattributes Signature
-keepattributes Exceptions

# 抛出异常时保留代码行号
-keepattributes SourceFile,LineNumberTable
# 保留Annotation不混淆
-keepattributes *Annotation*,InnerClasses
# 保留R下面的资源
-keep class **.R$* {*;}
	# 保留Parcelable序列化类不被混淆
-keep class * implements android.os.Parcelable {
    public static final android.os.Parcelable$Creator *;
}

# 保留Serializable序列化的类不被混淆
-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    !static !transient <fields>;
    !private <fields>;
    !private <methods>;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}

###plist
-keep class com.dd.plist.** { *; }
-dontwarn com.dd.plist.**

###kxml
-keep class org.kxml2.** { *; }
-keep class org.xmlpull.** { *; }
-dontwarn org.kxml2.**
-dontwarn org.xmlpull.**

###Lebo
-keep class com.hpplay.**{*;}
-keep class com.hpplay.**$*{*;}
-dontwarn com.hpplay.**

-keep class com.blankj.utilcode.** { *; }
-keepclassmembers class com.blankj.utilcode.** { *; }
-dontwarn com.blankj.utilcode.**
#statusbar
-keep class com.jaeger.library.**{*;}
#http
-keepattributes Signature, InnerClasses, EnclosingMethod

# Retrofit does reflection on method and parameter annotations.
-keepattributes RuntimeVisibleAnnotations, RuntimeVisibleParameterAnnotations

# Retain service method parameters when optimizing.
-keepclassmembers,allowshrinking,allowobfuscation interface * {
    @retrofit2.http.* <methods>;
}

# Ignore annotation used for build tooling.
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement

# Ignore JSR 305 annotations for embedding nullability information.
-dontwarn javax.annotation.**

# Guarded by a NoClassDefFoundError try/catch and only used when on the classpath.
-dontwarn kotlin.Unit

# Top-level functions that can only be used by Kotlin.
-dontwarn retrofit2.KotlinExtensions
-dontwarn retrofit2.KotlinExtensions$*

# With R8 full mode, it sees no subtypes of Retrofit interfaces since they are created with a Proxy
# and replaces all potential values with null. Explicitly keeping the interfaces prevents this.
-if interface * { @retrofit2.http.* <methods>; }
-keep,allowobfuscation interface <1>
#ad
-keep public class com.qy.** {*;}
-keep class android.support.v4.**{
        public *;
    }
-keep class android.support.v7.**{
        public *;
    }

# jiaoziPlayer
-keep public class cn.jzvd.JZMediaSystem {*; }
-keep public class cn.jzvd.demo.CustomMedia.CustomMedia {*; }
-keep public class cn.jzvd.demo.CustomMedia.JZMediaIjk {*; }
-keep public class cn.jzvd.demo.CustomMedia.JZMediaSystemAssertFolder {*; }

-keep class tv.danmaku.ijk.media.player.** {*; }
-dontwarn tv.danmaku.ijk.media.player.*
-keep interface tv.danmaku.ijk.media.player.** { *; }

-keep public class * extends android.view.View{*;}
-keep public class * implements com.kk.taurus.playerbase.player.IPlayer{*;}
#ad2
-keep public interface com.bytedance.sdk.openadsdk.downloadnew.** {*;}
-keep class com.pgl.sys.ces.* {*;}
-keep class com.bytedance.sdk.**{*;}

#nangua
-keep class com.waxgourd.wg.utils.**{*;}

#社会化组件
#qq
-keep class com.tencent.**{*;}
#微博
-keep class com.sina.weibo.sdk.** { *; }
#微信
-keep class com.tencent.mm.opensdk.** { *; }
-keep class packageName.wxapi.** { *; }
#Gson
-keep class com.google.gson.** {*;}
-keep class com.google.**{*;}
-keep class sun.misc.Unsafe { *; }
-keep class com.google.gson.stream.** { *; }
-keep class com.google.gson.examples.android.model.** { *; }
#Socialhelper
-keep class net.arvin.socialhelper.**{*;}


####################################################################################################
####################################################################################################
####################################################################################################
#ad 3 相关
#open_ad_sdk
-keep class com.bytedance.sdk.openadsdk.** { *; }
-keep public interface com.bytedance.sdk.openadsdk.downloadnew.** {*;}
-keep class com.ss.**{*;}
-dontwarn com.ss.**

#app-admob start
-keep class com.mob68.ad.**{*;}
-dontwarn com.mob68.ad.**
#app-admob end

# WindAd
-keep class com.sigmob.**{*;}
-dontwarn com.sigmob.**
# miitmdid
-keep class com.bun.miitmdid.core.** {*;}
-dontwarn com.bun.miitmdid.core.**

#广点通 start
-keep class com.qq.e.** {*;}
-dontwarn com.qq.e.**
#广点通 end

#inmobi star
-keepattributes SourceFile,LineNumberTable
-keep class com.inmobi.** { *; }
-dontwarn com.inmobi.**
-dontwarn com.squareup.picasso.**
#skip the Picasso library classes
-keep class com.squareup.picasso.** {*;}
#skip AVID classes
-keep class com.integralads.avid.library.** {*;}
#skip IAB classes
-keep class com.iab.** {*;}
-dontwarn com.iab.**
#inmobi end

#-------------- okhttp3 start-------------
# OkHttp3
# https://github.com/square/okhttp
# okhttp
-keepattributes Signature
-keepattributes *Annotation*
-keep class com.squareup.okhttp.* { *; }
-keep interface com.squareup.okhttp.** { *; }
-dontwarn com.squareup.okhttp.**

# okhttp 3
-keepattributes Signature
-keepattributes *Annotation*
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn okhttp3.**

# Okio
-dontwarn com.squareup.**
-dontwarn okio.**
-keep public class org.codehaus.* { *; }
-keep public class java.nio.* { *; }
#----------okhttp end--------------

##Glide
-dontwarn com.bumptech.glide.**
-keep class com.bumptech.glide.**{*;}
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.AppGlideModule
-keep public enum com.bumptech.glide.load.resource.bitmap.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}

-keep class com.chad.library.adapter.** {
*;
}

####################################################################################################
####################################################################################################
####################################################################################################

# 保留Parcelable序列化类不被混淆
-keep class * implements android.os.Parcelable {
    public static final android.os.Parcelable$Creator *;
}

# 保留Serializable序列化的类不被混淆
-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    !static !transient <fields>;
    !private <fields>;
    !private <methods>;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}
```
