### ISSUE TITLE
开启混淆之后,下载出现问题

### ISSUE THREAD

**Issue by MoonBlueSky** [AriaLyy/Aria#743]
开启混淆之后,下载出现问题
## 版本
* 框架版本
3.8.12
* 系统版本
android 10
## 错误日志

```
2020-08-20 09:53:09.140 11769-11769/com.yeahworld.gamebox V/YEAH_GAME_EVENT: [ (AriaDownLoadManager.java:278)#B ] 天刀情缘1218149954收到下载任务
2020-08-20 09:53:09.141 11769-11769/com.yeahworld.gamebox V/YEAH_GAME_EVENT: [ (AriaDownLoadManager.java:298)#B ] 天刀情缘1218149954任务id不存在,开始新建下载任务
2020-08-20 09:53:09.171 11769-11769/com.yeahworld.gamebox W/RecordUtil: 修改任务记录失败，新文件路径和旧文件路径一致
2020-08-20 09:53:09.171 11769-11769/com.yeahworld.gamebox I/CheckDEntityUtil: 将任务重命名为：天刀情缘.apk
2020-08-20 09:53:09.188 11769-11769/com.yeahworld.gamebox V/YEAH_GAME_EVENT: [ (AriaDownLoadManager.java:312)#B ] 天刀情缘1218149954创建下载任务成功,新建下载id为:1
2020-08-20 09:53:09.189 11769-12888/com.yeahworld.gamebox I/DTaskQueue: 获取任务，key：http://channels.yeahworld.com/datang_yeahandroid1617_145938_1596596619.apk
2020-08-20 09:53:09.191 11769-12888/com.yeahworld.gamebox W/System.err: java.lang.reflect.InvocationTargetException
2020-08-20 09:53:09.191 11769-12888/com.yeahworld.gamebox W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-08-20 09:53:09.191 11769-12888/com.yeahworld.gamebox W/System.err:     at com.arialyy.aria.core.event.EventMsgUtil$2.run(EventMsgUtil.java:71)
2020-08-20 09:53:09.191 11769-12888/com.yeahworld.gamebox W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
2020-08-20 09:53:09.191 11769-12888/com.yeahworld.gamebox W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-08-20 09:53:09.191 11769-12888/com.yeahworld.gamebox W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-08-20 09:53:09.191 11769-12888/com.yeahworld.gamebox W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-08-20 09:53:09.191 11769-12888/com.yeahworld.gamebox W/System.err:     at java.lang.Thread.run(Thread.java:919)
2020-08-20 09:53:09.191 11769-12888/com.yeahworld.gamebox W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
2020-08-20 09:53:09.192 11769-12888/com.yeahworld.gamebox W/System.err:     at com.arialyy.aria.util.AriaServiceLoader$LazyLoader.loadService(AriaServiceLoader.java:180)
2020-08-20 09:53:09.192 11769-12888/com.yeahworld.gamebox W/System.err:     at com.arialyy.aria.util.AriaServiceLoader$LazyLoader.access$100(AriaServiceLoader.java:77)
2020-08-20 09:53:09.192 11769-12888/com.yeahworld.gamebox W/System.err:     at com.arialyy.aria.util.AriaServiceLoader.getService(AriaServiceLoader.java:74)
2020-08-20 09:53:09.192 11769-12888/com.yeahworld.gamebox W/System.err:     at com.arialyy.aria.util.ComponentUtil.buildListener(ComponentUtil.java:184)
2020-08-20 09:53:09.192 11769-12888/com.yeahworld.gamebox W/System.err:     at com.arialyy.aria.core.task.DownloadTask.<init>(DownloadTask.java:38)
2020-08-20 09:53:09.192 11769-12888/com.yeahworld.gamebox W/System.err:     at com.arialyy.aria.core.task.DownloadTask.<init>(DownloadTask.java:31)
2020-08-20 09:53:09.192 11769-12888/com.yeahworld.gamebox W/System.err:     at com.arialyy.aria.core.task.DownloadTask$Builder.build(DownloadTask.java:96)
2020-08-20 09:53:09.192 11769-12888/com.yeahworld.gamebox W/System.err:     at com.arialyy.aria.core.queue.TaskFactory.createDownloadTask(TaskFactory.java:102)
2020-08-20 09:53:09.192 11769-12888/com.yeahworld.gamebox W/System.err:     at com.arialyy.aria.core.queue.TaskFactory.createTask(TaskFactory.java:62)
2020-08-20 09:53:09.192 11769-12888/com.yeahworld.gamebox W/System.err:     at com.arialyy.aria.core.queue.DTaskQueue.createTask(DTaskQueue.java:114)
2020-08-20 09:53:09.192 11769-12888/com.yeahworld.gamebox W/System.err:     at com.arialyy.aria.core.queue.DTaskQueue.createTask(DTaskQueue.java:37)
2020-08-20 09:53:09.192 11769-12888/com.yeahworld.gamebox W/System.err:     at com.arialyy.aria.core.command.AbsNormalCmd.createTask(AbsNormalCmd.java:185)
2020-08-20 09:53:09.192 11769-12888/com.yeahworld.gamebox W/System.err:     at com.arialyy.aria.core.command.StartCmd.executeCmd(StartCmd.java:64)
2020-08-20 09:53:09.192 11769-12888/com.yeahworld.gamebox W/System.err:     at com.arialyy.aria.core.command.CommandManager.start(CommandManager.java:53)
2020-08-20 09:53:09.192 11769-12888/com.yeahworld.gamebox W/System.err: 	... 7 more
```
## 混淆清单

#---------------------------------下载框架 aria ------------------------------------
-dontwarn com.arialyy.aria.**
-keep class com.arialyy.aria.**{*;}
-keep class **$$DownloadListenerProxy{ *; }
-keep class **$$UploadListenerProxy{ *; }
-keep class **$$DownloadGroupListenerProxy{ *; }
-keep class **$$DGSubListenerProxy{ *; }
-keepclasseswithmembernames class * {
    @Download.* <methods>;
    @Upload.* <methods>;
    @DownloadGroup.* <methods>;
}

## 重现步骤

1.打开混淆进行打包

## 排查出的问题
1.在源码中AriaServiceLoader会去META-INF/services/中获取服务配置并加载,加载后才能进行下载的操作,从断点来看获取的配置为空,所以导致了之后下载的时候调用失败.
2.排查到问题之后,我开始对比开启混淆和未开启混淆的包,发现
(1)在未加混淆的包中包含META-INF/services/
![image](https://user-images.githubusercontent.com/38198300/90713563-2fbdc280-e2d8-11ea-95f6-e64479565e8f.png)
(2)在混淆的包中未包含META-INF/services/
![image](https://user-images.githubusercontent.com/38198300/90713866-e457e400-e2d8-11ea-82da-4c306b13603a.png)
 目前不清楚如何处理

## 已有尝试
1.将 zipAlignEnabled和shrinkResources都设置为false (无效)
2.检查混淆文件(无果)

希望大佬帮忙康康哈

**Comment by AriaLyy** [comment]
和 https://github.com/AriaLyy/Aria/issues/739 一样的问题，我看下该怎么适配

**Comment by MoonBlueSky** [comment]
目前来看这个问题只在 com.android.tools.build:gradle:3.6.0 以下存在,3.6.0以上测试无问题 @AriaLyy

**Comment by MoonBlueSky** [comment]
用3.6.0打出包加固后,重打包![image](https://user-images.githubusercontent.com/38198300/90872720-a689b700-e3cf-11ea-8e7b-86efe33e5303.png)被删除,所以又不能下载
