### ISSUE TITLE
E/M3U8InfoThread: m3u8密钥key url 为空

### ISSUE THREAD

**Issue by scb7709** [AriaLyy/Aria#749]
框架版本

implementation 'com.arialyy.aria:core:3.8.12'
annotationProcessor 'com.arialyy.aria:compiler:3.8.12'
implementation 'com.arialyy.aria:m3u8Component:3.8.12'
或者 任意版本

系统版本
任意安卓版本

## 错误日志

2020-08-26 11:09:45.435 6106-6979/com.junwulei.jwlvideo I/DTaskQueue: 获取任务，key：https://video.tykkk.cn/20200804/Bc1vLCyW/1000kb/hls/index.m3u8
2020-08-26 11:09:45.436 6106-6979/com.junwulei.jwlvideo D/BaseCachePool: 任务【851.m3u8】进入缓存队列成功
2020-08-26 11:09:45.436 6106-6979/com.junwulei.jwlvideo I/DTaskQueue: 获取任务，key：https://video.tykkk.cn/20200804/Bc1vLCyW/1000kb/hls/index.m3u8
2020-08-26 11:09:45.436 6106-6979/com.junwulei.jwlvideo I/DTaskQueue: 添加任务，key：https://video.tykkk.cn/20200804/Bc1vLCyW/1000kb/hls/index.m3u8
2020-08-26 11:09:45.436 6106-6979/com.junwulei.jwlvideo D/DLoadExecutePool: 任务【851.m3u8】进入执行队列成功
2020-08-26 11:09:45.531 6106-6980/com.junwulei.jwlvideo D/M3U8InfoThread: #EXTM3U
2020-08-26 11:09:45.531 6106-6980/com.junwulei.jwlvideo D/M3U8InfoThread: #EXT-X-VERSION:3
2020-08-26 11:09:45.531 6106-6980/com.junwulei.jwlvideo D/M3U8InfoThread: #EXT-X-TARGETDURATION:6
2020-08-26 11:09:45.531 6106-6980/com.junwulei.jwlvideo D/M3U8InfoThread: #EXT-X-PLAYLIST-TYPE:VOD
2020-08-26 11:09:45.531 6106-6980/com.junwulei.jwlvideo D/M3U8InfoThread: #EXT-X-MEDIA-SEQUENCE:0
2020-08-26 11:09:45.531 6106-6980/com.junwulei.jwlvideo D/M3U8InfoThread: #EXT-X-KEY:METHOD=AES-128,URI="https://cdn.tykkk.cn/20200804/Bc1vLCyW/1000kb/hls/key.key"
2020-08-26 11:09:45.532 6106-6980/com.junwulei.jwlvideo D/M3U8InfoThread: 密钥不存在，下载密钥
2020-08-26 11:09:45.532 6106-6980/com.junwulei.jwlvideo I/m3u8UrlConverter: https://video.tykkk.cn/20200804/Bc1vLCyW/1000kb/hls/index.m3u8
2020-08-26 11:09:45.532 6106-6980/com.junwulei.jwlvideo I/m3u8UrlConverter: https://video.tykkk.cn/20200804/Bc1vLCyW/1000kb/hls/index.m3u8
2020-08-26 11:09:45.532 6106-6980/com.junwulei.jwlvideo I/m3u8UrlConverter: https://cdn.tykkk.cn/20200804/Bc1vLCyW/1000kb/hls/key.key
2020-08-26 11:09:45.532 6106-6980/com.junwulei.jwlvideo E/M3U8InfoThread: m3u8密钥key url 为空
2020-08-26 11:09:45.532 6106-6980/com.junwulei.jwlvideo D/M3U8InfoThread: #EXTINF:3.12,
2020-08-26 11:09:45.532 6106-6980/com.junwulei.jwlvideo D/M3U8InfoThread: https://cdn.tykkk.cn/20200804/Bc1vLCyW/1000kb/hls/x1ExbdIO.ts

0-08-26 11:09:46.378 6106-6980/com.junwulei.jwlvideo D/M3U8VodLoader: 启动定时器，delayTimer = 1000, updateInterval = 1000
2020-08-26 11:09:46.381 6106-6991/com.junwulei.jwlvideo D/M3U8ThreadTaskAdapter: 分片【0】开始下载
2020-08-26 11:09:46.381 6106-6992/com.junwulei.jwlvideo D/M3U8ThreadTaskAdapter: 分片【1】开始下载
2020-08-26 11:09:46.382 6106-6993/com.junwulei.jwlvideo D/M3U8ThreadTaskAdapter: 分片【2】开始下载
2020-08-26 11:09:46.382 6106-6995/com.junwulei.jwlvideo D/M3U8ThreadTaskAdapter: 分片【3】开始下载
2020-08-26 11:09:46.592 6106-6995/com.junwulei.jwlvideo W/System.err: com.arialyy.aria.exception.AriaM3U8Exception: Aria M3U8 Exception:
2020-08-26 11:09:46.592 6106-6995/com.junwulei.jwlvideo W/System.err:     at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handleConn(M3U8ThreadTaskAdapter.java:141)
2020-08-26 11:09:46.592 6106-6995/com.junwulei.jwlvideo W/System.err:     at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handlerThreadTask(M3U8ThreadTaskAdapter.java:92)

2020-08-26 11:09:46.945 6106-6980/com.junwulei.jwlvideo D/VodStateManager: vod任务【851.m3u8】失败
2020-08-26 11:09:46.949 6106-6106/com.junwulei.jwlvideo D/DTaskQueue: 从执行池删除任务【851.m3u8】成功

## 重现步骤

以下等链接不能下载， 链接没有问题可以正常播放的 网络也没有问题 ：其中包含的key.key  是存在的 但是 但是下载却报错说 秘钥不存在。……

**### _视频链接1    https://video.tykkk.cn/20200804/Bc1vLCyW/1000kb/hls/index.m3u8
文件信息

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:6
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="https://cdn.tykkk.cn/20200804/Bc1vLCyW/1000kb/hls/key.key"
#EXTINF:3.12,
https://cdn.tykkk.cn/20200804/Bc1vLCyW/1000kb/hls/x1ExbdIO.ts
#EXTINF:3.4,
https://cdn.tykkk.cn/20200804/Bc1vLCyW/1000kb/hls/4i8WpStB.ts
#EXTINF:2.72,
https://cdn.tykkk.cn/20200804/Bc1vLCyW/1000kb/hls/wekhlYNK.ts

**### _视频链接2    https://video.tykkk.cn/20200819/vojWlSVl/1000kb/hls/index.m3u8
文件信息
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:6
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="https://cdn.tykkk.cn/20200819/vojWlSVl/1000kb/hls/key.key"
#EXTINF:3.12,
https://cdn.tykkk.cn/20200819/vojWlSVl/1000kb/hls/1EEPZwOs.ts
#EXTINF:3,
https://cdn.tykkk.cn/20200819/vojWlSVl/1000kb/hls/YIkWzHbh.ts
#EXTINF:3.84,
https://cdn.tykkk.cn/20200819/vojWlSVl/1000kb/hls/iLkurYEi.ts
#EXTINF:3,
https://cdn.tykkk.cn/20200819/vojWlSVl/1000kb/hls/K2sv2hLa.ts

**Comment by AriaLyy** [comment]
https://github.com/AriaLyy/Aria/issues/597
默认的key转换器无法获取地址的话，需要自己设置key转换器
