### ISSUE TITLE
异常处理问题

### ISSUE THREAD

**Issue by ryanxia2016** [AriaLyy/Aria#750]
## 版本
* 框架版本 
3.8.12
* 系统版本
huawei android 8

## 错误日志
2020-08-26 13:16:06.994 13882-14100/? E/AndroidRuntime: FATAL EXCEPTION: Thread-37
    Process: com.smartcar.test, PID: 13882
    java.lang.IllegalArgumentException: Invalid path: /smartcar
        at android.os.StatFs.doStat(StatFs.java:46)
        at android.os.StatFs.<init>(StatFs.java:39)
        at com.arialyy.aria.util.FileUtil.checkMemorySpace(FileUtil.java:514)
        at com.arialyy.aria.http.download.HttpDFileInfoTask.handleConnect(HttpDFileInfoTask.java:140)
        at com.arialyy.aria.http.download.HttpDFileInfoTask.run(HttpDFileInfoTask.java:90)
        at com.arialyy.aria.core.loader.NormalLoader.handleTask(NormalLoader.java:101)
        at com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:133)
        at com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:115)

如果下载的目标保存路径无效，会导致闪退，应该触发下载错误回调为妥？
我们测试的时候，保存路径是由用户选择，如果用户选择了一个系统不允许访问的目录，就可能引发这样的问题

**Comment by AriaLyy** [comment]
对于这种情况，你可以在用户选择后就直接判断是否有效。对于这功能，后续可能会增加。。

**Comment by ryanxia2016** [comment]
已经加了判断

哈哈，不过有句话咋说来着，无论怎样就算闪退，也不能在自己的代码里发生 :-)

**Comment by Reginer** [comment]
以前路径不存在还能创建个目录，现在这直接返回失败了。创建失败再返回失败也可以吧
