### ISSUE TITLE
下载失败 

### ISSUE THREAD

**Issue by scb7709** [AriaLyy/Aria#758]
## 版本
implementation 'com.arialyy.aria:core:3.8.12'
annotationProcessor 'com.arialyy.aria:compiler:3.8.12'
implementation 'com.arialyy.aria:m3u8Component:3.8.12'
或者 任意版本

系统版本
任意安卓版本

## 错误日志

20-08-31 11:20:12.289 4798-4798/com.jieran.app.mjtv I/getM3U8Info: com.jieran.app.mjtv.model.VideoChapter
2020-08-31 11:20:12.289 4798-5954/com.jieran.app.mjtv I/DTaskQueue: 获取任务，key：https://video.kssznuu.cn/20200812/2XTqvKoa/2000kb/hls/index.m3u8
2020-08-31 11:20:12.290 4798-5954/com.jieran.app.mjtv D/BaseCachePool: 任务【1507.m3u8】进入缓存队列成功
2020-08-31 11:20:12.290 4798-5954/com.jieran.app.mjtv I/DTaskQueue: 获取任务，key：https://video.kssznuu.cn/20200812/2XTqvKoa/2000kb/hls/index.m3u8
2020-08-31 11:20:12.290 4798-5954/com.jieran.app.mjtv I/DTaskQueue: 添加任务，key：https://video.kssznuu.cn/20200812/2XTqvKoa/2000kb/hls/index.m3u8
2020-08-31 11:20:12.290 4798-5954/com.jieran.app.mjtv D/DLoadExecutePool: 任务【1507.m3u8】进入执行队列成功
2020-08-31 11:20:12.290 4798-4798/com.jieran.app.mjtv I/getM3U8Info: com.jieran.app.mjtv.model.BaseVideo
2020-08-31 11:20:12.563 4798-5956/com.jieran.app.mjtv D/M3U8InfoThread: #EXTM3U
2020-08-31 11:20:12.563 4798-5956/com.jieran.app.mjtv D/M3U8InfoThread: #EXT-X-VERSION:3
2020-08-31 11:20:12.563 4798-5956/com.jieran.app.mjtv D/M3U8InfoThread: #EXT-X-TARGETDURATION:6
2020-08-31 11:20:12.563 4798-5956/com.jieran.app.mjtv D/M3U8InfoThread: #EXT-X-PLAYLIST-TYPE:VOD
2020-08-31 11:20:12.564 4798-5956/com.jieran.app.mjtv D/M3U8InfoThread: #EXT-X-MEDIA-SEQUENCE:0
2020-08-31 11:20:12.564 4798-5956/com.jieran.app.mjtv D/M3U8InfoThread: #EXT-X-KEY:METHOD=AES-128,URI="https://cdn.0593666.com/20200812/2XTqvKoa/2000kb/hls/key.key"
2020-08-31 11:20:12.564 4798-5956/com.jieran.app.mjtv D/M3U8InfoThread: #EXTINF:3,
2020-08-31 11:20:12.564 4798-5956/com.jieran.app.mjtv D/M3U8InfoThread: https://cdn.0593666.com/20200812/2XTqvKoa/2000kb/hls/fCTifWE1.ts

。。。。

2020-08-31 11:20:12.714 4798-5956/com.jieran.app.mjtv D/M3U8InfoThread: #EXTINF:2.16,
2020-08-31 11:20:12.714 4798-5956/com.jieran.app.mjtv D/M3U8InfoThread: https://cdn.0593666.com/20200812/2XTqvKoa/2000kb/hls/Rq4o9wFx.ts
2020-08-31 11:20:12.714 4798-5956/com.jieran.app.mjtv D/M3U8InfoThread: #EXT-X-ENDLIST
2020-08-31 11:20:14.657 4798-5956/com.jieran.app.mjtv D/M3U8VodLoader: 启动定时器，delayTimer = 1000, updateInterval = 1000
2020-08-31 11:20:14.661 4798-5963/com.jieran.app.mjtv D/M3U8ThreadTaskAdapter: 分片【0】开始下载
2020-08-31 11:20:14.663 4798-5964/com.jieran.app.mjtv D/M3U8ThreadTaskAdapter: 分片【1】开始下载
2020-08-31 11:20:14.664 4798-5965/com.jieran.app.mjtv D/M3U8ThreadTaskAdapter: 分片【2】开始下载
2020-08-31 11:20:14.667 4798-5968/com.jieran.app.mjtv D/M3U8ThreadTaskAdapter: 分片【3】开始下载
2020-08-31 11:20:14.940 4798-5968/com.jieran.app.mjtv W/System.err: com.arialyy.aria.exception.AriaM3U8Exception: Aria M3U8 Exception:
2020-08-31 11:20:14.940 4798-5968/com.jieran.app.mjtv W/System.err:     at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handleConn(M3U8ThreadTaskAdapter.java:141)
2020-08-31 11:20:14.941 4798-5968/com.jieran.app.mjtv W/System.err:     at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handlerThreadTask(M3U8ThreadTaskAdapter.java:92)
2020-08-31 11:20:14.966 4798-5965/com.jieran.app.mjtv W/System.err: com.arialyy.aria.exception.AriaM3U8Exception: Aria M3U8 Exception:
2020-08-31 11:20:14.966 4798-5965/com.jieran.app.mjtv W/System.err:     at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handleConn(M3U8ThreadTaskAdapter.java:141)
2020-08-31 11:20:14.966 4798-5965/com.jieran.app.mjtv W/System.err:     at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handlerThreadTask(M3U8ThreadTaskAdapter.java:92)
2020-08-31 11:20:14.976 4798-5964/com.jieran.app.mjtv W/System.err: com.arialyy.aria.exception.AriaM3U8Exception: Aria M3U8 Exception:
2020-08-31 11:20:14.977 4798-5964/com.jieran.app.mjtv W/System.err:     at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handleConn(M3U8ThreadTaskAdapter.java:141)
2020-08-31 11:20:14.977 4798-5964/com.jieran.app.mjtv W/System.err:     at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handlerThreadTask(M3U8ThreadTaskAdapter.java:92)
2020-08-31 11:20:15.450 4798-5963/com.jieran.app.mjtv W/System.err: com.arialyy.aria.exception.AriaM3U8Exception: Aria M3U8 Exception:
2020-08-31 11:20:15.450 4798-5963/com.jieran.app.mjtv W/System.err:     at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handleConn(M3U8ThreadTaskAdapter.java:141)
2020-08-31 11:20:15.450 4798-5963/com.jieran.app.mjtv W/System.err:     at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handlerThreadTask(M3U8ThreadTaskAdapter.java:92)
2020-08-31 11:20:15.454 4798-5956/com.jieran.app.mjtv D/VodStateManager: vod任务【1507.m3u8】失败
2020-08-31 11:20:15.457 4798-4798/com.jieran.app.mjtv D/DTaskQueue: 从执行池删除任务【1507.m3u8】成功

## 重现步骤

这类链接下载失败
https://video.kssznuu.cn/20200812/2XTqvKoa/2000kb/hls/index.m3u8

**Comment by AriaLyy** [comment]
这种非标准的需要自己定义转换器，参考：https://github.com/AriaLyy/Aria/issues/597

**Comment by xqd360** [comment]
请问大佬这个资源地址（https://cdn.0593666.com/20200812/2XTqvKoa/2000kb/hls/Rq4o9wFx.ts）资源站地址是哪个？我正在寻找它，谢谢

> ## 版本
> 实现'com.arialyy.aria：core：3.8.12'
> 注解处理器'com.arialyy.aria：compiler：
> 3.8.12 '实现'com.arialyy.aria：m3u8Component：
> 3.8.12 '或任意版本
> 
> 系统版本
> 任意安卓版本
> 
> ## 错误日志
> 20-08-31 11：20：12.289 4798-4798 / com.jieran.app.mjtv I / getM3U8Info：com.jieran.app.mjtv.model.VideoChapter
> 2020-08-31 11：20：12.289 4798-5954 / com.jieran.app.mjtv I / DTaskQueue：获取任务，密钥：[https](https://video.kssznuu.cn/20200812/2XTqvKoa/2000kb/hls/index.m3u8)
> ://video.kssznuu.cn/20200812/2XTqvKoa/2000kb/hls/index.m3u8 2020-08-31 11：20：12.290 4798-5954 /com.jieran.app.mjtv D / BaseCachePool：任务【1507.m3u8】进入缓存
> 变量成功2020-08-31 11：20：12.290 4798-5954 / com.jieran.app.mjtv I / DTaskQueue：获取任务，密钥：[https](https://video.kssznuu.cn/20200812/2XTqvKoa/2000kb/hls/index.m3u8)
> ://video.kssznuu.cn/20200812/2XTqvKoa/2000kb/hls/index.m3u8 2020-08-31 11：20：12.290 4798-5954 / com.jieran.app.mjtv I / DTaskQueue：添加任务，密钥：[https](https://video.kssznuu.cn/20200812/2XTqvKoa/2000kb/hls/index.m3u8)
> ://video.kssznuu.cn/20200812/2XTqvKoa/2000kb/hls/index.m3u8 2020-08-31 11：20：12.290 4798-5954 / com.jieran.app.mjtv D / DLoadExecutePool：任务【1507.m3u8】进入执行体内成功
> 2020-08-31 11：20：12.290 4798-4798 / com.jieran.app.mjtv I / getM3U8信息：com.jieran.app.mjtv.model.BaseVideo
> 2020-08-31 11：20：12.563 4798-5956 / com.jieran.app.mjtv D / M3U8InfoThread：＃EXTM3U
> 2020-08-31 11：20：12.563 4798-5956 / com.jieran.app.mjtv D / M3U8InfoThread：＃EXT-X-VERSION：3
> 2020-08- 31 11：20：12.563 4798-5956 / com.jieran.app.mjtv D / M3U8InfoThread：＃EXT-X-TARGETDURATION：6
> 2020-08-31 11：20：12.563 4798-5956 / com.jieran.app.mjtv D / M3U8InfoThread：＃EXT-X-PLAYLIST-TYPE：VOD
> 2020-08-31 11：20：12.564 4798-5956 / com.jieran.app.mjtv D / M3U8InfoThread：＃EXT-X-MEDIA-SEQUENCE：0
> 2020 -08-31 11：20：12.564 4798-5956 / com.jieran.app.mjtv D / M3U8InfoThread：＃EXT-X-KEY：METHOD = AES-128，URI =“ [https://cdn.0593666.com/ 20200812 / 2XTqvKoa / 2000kb / hls / key.key](https://cdn.0593666.com/20200812/2XTqvKoa/2000kb/hls/key.key) “
> 2020-08-31 11：20：12.564 4798-5956 / com.jieran.app.mjtv D / M3U8InfoThread：#EXTINF：
> 3，2020-08-31 11：20：12.564 4798-5956 / com.jieran.app。 mjtv D / M3U8InfoThread：[https](https://cdn.0593666.com/20200812/2XTqvKoa/2000kb/hls/fCTifWE1.ts) ://cdn.0593666.com/20200812/2XTqvKoa/2000kb/hls/fCTifWE1.ts[](https://cdn.0593666.com/20200812/2XTqvKoa/2000kb/hls/fCTifWE1.ts)
> 
> 。。。
> 
> 2020-08-31 11：20：12.714 4798-5956 / com.jieran.app.mjtv D / M3U8InfoThread：#EXTINF：
> 2.16，2020-08-31 11：20：12.714 4798-5956 / com.jieran.app。 mjtv D / M3U8InfoThread：[https](https://cdn.0593666.com/20200812/2XTqvKoa/2000kb/hls/Rq4o9wFx.ts)
> ://cdn.0593666.com/20200812/2XTqvKoa/2000kb/hls/Rq4o9wFx.ts 2020-08-31 11：20：12.714 4798-5956 / com.jieran.app.mjtv D / M3U8InfoThread ：＃EXT-X-ENDLIST
> 2020-08-31 11：20：14.657 4798-5956 / com.jieran.app.mjtv D / M3U8VodLoader：启动定时器，delayTimer = 1000，updateInterval = 1000
> 2020-08-31 11： 20：14.661 4798-5963 / com.jieran.app.mjtv D / M3U8ThreadTaskAdapter：分片【0】开始下载
> 2020-08-31 11：20：14.663 4798-5964 / com.jieran.app.mjtv D / M3U8ThreadTaskAdapter：分片【1】开始下载
> 2020-08-31 11：20：14.664 4798-5965 / com.jieran.app.mjtv D / M3U8ThreadTaskAdapter：分片【2】开始下载
> 2020-08-31 11：20：14.667 4798-5968 / com.jieran.app.mjtv D / M3U8ThreadTaskAdapter：分片【3】开始下载
> 2020-08-31 11：20：14.940 4798-5968 / com.jieran。 app.mjtv W / System.err：com.arialyy.aria.exception.AriaM3U8Exception：Aria M3U8 Exception：
> 2020-08-31 11：20：14.940 4798-5968 / com.jieran.app.mjtv W / System.err：在com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handleConn（M3U8ThreadTaskAdapter.java:141）
> 2020-08-31 11：20：14.941 4798-5968 / com.jieran.app.mjtv W / System.err：在com.arialyy .aria.m3u8.M3U8ThreadTaskAdapter.handlerThreadTask（M3U8ThreadTaskAdapter.java:92）
> 2020-08-31 11：20：14.966 4798-5965 / com.jieran.app.mjtv W / System.err：com.arialyy.aria.exception。 AriaM3U8Exception：Aria M3U8异常：
> 2020-08-31 11：20：14.966 4798-5965 / com.jieran.app.mjtv W / System.err：at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handleConn（M3U8ThreadTaskAdapter.java:141）
> 2020-08- 31 11：20：14.966 4798-5965 / com.jieran.app.mjtv W / System.err：at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handlerThreadTask（M3U8ThreadTaskAdapter.java:92）
> 2020-08-31 11:20 ：14.976 4798-5964 / com.jieran.app.mjtv W / System.err：com.arialyy.aria.exception.AriaM3U8Exception：Aria M3U8 Exception：
> 2020-08-31 11：20：14.977 4798-5964 / com.jieran .app.mjtv W / System.err：at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handleConn（M3U8ThreadTaskAdapter.java:141）
> 2020-08-31 11：20：14.977 4798-5964 / com.jieran.app.mjtv W / System.err：位于com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handlerThreadTask（M3U8ThreadTaskAdapter.java:92）
> 2020-08-31 11：20：15.450 4798-5963 / com.jieran.app.mjtv W / System.err：com.arialyy.aria.exception.AriaM3U8Exception：Aria M3U8 Exception：
> 2020-08-31 11:20： 15.450 4798-5963 / com.jieran.app.mjtv W / System.err：at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handleConn（M3U8ThreadTaskAdapter.java:141）
> 2020-08-31 11：20：15.450 4798-5963 /com.jieran.app.mjtv W / System.err：位于com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handlerThreadTask（M3U8ThreadTaskAdapter.java:92）
> 2020-08-31 11：20：15.454 4798-5956 / com.jieran .app.mjtv D / VodStateManager：vod任务【1507.m3u8】失败
> 2020-08-31 11：20：15.457 4798-4798 / com.jieran.app.mjtv D / DTaskQueue：从执行池删除任务【1507.m3u8 】成功
> 
> ## 重现步骤
> 种类链接下载失败
> https://video.kssznuu.cn/20200812/2XTqvKoa/2000kb/hls/index.m3u8


请问大佬这个资源地址（https://cdn.0593666.com/20200812/2XTqvKoa/2000kb/hls/Rq4o9wFx.ts）资源站地址是哪个？我正在寻找它，谢谢
