### ISSUE TITLE
崩溃bug

### ISSUE THREAD

**Issue by zccguagua** [AriaLyy/Aria#760]
版本3.8.6 出现一次崩溃 暂未复现
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
	at com.arialyy.aria.core.common.RecordHelper.handleSingleThreadRecord(RecordHelper.java:157)
	at com.arialyy.aria.http.HttpRecordHandler.handlerTaskRecord(HttpRecordHandler.java:57)
	at com.arialyy.aria.core.common.RecordHandler.getRecord(RecordHandler.java:88)
	at com.arialyy.aria.core.loader.NormalLoader.startThreadTask(NormalLoader.java:111)
	at com.arialyy.aria.core.loader.NormalLoader$1.onSucceed(NormalLoader.java:150)
	at com.arialyy.aria.http.download.HttpDFileInfoTask.handleConnect(HttpDFileInfoTask.java:249)
	at com.arialyy.aria.http.download.HttpDFileInfoTask.run(HttpDFileInfoTask.java:85)
	at com.arialyy.aria.core.loader.NormalLoader.handleTask(NormalLoader.java:98)
	at com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:132)
	at com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:114)
	at java.lang.Thread.run(Thread.java:818)

**Comment by AriaLyy** [comment]
升级到新版本，这个是已知问题
