### ISSUE TITLE
Android6部分资源下载出错

### ISSUE THREAD

**Issue by xuqingquan1995** [AriaLyy/Aria#761]
## 版本
* 框架版本
3.8.12
* 系统版本
Android 6 小米 红米Note 4,
Android 6 AVD 模拟器
## 错误日志

com.arialyy.aria.exception.AriaHTTPException: Aria HTTP Exception:
    任务下载失败，errorCode：400, url: http://down2.jjxsw.la/d/file/p/txt/2020/%E5%BD%93%E5%B0%98%E6%B2%99%E6%B4%97%E5%87%80%E7%9A%84%E6%97%B6%E5%80%99[%E8%B5%8C%E7%9F%B3].txt
        at com.arialyy.aria.http.download.HttpDFileInfoTask.handleConnect(HttpDFileInfoTask.java:242)
        at com.arialyy.aria.http.download.HttpDFileInfoTask.run(HttpDFileInfoTask.java:90)
        at com.arialyy.aria.core.loader.NormalLoader.handleTask(NormalLoader.java:101)
        at com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:133)
        at com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:115)
        at java.lang.Thread.run(Thread.java:818)

测试了该网站几个小说的下载全部失败，但是其他网站的能够成功下载

**Comment by AriaLyy** [comment]
可能是host 头域的问题

**Comment by xuqingquan1995** [comment]
那我应该怎么解决呢？

**Comment by AriaLyy** [comment]
在header 中增加 host头域
```
.option(new HttpOption().addHeader())
```

**Comment by xuqingquan1995** [comment]
因为这个是做网页中的下载，我有把网页返回的参数添加到header中，但还是一样但错误日志
