### ISSUE TITLE
下载mp4文件,下载失败后(包括非正常退出app)继续下载有时候播放不了

### ISSUE THREAD

**Issue by huangxiaoyu** [AriaLyy/Aria#767]
## 版本
* 3.8.7-beta-12 3.8.12

* 系统版本
android 8.1
## 错误日志
2020-09-14 10:16:31.039 29366-29601/com.education.zhongxinvideo E/qdgralloc: Unknown Color Space = 2
2020-09-14 10:16:31.463 29366-29366/com.education.zhongxinvideo E/huang_app_log: progress=0,  secProgress=0,  currentPosition=2013,  duration=1531796
2020-09-14 10:16:31.825 29366-31105/com.education.zhongxinvideo E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.ParserException: Invalid NAL length
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:542)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:192)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:982)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2020-09-14 10:16:31.874 29366-29366/com.education.zhongxinvideo E/EventLogger: playerFailed [2.07]
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.ParserException: Invalid NAL length
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:394)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:192)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.ParserException: Invalid NAL length
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:542)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:192)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:982)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2020-09-14 10:16:31.925 29366-29366/com.education.zhongxinvideo E/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

## 重现步骤

1.下载的时候出错重新下载.或者退出app(包括非正常退出,从最近里面移除)没有调用结束任务再次打开app继续下载,下载视频文件后打开视频播放,无法播放. 正常下载, 开着app一直下载完的话就可以播放,下载配置的单线程下载
 是不是下载进度没有记录好 继续接着下载的时候损坏了视频文件的索引导致视频无法播放?

**Comment by z876335662** [comment]
确实有这个问题  失败之后再下载完成之后无法播放

**Comment by huangxiaoyu** [comment]
> 确实有这个问题 失败之后再下载完成之后无法播放

嗯  如果app打开着 从头下到尾可以播放  手动暂停在开启也可以  就是直接杀死app在进入app开始下载就会有这个问题  应该是下载进度和保存的文件进度不同步  看他的源码还没找到问题在哪

**Comment by huangxiaoyu** [comment]
下载识别到长度为0 并且代码已经抛出异常了,下载的状态是不是应该是失败的状态? 下载长度是零0应该是服务器那边出问题了  使用浏览器或者vlc是可以看视频的,只不过视频打开的慢
![image](https://user-images.githubusercontent.com/4270373/93663006-05a61e80-fa97-11ea-9bee-662d3de78b1d.png)

**Comment by huangxiaoyu** [comment]
> 确实有这个问题 失败之后再下载完成之后无法播放

你把下载的缓存大小设置大点  默认的8192  改成16384我试了很多次没有这个问题了

**Comment by z876335662** [comment]
好的  等会测试一下

**Comment by huangxiaoyu** [comment]
> 下载识别到长度为0 并且代码已经抛出异常了,下载的状态是不是应该是失败的状态? 现在给的状态是完成.下载长度是零0应该是服务器那边出问题了 使用浏览器或者vlc是可以看视频的,只不过视频打开的慢
> ![1600505086(1)](https://user-images.githubusercontent.com/4270373/93663060-849b5700-fa97-11ea-990f-9a8d2cf49c8e.jpg)

使用3.8.7-beta-12可以正常下载  3.8.12有上面的问题

**Comment by huangxiaoyu** [comment]
这个问题比较严重...  还是存在视频文件下载中断后继续下载,下载完成后不能播放  经常有用户反馈

**Comment by AriaLyy** [comment]
提供一个可用的url吧，我测试看看

**Comment by huangxiaoyu** [comment]
这是随便找的个课程,因为课程是收费的不便公开,私发你邮件.
播放器用的gsyplayer,eox内核

**Comment by AriaLyy** [comment]
邮件已经收到了，我晚上看看是啥情况

**Comment by huangxiaoyu** [comment]
非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AriaLyy/Aria"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月12日(星期四) 下午3:33
收件人:&nbsp;"AriaLyy/Aria"<Aria@noreply.github.com&gt;;
抄送:&nbsp;"懒鱼"<592010803@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AriaLyy/Aria] 下载mp4文件,下载失败后(包括非正常退出app)继续下载有时候播放不了 (#767)





 
邮件已经收到了，我晚上看看是啥情况

**Comment by AriaLyy** [comment]
我测试了4，5次，貌似都没问题～～，md5都和我用迅雷下的一样，期间断网，杀进程好几次...

**Comment by huangxiaoyu** [comment]
http://v.kjjl100.com/kz/zx/cj/2020cjswxdb/1.mp4


我这下载经常这样 人多就会出现各种问题.... 麻烦你在试下这个地址&nbsp; 我用的版本是3.8.7-beta-12
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AriaLyy/Aria"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月12日(星期四) 晚上9:11
收件人:&nbsp;"AriaLyy/Aria"<Aria@noreply.github.com&gt;;
抄送:&nbsp;"懒鱼"<592010803@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AriaLyy/Aria] 下载mp4文件,下载失败后(包括非正常退出app)继续下载有时候播放不了 (#767)





 
我测试了4，5次，貌似都没问题～～，md5都和我用迅雷下的一样，期间断网，杀进程好几次...

**Comment by huangxiaoyu** [comment]
是不是我这对应状态之心的方法不对?











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AriaLyy/Aria"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月12日(星期四) 晚上9:11
收件人:&nbsp;"AriaLyy/Aria"<Aria@noreply.github.com&gt;;
抄送:&nbsp;"懒鱼"<592010803@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AriaLyy/Aria] 下载mp4文件,下载失败后(包括非正常退出app)继续下载有时候播放不了 (#767)





 
我测试了4，5次，貌似都没问题～～，md5都和我用迅雷下的一样，期间断网，杀进程好几次...

**Comment by AriaLyy** [comment]
现在最后这样吧，文件下载完成后，比对下服务器端传来的md5，目前排除不出是哪出的问题，我这来来回回测了好多次，都没啥问题～～
