### ISSUE TITLE
FtpUrlEntity.hostName' on a null object reference

### ISSUE THREAD

**Issue by autumnLei** [AriaLyy/Aria#793]
## 版本
* 框架版本
 'com.arialyy.aria:core:3.8.14'
* 系统版本
android 9
## 错误日志
2020-10-21 16:53:05.575 7301-7502/com.tcl.versionUpdateApp E/AndroidRuntime: FATAL EXCEPTION: Thread-10
    Process: com.tcl.versionUpdateApp, PID: 7301
    java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.arialyy.aria.core.FtpUrlEntity.hostName' on a null object reference
        at com.arialyy.aria.ftp.AbsFtpInfoTask.createFtpClient(AbsFtpInfoTask.java:133)
        at com.arialyy.aria.ftp.AbsFtpInfoTask.run(AbsFtpInfoTask.java:94)
        at com.arialyy.aria.core.loader.NormalLoader.handleTask(NormalLoader.java:101)
        at com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:133)
        at com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:115)
        at java.lang.Thread.run(Thread.java:764)

## 重现步骤
        mTaskId = Aria.download(this)
                .loadFtp("ftp://anonymous@ftp.gnu.org:21/welcome.msg")
                .setFilePath(file.getPath() + "/")
                .option(getFtpOption())
                .create() + "";

**Comment by autumnLei** [comment]
匿名访问密码得带个空格 不然库自动判null了
功能不复杂的还是用apache的commons-net简单实现吧
