### ISSUE TITLE
FTP下载空指针

### ISSUE THREAD

**Issue by guodongAndroid** [AriaLyy/Aria#799]
## 版本
* 框架版本 3.8.12 - 3.8.14

* 系统版本 5.1.1

## 错误日志

![image](https://user-images.githubusercontent.com/19586334/98490169-a630e780-226b-11eb-8609-2a3cab72ba06.png)

java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Handler$Callback com.arialyy.aria.core.inf.IThreadStateManager.getHandlerCallback()' on a null object reference
        at com.arialyy.aria.core.loader.SubLoader.handlerTask(SubLoader.java:124)
        at com.arialyy.aria.core.loader.SubLoader.run(SubLoader.java:268)
        at java.lang.Thread.run(Thread.java:818)

## 重现步骤

1.FTP下载即可
2.
3.
4.

**Comment by AriaLyy** [comment]
感谢反馈，3.8.15已经修复了这个问题
