### ISSUE TITLE
StopAllTask()异常ConcurrentModificationException

### ISSUE THREAD

**Issue by fishingcats** [AriaLyy/Aria#80]
D/SingleThreadTask: 任务【dfeba30541f209ab8a50d847fc1661ce.apk.temp】thread__0__停止, stop location ==> 38171153
07-24 15:33:57.477 27290-27467/? D/SingleThreadTask: 任务【dfeba30541f209ab8a50d847fc1661ce.apk.temp】thread__1__停止, stop location ==> 127444554
07-24 15:33:57.487 27290-27467/? D/SingleThreadTask: 任务【dfeba30541f209ab8a50d847fc1661ce.apk.temp】thread__2__停止, stop location ==> 230430328
07-24 15:33:57.487 27290-27467/? D/SingleThreadTask: 任务【dfeba30541f209ab8a50d847fc1661ce.apk.temp】已停止
07-24 15:33:57.487 27290-27290/? E/ManageFragment: onTaskStop
07-24 15:33:57.487 27290-27290/? E/AppListPager: downloadStop:com.test_1
07-24 15:33:57.497 27290-27290/? D/DownloadTaskQueue: 从执行池删除任务，删除成功
07-24 15:33:57.497 27290-27467/? W/dalvikvm: threadid=13: thread exiting with uncaught exception (group=0x4189aba8)
07-24 15:33:57.497 27290-27290/? W/AbsSchedulers: 没有下一任务
07-24 15:33:57.507 27290-27467/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                   Process: com.iflytek.appstoreauto, PID: 27290
                                                   java.lang.RuntimeException: An error occured while executing doInBackground()
                                                       at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                       at java.lang.Thread.run(Thread.java:841)
                                                    Caused by: java.util.ConcurrentModificationException
                                                       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
                                                       at java.util.HashMap$KeyIterator.next(HashMap.java:833)
                                                       at com.arialyy.aria.core.queue.AbsTaskQueue.stopAllTask(AbsTaskQueue.java:49)
                                                       at com.arialyy.aria.core.queue.DownloadTaskQueue.stopAllTask(DownloadTaskQueue.java:36)
                                                       at com.arialyy.aria.core.command.StopAllCmd.executeCmd(StopAllCmd.java:18)
                                                       at com.arialyy.aria.core.AriaManager.exe(AriaManager.java:138)
                                                       at com.arialyy.aria.core.download.DownloadReceiver.stopAllTask(DownloadReceiver.java:143)
                                                       at com.iflytek.appstoreauto.appmarket.ManageFragment.installSelfPre(ManageFragment.java:188)
                                                       at com.iflytek.appstoreauto.download.InstallManager$InstallTask.doInBackground(InstallManager.java:89)
                                                       at com.iflytek.appstoreauto.download.InstallManager$InstallTask.doInBackground(InstallManager.java:72)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)?
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)?
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)?
                                                       at java.lang.Thread.run(Thread.java:841)?

**Comment by fishingcats** [comment]
从log看，在AbsTaskQueue调用stopAllTask执行下面代码：
Set<String> exeKeys = mExecutePool.getAllTask().keySet();
        for (String key : exeKeys) {
            TASK task = mExecutePool.getAllTask().get(key);
            if (task != null && task.isRunning()) task.stop();
        }
好像有问题：download stop的时候，mExecutePool.removeTask(task)导致mExecuteMap changed，这时候就会出现上述代码出现ConcurrentModificationException。

@Override public boolean removeTask(TASK task) {
    synchronized (AriaManager.LOCK) {
      if (task == null) {
        Log.e(TAG, "任务不能为空");
        return false;
      } else {
        String key = CommonUtil.keyToHashKey(task.getKey());
        mExecuteMap.remove(key);
        return mExecuteQueue.remove(task);
      }
    }
  } 
removeTask有加这个锁，为啥没有用？是不是在stopAllTask里面也需要添加这个？

**Comment by fishingcats** [comment]
我在stopAllTask上也加上了synchronized (AriaManager.LOCK) {这个锁，测试能用

**Comment by AriaLyy** [comment]
感谢你的 反馈，这问题应该是偶发的，加静态锁可以解决，也可以将HashMap替换为ConcurrentHashMap，回头我该下遍历那的代码，那部分有点问题

**Comment by AriaLyy** [comment]
```
compile 'com.arialyy.aria:aria-core:3.2.8'
annotationProcessor 'com.arialyy.aria:aria-compiler:3.2.8'
```
修复了问题
