### ISSUE TITLE
类转换异常

### ISSUE THREAD

**Issue by L-Kyle** [AriaLyy/Aria#805]
文件上传时出现的 ，最新版本，第一次使用上传功能，日志如下：

2020-11-20 11:37:18.280 29946-2199/com.kk.so I/UTaskQueue: 获取任务，key：/sdcard/base.apk
2020-11-20 11:37:18.287 29946-2199/com.kk.so D/BaseCachePool: 任务【base.apk】进入缓存队列成功
2020-11-20 11:37:18.289 29946-2199/com.kk.so D/StartCmd: 开始新任务, 任务状态：3
2020-11-20 11:37:18.289 29946-2199/com.kk.so I/UTaskQueue: 获取任务，key：/sdcard/base.apk
2020-11-20 11:37:18.289 29946-2199/com.kk.so I/UTaskQueue: 添加任务，key：/sdcard/base.apk
2020-11-20 11:37:18.289 29946-2199/com.kk.so D/UploadExecutePool: 任务【base.apk】进入执行队列成功
    
    --------- beginning of crash
2020-11-20 11:37:18.319 29946-2200/com.kk.so E/AndroidRuntime: FATAL EXCEPTION: Thread-20
    Process: com.kk.so, PID: 29946
    java.lang.ClassCastException: com.arialyy.aria.orm.DelegateFind cannot be cast to com.arialyy.aria.orm.DelegateUpdate
        at com.arialyy.aria.orm.DelegateWrapper.insertData(DelegateWrapper.java:181)
        at com.arialyy.aria.orm.DbEntity.insert(DbEntity.java:293)
        at com.arialyy.aria.orm.DbEntity.save(DbEntity.java:267)
        at com.arialyy.aria.core.common.RecordHandler.saveRecord(RecordHandler.java:183)
        at com.arialyy.aria.core.common.RecordHandler.getRecord(RecordHandler.java:96)
        at com.arialyy.aria.http.upload.HttpULoader.handleTask(HttpULoader.java:59)
        at com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:133)
        at com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:115)
        at java.lang.Thread.run(Thread.java:764)

**Comment by Equalzys** [comment]
怀疑是hashcode冲突导致的；
试试分别重写DelegateFind和DelegateUpdate这两个类的hashcode方法；
