### ISSUE TITLE
第二次下载组合任务SQL 错误

### ISSUE THREAD

**Issue by zl13701903024** [AriaLyy/Aria#810]
## 版本
* 框架版本 最新版本

* 系统版本

## 错误日志

 android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: DownloadEntity.downloadPath (code 2067)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1474)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1343)

## 重现步骤

1.下载一个组合任务 （第一次都成功）
2.再次下载也能成功但是SQL错误了（保存的目录跟第一次下载时一样）

**Comment by flyzend** [comment]
我也一样的步骤一样的错误。

**Comment by flyzend** [comment]
@AriaLyy 麻烦看一下，组合任务这个问题

**Comment by zl13701903024** [comment]
框架设计的时候 数据库中 dirPath是唯一的  我也不知道为啥这样设计  所以每一个组合任务都必须是不同的路径

**Comment by zmin666** [comment]
也遇到这个问题. 怎么解决呢
