### ISSUE TITLE
暂停下载，关闭并重启App后，点击继续下载报空指针异常

### ISSUE THREAD

**Issue by 1903514970** [AriaLyy/Aria#817]
## 版本
* 框架版本
  3.8.12
* 系统版本
Android 7.0
## 错误日志

java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.arialyy.aria.core.FtpUrlEntity.hostName' on a null object reference
        at com.arialyy.aria.ftp.AbsFtpInfoTask.createFtpClient(AbsFtpInfoTask.java:133)
        at com.arialyy.aria.ftp.AbsFtpInfoTask.run(AbsFtpInfoTask.java:94)
        at com.arialyy.aria.core.loader.NormalLoader.handleTask(NormalLoader.java:101)
        at com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:133)
        at com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:115)
        at java.lang.Thread.run(Thread.java:776)

## 重现步骤

1. 开启一个新的下载任务，可以正常下载
 private void downloadFtp(DBDocEntity dbDocEntity,String ftpPath){
        ServerFtpConfigEntity ftpConfigEntity = ServerFtpHelper.getFtpConfigEntity();
        dbDocEntity.setServerFilePath("ftp://"+ ftpConfigEntity.getIp()+":"+ftpConfigEntity.getPort()+ftpPath);
        long downloadTaskId = Aria.download(this).loadFtp("ftp://192.168.137.1:21/test2.apk")
                .setFilePath(dbDocEntity.getLocalVideoPath())
                .option(getFtpOption()).create();
        dbDocEntity.setDownloadTaskId(downloadTaskId);
    }

    private FtpOption getFtpOption() {
        FtpOption option = new FtpOption();
        option.login("dj02", "123456");
        option.setConnectionMode(FtpConnectionMode.DATA_CONNECTION_MODE_ACTIVITY);
        return option;
    }
2. 点击暂停下载。
      Aria.download(this).loadFtp(taskId).stop();
3. 然后杀掉App，进到页面后点击重新下载。
   Aria.download(this).loadFtp(taskId).resume();

4. 然后就闪退了。

**Comment by 1903514970** [comment]
解决了。
需要使用：Aria.download(this).loadFtp(taskId).option(options).resume();
