### ISSUE TITLE
任务组下载，报错路径不可写

### ISSUE THREAD

**Issue by LucasXu01** [AriaLyy/Aria#820]
## 版本
* 框架版本
    implementation 'com.arialyy.aria:core:3.8.15'
    annotationProcessor 'com.arialyy.aria:compiler:3.8.15'

* 系统版本
* android10

## 错误日志

2020-12-31 20:08:06.275 29898-30494/com.ysalliance.qifan W/System.err: java.io.IOException: No such file or directory
2020-12-31 20:08:06.275 29898-30494/com.ysalliance.qifan W/System.err:     at java.io.UnixFileSystem.createFileExclusively0(Native Method)
2020-12-31 20:08:06.275 29898-30494/com.ysalliance.qifan W/System.err:     at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
2020-12-31 20:08:06.275 29898-30494/com.ysalliance.qifan W/System.err:     at java.io.File.createNewFile(File.java:1008)
2020-12-31 20:08:06.275 29898-30494/com.ysalliance.qifan W/System.err:     at com.arialyy.aria.util.FileUtil.canWrite(FileUtil.java:706)
2020-12-31 20:08:06.275 29898-30494/com.ysalliance.qifan W/System.err:     at com.arialyy.aria.core.download.CheckDGEntityUtil.checkDirPath(CheckDGEntityUtil.java:72)
2020-12-31 20:08:06.275 29898-30494/com.ysalliance.qifan W/System.err:     at com.arialyy.aria.core.download.CheckDGEntityUtil.checkEntity(CheckDGEntityUtil.java:165)
2020-12-31 20:08:06.275 29898-30494/com.ysalliance.qifan W/System.err:     at com.arialyy.aria.core.common.controller.FeatureController.checkEntity(FeatureController.java:209)
2020-12-31 20:08:06.275 29898-30494/com.ysalliance.qifan W/System.err:     at com.arialyy.aria.core.common.controller.FeatureController.checkConfig(FeatureController.java:151)
2020-12-31 20:08:06.275 29898-30494/com.ysalliance.qifan W/System.err:     at com.arialyy.aria.core.common.controller.BuilderController.create(BuilderController.java:55)
2020-12-31 20:08:06.275 29898-30494/com.ysalliance.qifan W/System.err:     at com.arialyy.aria.core.common.AbsBuilderTarget.create(AbsBuilderTarget.java:80)
2020-12-31 20:08:06.275 29898-30494/com.ysalliance.qifan W/System.err:     at com.ysalliance.qifan.ui.music.improve.MusicRecordMVPActivity$3.run(MusicRecordMVPActivity.java:374)
2020-12-31 20:08:06.275 29898-30494/com.ysalliance.qifan W/System.err:     at java.lang.Thread.run(Thread.java:929)
2020-12-31 20:08:06.275 29898-30494/com.ysalliance.qifan E/CheckDGEntityUtil: 路径【/storage/emulated/0/faner/music/64cab6f0-90d5-11e9-965c-0242ac170004/】不可写

**Comment by LucasXu01** [comment]
权限已经给了

**Comment by GirlFriendNotFind** [comment]
一样的问题
