### ISSUE TITLE
Url转换器问题

### ISSUE THREAD

**Issue by yefangqingchen** [AriaLyy/Aria#845]
**Aria 版本 = 3.8.12**

**M3U8格式**
![image](https://user-images.githubusercontent.com/9261470/112989952-1519c900-9198-11eb-8cd4-6c33088f193e.png)

**自定义URL转换器**
![image](https://user-images.githubusercontent.com/9261470/112989998-24007b80-9198-11eb-8c47-d477c3380312.png)

**URL转换器回调方法中为何出现这种**
![image](https://user-images.githubusercontent.com/9261470/112990125-4a261b80-9198-11eb-81ac-26485af95369.png)

所以报错
连接错误，http错误码：403，url：http://cdn.oss-cn-hangzhou.aliyuncs.com.laobandq.com#EXTINF:2.458333,

**Comment by yefangqingchen** [comment]
**然后我加一个一个判断虽然下载完了，但是下的不全**
               tsUrls?.forEach {
                        if (it.contains("https") || it.contains("http")){
                            newUrls.add(it)
                        }else if (it.contains(".ts")){
                            newUrls.add(parentUrl + it)
                        }else{

                        }
                    }

**Comment by yefangqingchen** [comment]
9 5697-6264/com.hnkj.video W/System.err: com.arialyy.aria.exception.AriaM3U8Exception: Aria M3U8 Exception:
2021-03-30 20:30:21.800 5697-6264/com.hnkj.video W/System.err: 连接错误，http错误码：403，url：http://cdn.oss-cn-hangzhou.aliyuncs.com.laobandq.com#EXTINF:2.458333,
2021-03-30 20:30:21.802 5697-6264/com.hnkj.video W/System.err:     at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handleConn(M3U8ThreadTaskAdapter.java:141)
2021-03-30 20:30:21.803 5697-6264/com.hnkj.video W/System.err:     at com.arialyy.aria.m3u8.M3U8ThreadTaskAdapter.handlerThreadTask(M3U8ThreadTaskAdapter.java:92)
2021-03-30 20:30:21.803 5697-6264/com.hnkj.video W/System.err:     at com.arialyy.aria.core.task.AbsThreadTaskAdapter.call(AbsThreadTaskAdapter.java:54)
2021-03-30 20:30:21.804 5697-6264/com.hnkj.video W/System.err:     at com.arialyy.aria.core.task.ThreadTask.call(ThreadTask.java:547)
2021-03-30 20:30:21.804 5697-6264/com.hnkj.video W/System.err:     at com.arialyy.aria.core.task.ThreadTask.call(ThreadTask.java:47)
2021-03-30 20:30:21.804 5697-6264/com.hnkj.video W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-03-30 20:30:21.804 5697-6264/com.hnkj.video W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-03-30 20:30:21.804 5697-6264/com.hnkj.video W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-03-30 20:30:21.804 5697-6264/com.hnkj.video W/System.err:     at java.lang.Thread.run(Thread.java:929)

**Comment by yefangqingchen** [comment]
![image](https://user-images.githubusercontent.com/9261470/113082784-a70fe900-920d-11eb-9ed9-d6c157e0a3f0.png)

**Comment by yefangqingchen** [comment]
在转换器中过滤后

         tsUrls?.forEach {
                    if (it.contains("http")){
                        newUrls.add(it)
                    }else if (it.contains(".ts")){
                        newUrls.add(parentUrl + it)
                    }else if (it.contains("#EXTINF")){

                    }
                }

**Comment by yefangqingchen** [comment]
https://cdn.oss-cn-hangzhou.aliyuncs.com.laobandq.com/m3u8/shishenling2021.m3u8
