### ISSUE TITLE
如何获取下载失败消息

### ISSUE THREAD

**Issue by shengdoushi** [AriaLyy/Aria#855]
当前使用的版本是 3.8.15， 在下载一个404 的下载资源 时如何获知下载失败消息？

**Comment by shengdoushi** [comment]
日志中错误如下：

I/DTaskQueue: 获取任务，key：http://XXXXXX:8088/mapps/rateclient/app/v1.0.apk
    添加任务，key：http://XXXXXX:8088/mapps/rateclient/app/v1.0.apk
D/DLoadExecutePool: 任务【update.apk】进入执行队列成功
D/Surface: Surface::final mReqUsage=602
D/DTaskQueue: 从执行池删除任务【update.apk】成功
I/TaskSchedulers: 没有等待中的任务
E/BaseDListener: ExceptionDetailed:
    ====================Exception Info====================
    com.arialyy.aria.exception.AriaHTTPException: Aria HTTP Exception:
    任务下载失败，errorCode：404, url: http://222.134.6.130:8088/mapps/rateclient/app/v1.0.apk
    com.arialyy.aria.http.download.HttpDFileInfoTask.handleConnect(HttpDFileInfoTask.java:242)
    com.arialyy.aria.http.download.HttpDFileInfoTask.run(HttpDFileInfoTask.java:90)
    com.arialyy.aria.core.loader.NormalLoader.handleTask(NormalLoader.java:101)
    com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:133)
    com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:115)
    java.lang.Thread.run(Thread.java:818)
    ===================================================
W/System.err: java.io.FileNotFoundException: http://XXXXXX:8088/mapps/rateclient/app/v1.0.apk
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:238)
        at com.arialyy.aria.http.download.HttpDFileInfoTask.run(HttpDFileInfoTask.java:98)
W/System.err:     at com.arialyy.aria.core.loader.NormalLoader.handleTask(NormalLoader.java:101)
        at com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:133)
        at com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:115)
        at java.lang.Thread.run(Thread.java:818)
