### ISSUE TITLE
publicComponents中FileUtil代码的问题

### ISSUE THREAD

**Issue by aolphn** [AriaLyy/Aria#890]
FileUtil中很多代码都会直接使用`new StatFs(path)`，StatFs内部的代码：
```
    public StatFs(String path) {
        mStat = doStat(path);
    }
    private static StructStatVfs doStat(String path) {
        try {
            return Os.statvfs(path);
        } catch (ErrnoException e) {
            throw new IllegalArgumentException("Invalid path: " + path, e);
        }
    }
```
可以看到doStat方法会抛出IllegalArgumentException异常，这种代码会遇到的异常如下：
```
java.lang.IllegalArgumentException: Invalid path: /storage/emulated/0/xxoo/download
	at android.os.StatFs.doStat(StatFs.java:53)
	at android.os.StatFs.<init>(StatFs.java:43)
	at com.arialyy.aria.util.FileUtil.checkMemorySpace(SourceFile:514)
	at com.arialyy.aria.http.download.HttpDFileInfoTask.handleConnect(SourceFile:140)
	at com.arialyy.aria.http.download.HttpDFileInfoTask.run(SourceFile:90)
	at com.arialyy.aria.core.loader.NormalLoader.handleTask(SourceFile:101)
	at com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(SourceFile:133)
	at com.arialyy.aria.core.loader.AbsNormalLoader.run(SourceFile:115)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.system.ErrnoException: statvfs failed: ENOENT (No such file or directory)
	at libcore.io.Linux.statvfs(Native Method)
	at libcore.io.ForwardingOs.statvfs(ForwardingOs.java:223)
	at libcore.io.BlockGuardOs.statvfs(BlockGuardOs.java:398)
	at libcore.io.ForwardingOs.statvfs(ForwardingOs.java:223)
	at android.system.Os.statvfs(Os.java:662)
	at android.os.StatFs.doStat(StatFs.java:51)
```
因此建议在new StatFs外部加入相应的异常处理，否则内部抛出IllegalArgumentException会直接crash，或者作者特意不加是出于什么样的考虑，希望得到科普，如果作者接受的话我可以提个mr。

**Comment by aolphn** [comment]
纳尼？现在机器人这么狗了，直接给关了吗？
