### ISSUE TITLE
ndroid.database.sqlite.SQLiteException: no such column: filePath (code 1 SQLITE_ERROR): , while compiling: SELECT rowid, * FROM M3U8Entity WHERE filePath=?

### ISSUE THREAD

**Issue by JavanLuo** [AriaLyy/Aria#897]
android.database.sqlite.SQLiteException: no such column: filePath (code 1 SQLITE_ERROR): , while compiling: SELECT rowid, * FROM M3U8Entity WHERE filePath=?
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:903)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:514)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)

**Comment by hezheng1978** [comment]
第一使用，我也出现这个问题，是修复了还没发新版本吗？
