### ISSUE TITLE
下载闪退：NumberFormatException: For input string: "1318\r"

### ISSUE THREAD

**Issue by liyujiang-gzu** [AriaLyy/Aria#949]
## 版本
* 框架版本
3.8.16
* 系统版本
Android 11
## 错误日志

java.lang.NumberFormatException: For input string: "1318\r"
        at java.lang.Long.parseLong(Long.java:594)
        at java.lang.Long.parseLong(Long.java:636)
        at com.arialyy.aria.http.download.HttpDFileInfoTask$FileLenAdapter.handleFileLen(HttpDFileInfoTask.java:404)
        at com.arialyy.aria.http.download.HttpDFileInfoTask.handleConnect(HttpDFileInfoTask.java:147)
        at com.arialyy.aria.http.download.HttpDFileInfoTask.run(HttpDFileInfoTask.java:91)
        at com.arialyy.aria.core.loader.NormalLoader.handleTask(NormalLoader.java:101)
        at com.arialyy.aria.core.loader.AbsNormalLoader.startFlow(AbsNormalLoader.java:133)
        at com.arialyy.aria.core.loader.AbsNormalLoader.run(AbsNormalLoader.java:115)
        at java.lang.Thread.run(Thread.java:923)

## 重现步骤

定位到触发闪退的代码：
```
      List<String> sLength = headers.get("Content-Length");
      if (sLength == null || sLength.isEmpty()) {
        return -1;
      }
      String temp = sLength.get(0);
      long len = TextUtils.isEmpty(temp) ? -1 : Long.parseLong(temp);
```
目测是Content-Length的换行符是“\r\n”，`String temp = sLength.get(0);`需要`trim()`删掉回车符？

**Comment by 333bkz** [comment]
/**
   * 如果你需要使用header中特定的key来设置文件长度，或有定制文件长度的需要，那么你可以通过该方法自行处理文件长度
   */
  public HttpOption setFileLenAdapter(IHttpFileLenAdapter fileLenAdapter) {
    if (fileLenAdapter == null) {
      throw new IllegalArgumentException("adapter为空");
    }
    CheckUtil.checkMemberClass(fileLenAdapter.getClass());
    this.fileLenAdapter = fileLenAdapter;
    return this;
  }

**Comment by liyujiang-gzu** [comment]
> /**
> 
> * 如果你需要使用header中特定的key来设置文件长度，或有定制文件长度的需要，那么你可以通过该方法自行处理文件长度
>   */
>   public HttpOption setFileLenAdapter(IHttpFileLenAdapter fileLenAdapter) {
>   if (fileLenAdapter == null) {
>   throw new IllegalArgumentException("adapter为空");
>   }
>   CheckUtil.checkMemberClass(fileLenAdapter.getClass());
>   this.fileLenAdapter = fileLenAdapter;
>   return this;
>   }

非常感谢指点！
