### ISSUE TITLE
java.lang.NullPointerException 组合下载偶尔会出现ConcurrentHashMap的key为null的情况

### ISSUE THREAD

**Issue by wangdakuan** [AriaLyy/Aria#965]
## 版本
* 框架版本
    api 'me.laoyuyu.aria:core:3.8.16'
    kapt 'me.laoyuyu.aria:compiler:3.8.16'

* 系统版本

## 错误日志
Process Name: 'com.piaxiya.app'
Thread Name: 'Thread-119'
Back traces starts.
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
 at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:948)
 at com.arialyy.aria.core.group.SimpleSubQueue.getLoaderUtil(SimpleSubQueue.java:1)
 at com.arialyy.aria.core.group.SimpleSchedulers.handleMessage(SimpleSchedulers.java:4)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:210)
 at com.arialyy.aria.core.group.AbsGroupLoader.startRunningFlow(AbsGroupLoader.java:12)
 at com.arialyy.aria.core.group.AbsGroupLoader.run(AbsGroupLoader.java:3)
 at java.lang.Thread.run(Thread.java:764)
Back traces ends.

## 重现步骤
自测没有出现，在生产上每天会出现几次异常

**Comment by wangdakuan** [comment]
这个问题还是存在
